### ISSUE TITLE
Add an option to make pyright output less verbose

### ISSUE THREAD

**Issue by jamielinux** [microsoft/pyright#4807] opened 2023-03-20 15:25 UTC
**Is your feature request related to a problem? Please describe.**

When I run `pyright`, it gives me a lot of output:

```console
$ pyright
No configuration file found.
pyproject.toml file found at /tmp/project.
Loading pyproject.toml file at /tmp/project/pyproject.toml
Assuming Python version 3.11
Assuming Python platform Linux
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /tmp/project/typings is not a valid directory.
Searching for source files
Found 5 source files
pyright 1.1.299
0 errors, 0 warnings, 0 informations
Completed in 0.753sec
```

`pyproject.toml` contains just this for `pyright`:

```toml
[tool.pyright]
include = ["."]
```

**Describe the solution you'd like**

It'd be nice if most of this output could be put behind the `--verbose` flag, perhaps cutting it down to something like this:

```console
Found 5 source files
pyright 1.1.299
0 errors, 0 warnings, 0 informations
Completed in 0.753sec
```

Thanks for this amazing tool!

**Comment by erictraut** [comment] 2023-03-20 18:12
This is a duplicate of https://github.com/microsoft/pyright/issues/4594. Please upvote the original issue.

**Closed by erictraut** 2023-03-20 18:12 UTC
Labels: enhancement request
