### ISSUE TITLE
Can't recognize venv settings

### ISSUE THREAD

**Issue by wd** [Microsoft/pyright#30] opened 2019-03-29 06:39 UTC
My project is based on django, with virtualenv.

```
{
  "typingsPath": "./typestubs",

  "reportTypeshedErrors": false,
  "reportMissingImports": true,
  "reportMissingTypeStubs": false,

  "executionEnvironments": [
    {
      "root": "./",
      "venv": "./.venv",
      "extraPaths": [
        "./3rd-modules"
      ]
    }
  ]
}
```

`.venv` is the vritualenv environment directory, but I still get `django.xx could not be resolved` errors. I have tried set  `venvPath` to "./" but still not work.

```
  Import 'django.db' could not be resolved
```

**Comment by erictraut** [comment] 2019-03-29 06:51
The "venv" config tag shouldn't contain a path. It should contain the name of the virtual environment you want to use for the execution environment. That venv is assumed to be the name of a subdirectory within the "venvPath".

Typically the pyrightconfig.json file is located at the root of your source directory, and venvPath points to some place outside of your source directory. The venvPath can be specified in the config file, through VS Code settings, or a command-line option.

**Comment by wd** [comment] 2019-03-29 07:04
My `venvPath` is in the project root directory, it's directory name is `.venv`, I've tried `"venv": ".venv"`, it's not working. So should I move the directory out of my project ?

**Comment by erictraut** [comment] 2019-03-29 07:07
Yeah, create a directory somewhere outside of your source directory. In my case, I use the path '~/venvs/'. Then create one or more virtual environments within this directory. In my case, I have one called "py35" and another called "py36", and I have different versions of the python environment installed in each.

**Comment by wd** [comment] 2019-03-29 07:21
I've tried as you said, but still get the errors. Here is my steps.

```
$ mkdir ~/venvs
$ cd ~/venvs
$ virtualenv py36
$ source ~/venvs/py36/bin/activate.fish
$ cd MY_PROEJCT
$ pip install -r requirements.txt  # here will be install django in ~/venvs/py36
$ ls ~/venvs/py36/lib/python3.6/site-packages/django/
__init__.py  __main__.py  __pycache__  apps         bin          conf         contrib      core         db           dispatch     forms        http         middleware   shortcuts.py template     templatetags test         urls         utils        views
$ ./node_modules/.bin/pyright -p ./
```

```
{
  "include": [
    "./",
  ],
  "typingsPath": "./typestubs",
  "venvPath": "~/venvs/",

  "reportTypeshedErrors": false,
  "reportMissingImports": true,
  "reportMissingTypeStubs": false,

  "executionEnvironments": [
    {
      "root": "./",
      "venv": "py36",
      "extraPaths": [
        "./3rd-modules"
      ]
    }
  ]
}
```

**Comment by erictraut** [comment] 2019-03-29 07:23
Shell variables and path shortcuts like "~" aren't supported in the pyright config file. You'll need to expand "~/venvs/" yourself. Or pass the path on the command line from the shell.

**Comment by wd** [comment] 2019-03-29 07:37
I've tried to change the `"venvPath": "/Users/wd/venvs",`, but still not work.

```
/Users/wd/work/......../apps.py
  Import 'django.apps' could not be resolved (1, 6)
/Users/wd/work/........execute_raw_sql.py
  Import 'django.db' could not be resolved (4, 6)
  Import 'django.conf' could not be resolved (5, 6)
/Users/wd/work/............/ga_helpers.py
  Import 'filetype' could not be resolved (1, 8)
  Import 'django.utils' could not be resolved (9, 6)
  Import 'django.contrib.gis.geos' could not be resolved (10, 6)
  Import 'django.db.models' could not be resolved (11, 6)
  Import 'django.db.utils' could not be resolved (12, 6)
  Import 'django.conf' could not be resolved (13, 6)
  Import 'django.contrib.gis.db.models.functions' could not be resolved (14, 6)
```

**Comment by erictraut** [comment] 2019-03-29 08:14
I found a bug in the config file parsing code where it wasn't correctly picking up the venvPath entry. In my testing, I've always used either the command-line "-v" switch or the VS Code "python.venvPath" setting. I've pushed a fix, and it will be in the next version of pyright. In the meantime, you can specify the venvPath using the "-v" command-line option.

I also noticed that you have a hanging comma in your config file, which is invalid JSON, so the standard JSON parser will probably fail to parse that.

**Comment by wd** [comment] 2019-03-29 08:52
Oh, the comma is a mistake while I remove some settings there but forgot the comma.

After set `"python.venvPath": "/Users/wd/venvs",` in VS Code, it seems working now.

More discuss about the `.venv` directory. I'd like to put it in the project directory, since different project may have different python version, different package version, for example one project work with python 3.6 and django 1.9, requests 2.7, others may work with python 3.6, django 2.1, requests 3.4, and so on, I think put the `.venv` directory with the project may be better than put them together in this situation. And also I can write a script for `fish` shell (which I use) to auto activate the environment every time I enter the directory.

**Closed** 2019-03-29 11:08 UTC

**Comment by erictraut** [comment] 2019-03-29 15:22
Placing your venv directory within the root of your source code should work, but I'd generally recommend not doing that because you'll need to exclude it from pyright (using the "exclude" config setting), git (using the gitignore file), and any other tool that operates over the entire code directory. If you're working on the code with other collaborators, it's best to agree on the name(s) of the venvs and include them in the pyrightconfig.json file but then let each collaborator specify their own venvPath.

**Comment by Imaclean74** [comment] 2019-03-31 05:20
it's pretty common to have the venv directory under root as something like .venv - which is pretty well supported by the vscode python plugin. Anyone using this approach will likely have .venv added to .gitignore anyway.

**Comment by wd** [comment] 2019-04-01 08:37
To those who may like put `.venv` dir in the project root, you can use these settings to cheat pyright.

```
{
  "exclude": [ ".venv" ],
  "venvPath": "./.venv/",
  "typingsPath": "./typestubs",

  "reportTypeshedErrors": false,
  "reportMissingImports": true,
  "reportMissingTypeStubs": false,

  "executionEnvironments": [
    {
      "root": "./",
      "venv": "./",
      "extraPaths": [
        "./3rd-modules"
      ]
    }
  ]
}
```

**Comment by Imaclean74** [comment] 2019-04-02 15:01
cool - that worked. Looks like it was the executionEnvironment venv setting that did it. I wonder though - is it worth auto checking for a .venv or similar folder in the root ?  Seems common enough user pattern to cater for.

**Comment by wd** [comment] 2019-04-06 00:50
Yeh, I've checked [python doc](https://github.com/openstack/python-manilaclient/blob/master/tools/install_venv.py), it's example is put a `venv` directory in proejct_folder.

![image](https://user-images.githubusercontent.com/58177/55662707-f0acdf80-5850-11e9-9817-63ceab94d815.png)

And openstack [install_vevn.py](https://github.com/openstack/python-manilaclient/blob/master/tools/install_venv.py), it's default directory is `.venv`.

I think virtual env in project folder is a common pattern.

**Comment by balsagoth** [comment] 2019-04-30 10:08
Is there any way to configure pyright to use the setting `python.venvPath` configured on vscode? 
Configuring venvPath on pyrightconfig.json will require that all people working on a project to have the venv path on the same relative location.

**Comment by erictraut** [comment] 2019-04-30 15:33
Pyright already uses the setting `python.venvPath` from VS Code if it's present and not overridden by the venvPath in the pyrightconfig.json.

**Comment by balsagoth** [comment] 2019-05-03 16:30
You are right. I have fixed my `pyrightconfig.json` settings. Thanks.

**Comment by dcsanx** [comment] 2020-05-30 00:13
hi! I'm just hitting this thread, which are the `pyrightconfig.json` file and which is a general vscode project settings file and what should it be called? some filenames and examples would be helpful.

**Comment by exhuma** [comment] 2022-01-02 10:12
Since the last time I came across this things seem to have changed in the way VS-Code handles Python environment (the setting `python.venvPath` no longer exists).

Our team also keeps the venv folder inside each project. Typically because each project has its own dependencies, distinct from other projects. So we would have to keep a separate folder per project anyway. We keep it in the project folder to keep things more organised.

Yet, specifying `venvPath` and `venv` in the pyright config does not seem to work. I have this in my `pyproject.toml`:

```
[tool.pyright]
strict = ["strec"]
ignore = ["tests"]
venvPath = "."
venv = "env"
```

It does not seem to pick up on the items in the `env` folder.

**Comment by baggiponte** [comment] 2022-09-14 18:32
Hi @exhuma, my venv is in `./.venv` so I set:

```toml
exclude = [ ".venv" ]
venvPath = "."
venv = ".venv"
```

And pyright now works!

**Comment by exhuma** [comment] 2022-09-15 08:03
@baggiponte I can confirm that this works. Thank you.

The combination of `venvPath` and the `exclude` part were important.

**Comment by nithin-mk** [comment] 2022-11-25 17:50
@baggiponte @exhuma Is it necessary to specify the venv in `exclude` now? The [documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) says:

> If no exclude paths are specified, Pyright automatically excludes the following: **/node_modules, **/__pycache__, .git and any virtual environment directories.

Also, it says:

> Note that files in the exclude paths may still be included in the analysis if they are referenced (imported) by source files that are not excluded.

So, a venv file might still be automatically included, if it is imported in the application!

**Comment by baggiponte** [comment] 2022-12-09 08:52
Hi @nithin-mk, sorry for the late reply. I believe that the second quote you wrote is exactly why you need to specify `exclude = [".venv"]`: contents of the venv are imported by source files by definition. I just made a quick check with the backend of a website I am managing and pyright became unable to work because it had too many files to scan: ~10k, because it was scanning all of the dependencies.

**Comment by tankorsmash** [comment] 2023-09-28 17:33
For me, the issue appears to be a trailing comma in my `pyrightconfig.json`.

```json
{
	"venvPath": "C:/path/to/folder",
	"venv": "env-name",
}
```
didn't let Neovim/CoC detect my files, but changing it to

```json
{
	"venvPath": "C:/path/to/folder",
	"venv": "env-name"
}
```

did. Seems like it shouldn't have been an issue but it's working now.
