### ISSUE TITLE
imports "is not accessed" even though they are accessed and being used.

### ISSUE THREAD

**Issue by leet0rz** [microsoft/pyright#5851] opened 2023-08-30 11:41 UTC
What it looks like:
![EEFkmjT 1](https://github.com/microsoft/pyright/assets/29175192/6a1a465c-380b-4ef2-a960-e792cb1d4f78)

**Describe the bug**
use nvim with pyright lsp. typeCheckingMode = 'off/basic/strict', seems to be the setting that control these but I've only managed to turn it from red to this. It seems to happen with all non-standard libs even though they have been installed without issues and are working just fine in the code.

```
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QComboBox,
    QDateEdit,
    QDateTimeEdit,
    QDial,
    QDoubleSpinBox,
    QFontComboBox,
    QLCDNumber,
    QLabel,
    QLineEdit,
    QMainWindow,
    QProgressBar,
    QPushButton,
    QRadioButton,
    QSlider,
    QSpinBox,
    QTextEdit,
    QTimeEdit,
    QVBoxLayout,
    QWidget,
)
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension, a language server in another editor, integrated into Pylance, or the command-line tool? Which version?

Just regular pyright with lspconfig and nvim.

NVIM v0.10.0-dev-798+g72e619ca9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

**Comment by erictraut** [comment] 2023-08-30 13:50
This is a duplicate of https://github.com/microsoft/pyright/issues/4652.

**Closed by erictraut** 2023-08-30 13:50 UTC
Labels: bug
