### ISSUE TITLE
Workspace `diagnosticSeverityOverrides` ignored with presence of `pyproject.toml`

### ISSUE THREAD

**Issue by sventec** [microsoft/pyright#8239] opened 2024-06-26 18:14 UTC
**Describe the bug**

Starting from pyright version 1.1.364, the presence of a `pyproject.toml` (even if empty) in a project root seems to override/nullify any `diagnosticSeverityOverrides` present in a vscode workspace config (`settings.json`). I was also able to reproduce this in neovim, by passing `diagnosticSeverityOverrides` via `nvim-lspconfig`.

Steps to reproduce are as follows:

1. Install the vscode pyright extension (though I was also able to reproduce in other editors)
2. Open a folder/workspace, and create a test Python file
3. Create an empty `pyproject.toml` in the folder/workspace root
4. Add `python.analysis.diagnosticSeverityOverrides` to the folder's workspace settings (`./.vscode/settings.json`)
5. Observe that any diagnostics raised in the test file do not respect these severity overrides
6. Delete the empty `pyproject.toml` from the workspace
7. Observe that, after deletion of `pyproject.toml`, the workspace diagnostic severity overrides are respected in the test file

During testing in some cases, I needed to remove/re-add the overrides to `settings.json`, or restart vscode, after creating `pyproject.toml`, before the overrides would be ignored. However, immediately after removing `pyproject.toml`, overrides are respected again.

This issue only seems to exist in pyright versions newer than 1.1.364. Version 1.1.364 and older works as expected given this test scenario.

**Code or Screenshots**

Create a directory structure as follows:

![image](https://github.com/microsoft/pyright/assets/18218761/a2f46393-f119-4ed3-9e3d-8c1a51df90c7)

The file `test.py` contains the following code:

```python
foo = 1
foo.someattr  # error 'reportAttributeAccessIssue' reported here
```

The file `settings.json` contains the following settings:

```json
{
  "python.analysis.diagnosticSeverityOverrides": {
    "reportAttributeAccessIssue": false
  },
}
```

The file `pyproject.toml` does not need to contain anything specific, it simply needs to exist in the project root.

As seen in this screenshot, with an empty `pyproject.toml` in the project root, the override present in `settings.json` is not respected :

![image](https://github.com/microsoft/pyright/assets/18218761/51977aa7-10ca-41be-8fc3-bc6ccc025fad)

However, when `pyproject.toml` is deleted, and no other changes are made, the severity override works as intended:

![image](https://github.com/microsoft/pyright/assets/18218761/0e864efe-d686-4e73-b131-e95e41c41845)

**VS Code extension or command-line**

Pyright vscode extension, version v1.1.369. Latest version without this bug is v1.1.364.

**Comment by erictraut** [comment] 2024-06-26 19:07
This is a duplicate of https://github.com/microsoft/pylance-release/issues/6052. Someone from the pylance team has already been assigned the issue, so I'm going to close this one as a duplicate.

Apologies for the regression.

**Closed by erictraut** 2024-06-26 19:07 UTC
Labels: bug

**Comment by sventec** [comment] 2024-06-26 19:09
Oops, should have checked the pylance repo before opening this. Thanks Eric!
