### ISSUE TITLE
Support multiple packages with overlapping namespaces

### ISSUE THREAD

**Issue by SandyChapman** [microsoft/pyright#2882] opened 2022-01-17 16:24 UTC
In our projects, we use multiple libraries distributed by Google for interacting with Google Cloud. Two such libraries are `google-cloud-bigquery` and `google-cloud-storage`. One feature of these libraries, is that they share a common namespace when importing them. For these two examples, they share `google.cloud` (I.e. `google.cloud.storage` and `google.cloud.bigquery`). Google implements this pattern using [`pkgutil`'s `extend_path`](https://docs.python.org/3/library/pkgutil.html#pkgutil.extend_path) function (see [here](https://github.com/googleapis/python-storage/blob/main/google/cloud/__init__.py) and [here](https://github.com/googleapis/python-bigquery/blob/main/google/cloud/__init__.py)).

However, this pattern introduces problems for Pyright as it appears it only resolves the first instance of a namespace when searching for members.

Here's a simple example:

We have two packages, `dep_1` and `dep_2`, contained in a directory `deps`. Both of these deps have a package with the same name, and subpackages with differing names.

E.g.

```
.
┣ deps
┃  ┣ dep_1
┃  ┃ ┗ pkg
┃  ┃   ┣ __init__.py
┃  ┃   ┗ a
┃  ┃     ┗ __init__.py
┃  ┗ dep_2
┃    ┗ pkg
┃      ┣ __init__.py
┃      ┗ b
┃        ┗ __init__.py
┗ main.py
```

After adding the packages to my PYTHONPATH, I can execute main.py which imports from both pkg.a and pkg.b and works at runtime.

```python
from pkg import a
from pkg import b

print(a.A())
print(b.B())
```

However, this results in Pyright detecting `a` as a valid namespace for `pkg` but not `b`.

```
➤ pyright ./main.py
Loading configuration file at <snip>/pyrightconfig.json
Assuming Python version 3.8
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding .git
stubPath <snip>/typings is not a valid directory.
Searching for source files
Found 1 source file
<snip>/main.py
  <snip>/main.py:2:17 - error: "b" is unknown import symbol (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos 
Completed in 0.737sec
```

For ease of reproducibility, you can find this example here: https://github.com/SandyChapman/pkgutil_import_example

**Describe the solution you'd like**

Pyright should attempt to resolve modules / sub-packages from all possible entries in `PYTHONPATH` before raising an error.

**Comment by erictraut** [comment] 2022-01-17 18:07
If both instances of `pkg` share the same namespace, it should be a "namespace package" rather than a traditional package with a top-level `__init__.py` file. Consider what would happen if both packages included a symbol `c` in their respective `__init__.py` files and you used the import statement `from pkg import c`. Which one would it refer to?

If you delete the `__init__.py` within both `pkg` directories, it should work as expected. I'm not sure why it's working when you run it in the interpreter, since that seems to contradict the expectations of [PEP 420](https://www.python.org/dev/peps/pep-0420/). Perhaps the google packages are performing some dynamic runtime magic like `__path__ = extend_path(__path__, __name__)`. Those sort of dynamic manipulations won't work for a static type checker.

**Comment by SandyChapman** [comment] 2022-01-17 18:37
I believe the Google packages are using the `pkgutil-style` namespace packages as specified here:

https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages

This is notably an alternative to the *implicit* namespace packages (defined in PEP 420) because the namespacing is *explicit* instead. The Python Package Authority basically gives the same example as I specified above here: https://github.com/pypa/sample-namespace-packages/tree/master/pkgutil

Since I don't maintain the Google libs, I cannot realistically delete the `__init__.py` in the namespace package, but I would just like to point out that this is a standard method of constructing packages for usage.

I believe the result of pip installing these is a merged directory in your python packages, however, because of our tooling, this isn't desirable and we'd rather point to the packages directly using PYTHONPATH.

**Comment by erictraut** [comment] 2022-01-17 20:46
Ah, I see. When these packages are installed, the installer effectively places them into a common namespace. Prior to installation, they are in separate namespaces. Correct me if I'm wrong, but I don't think the python interpreter would be able to resolve these if you configured it to point to these two separate (uninstalled) packages in different directories.

I don't think we'd be interested in supporting this in pyright. Package import resolution is already ridiculously complex in Python, and we do our best to match the behaviors of the Python interpreter the best we can. This would deviate from the behavior and result in false negative errors.

I think your options are:
1. Use the installed versions of these packages, which are combined into a single namespace.
2. Manually modify the packages such that they are explicitly merged into a single directory hierarchy.
3. Manually modify the packages such that they are seen by pyright as implicit namespace packages.
4. Use the aliasing trick you discovered above.

**Closed** 2022-01-18 06:27 UTC
Labels: as designed

**Comment by SandyChapman** [comment] 2022-01-18 12:30
@erictraut : I would have also thought you were right, but the Python interpreter does in fact seem to handle this gracefully:

![image](https://user-images.githubusercontent.com/3920249/149936480-6c0bc430-5622-4988-83b9-d45e22036aa0.png)

You can see in the screenshot above that by adding the two packages in different directories with the same namespace, the Python interpreter can properly import both `a` and `b`.

After trying your suggestion to remove the `__init__.py` files from the namespace directory to leverage the implicit namespace packages, I'm still seeing the exact same result so I'm not sure they are working as expected either.

![image](https://user-images.githubusercontent.com/3920249/149937444-940510ba-49cb-499d-a613-f29fb765ae52.png)

**Comment by SandyChapman** [comment] 2022-01-18 17:10
@erictraut : I've put together a small changeset that should allow this to resolve this type of namespace package. Essentially, I wrote a function to create a parseTree of the __init__.py file and validate it's equivalent to `__path__ = __import__('pkgutil').extend_path(__path__, __name__)`. Since the docs emphasize that the __init__.py must contain ONLY this statement, I feel like this is a reasonable way to detect these types of packages. Can you let me know if you're open to receive a PR based on this pattern and I can open one?

**Comment by SandyChapman** [comment] 2022-01-18 17:14
@erictraut I've put together a PoC for detecting these types of namespace packages by building a parseTree of the file and detecting the pkgutil usage. I'm wondering if you'd be open to a PR adding the functionality for pkgutil and pkg_resource namespace packages? If so, I'll try to extend my PoC to capture the other cases (such as what the Google Cloud libs do).

**Comment by erictraut** [comment] 2022-01-19 04:40
As I suspected, the code in question is dynamically manipulating path variables at runtime. We don't have plans to support such dynamic behaviors. I'm sorry, but you'll need to find a different workaround here.

**Comment by SandyChapman** [comment] 2022-01-19 12:31
Understood. Thanks, again!

**Comment by ms-lolo** [comment] 2024-04-30 17:35
> As I suspected, the code in question is dynamically manipulating path variables at runtime. We don't have plans to support such dynamic behaviors. I'm sorry, but you'll need to find a different workaround here.

hey @erictraut, sorry for reviving an old thread, but i am currently working in a project that has two namespace packages similar to this ticket, but i am not including the init files within the top namespace, and i'm not making any dynamic changes to variables, but i'm still seeing `reportAttributeAccessIssue` errors on the import lines. could you help me understand what is wrong here? i think we're following all the latest best practices for namespace packages but maybe i'm missing something.

![image](https://github.com/microsoft/pyright/assets/61251739/76172e54-fa45-4305-8164-f49406aa79ca)
^ this is the `rats.apps` package. no `__init__.py` file in the `src/python/rats` folder.

![image](https://github.com/microsoft/pyright/assets/61251739/50e4c62e-cc06-4985-8120-37bccfef5e37)
^ this is the `rats.devtools` package with a similar structure.

`from rats import apps, devtools` works as expected, by pyright reports `devtools` as an unknown import symbol

**Comment by erictraut** [comment] 2024-04-30 17:51
@ms-lolo, it sounds like your situation is unrelated to this thread. It's difficult to diagnose the cause of the problem you're seeing from a couple of screen shots. I recommend that you try to simplify the problem to a minimal reproducible case. That will probably help you figure out what's wrong, but if you get stuck, you can throw a question (with all the repro details) into the pyright discussion forum, and I can help you out.

**Comment by ms-lolo** [comment] 2024-04-30 20:24
thanks i'll set up an example in a branch and open a new discussion
