### ISSUE TITLE
An isinstance is not considered for types in List

### ISSUE THREAD

**Issue by LarsNeR** [microsoft/pyright#491] opened 2020-01-21 08:57 UTC
**Describe the bug**
An `all(isinstance(x, mytype))` is not considered in following statements. I am not sure if that is a bug or a feature request.

**To Reproduce**
See following code. There is a warning at `return my_list` because `my_list` can have `str` or `int` elements according to the signature. The `all(isinstance())` before that line ensures that it is only `int` in that `elif` but pyright still shows that warning. `my_method2` works as expected because here is only a single `isinstance` and not a list.
```
from typing import List, Union

def my_method(my_list: List[Union[str, int]]) -> List[int]:
    if all(isinstance(n, str) for n in my_list):
        return [int(x) for x in my_list]
    elif all(isinstance(n, int) for n in my_list):
        return my_list # Expression of type 'List[Union[str, int]]' cannot be assigned to return type 'List[int]' Type 'Union[str, int]' cannot be assigned to type 'int' Pyright
    return [0]

def my_method2(my_var: Union[str, int]) -> int:
    if isinstance(my_var, str):
        return int(my_var)
    if isinstance(my_var, int):
        return my_var
    return 0

print(my_method(["1", "2", "3"]))
print(my_method([1, 2, 3]))
```

**Expected behavior**
The warning is not correct because the `all(isinstance())` ensures that `my_list` is of type `List[int]`. I expected it to work the same way as it works for single elements (see `my_method2`).

**VS Code extension or command-line**
I am using it as VS Code extension in Version 1.1.21

**Comment by erictraut** [comment] 2020-01-21 16:23
This is a duplicate of #489. Please see the comments in that bug.

In short, this is expected behavior, not a bug.

**Closed** 2020-01-24 17:56 UTC
Labels: as designed
