### ISSUE TITLE
Invalid type in except clause with return in try body

### ISSUE THREAD

**Issue by tkukushkin** [microsoft/pyright#3106] opened 2022-02-23 17:47 UTC
**Describe the bug**
Pyright shows wrong type of variable inside `except` clause when there is `return` inside `try` body.

**To Reproduce**

```python
from typing import Optional, ContextManager

def create_context() -> ContextManager[str]: ...
def possible_exception() -> None: ...

def main() -> None:
    ctx: Optional[str] = None
    try:
        with create_context() as ctx:
            possible_exception()
            return
    except Exception:
        reveal_type(ctx)  #  information: Type of "ctx" is "None"
```

**Expected behavior**

Type of `ctx` expected to be `Optional[str]`

**VS Code extension or command-line**
pyright 1.1.224

**Additional context**
A similar problem has already been fixed in #2648. But this case is more complicated because of `return`.

**Comment by erictraut** [comment] 2022-02-24 19:02
Thanks for the bug report. This will be fixed in the next release.

**Comment by erictraut** [comment] 2022-02-26 08:38
I am going to need to revert this change because it causes a regression. The real fix here is much more complex and will require additional thought to get right.

**Comment by erictraut** [comment] 2022-02-26 22:13
This will be fixed in the next release. For real this time. :)

**Closed** 2022-03-02 07:06 UTC
Labels: bug, addressed in next version
