### ISSUE TITLE
Conditional bases not inherited properly

### ISSUE THREAD

**Issue by Gobot1234** [microsoft/pyright#5554] opened 2023-07-21 11:20 UTC
**Describe the bug**
I have a admittedly a weird setup with a class that has conditional bases in its super class. The class (`WrapsUser`) is used to make what would be a virtual (ABC) subclass (`Friend` and other classses) at type time (not useful) into a concrete subclass at type time (much more useful) for memory saving purposes.

**To Reproduce**
I can't seem to get a minimal repro because as soon as I paste the somewhat reduced definitions outside of the library it seems to work. I also don't think this is a cache issue like some other unknown member bugs are because they do not go away if you restart the LSP.

1. `git clone https://github.com/Gobot1234/steam.py`
2. Run `poetry install`
3. Open `steam/friend.py`
4. Hover over the errors, they are all of the same type, pylance is able to resolve the correct definitions but pyright reports them as unknown

**Expected behavior**
No errors to be produced.

**Code or Screenshots**
friend.py:
<img width="777" alt="image" src="https://github.com/microsoft/pyright/assets/50501825/c5ae8204-d592-4a4b-b925-c3c7b0d49f41">.
<img width="580" alt="image" src="https://github.com/microsoft/pyright/assets/50501825/d2781d40-9422-42a7-8b74-f65c0e467b64">
state.py:
<img width="941" alt="image" src="https://github.com/microsoft/pyright/assets/50501825/295dd3cc-6fd8-4ffe-aec4-8fc99d4cf326">
All of these I think stem from the same base (🥁) issue

**VS Code extension or command-line**
pylance: v2023.7.31

**Comment by erictraut** [comment] 2023-07-21 14:55
The issue is related to a circular dependency that pyright is not currently able to resolve.

When pyright evaluates the type of class `User`, it needs to first evaluate the type of the base class `Messageable[UserMessage]`, which requires it to evaluate the type of `UserMessage`. That requires it to first evaluate the type of `UserMessageAuthorT`, which has a default that references the class `Friend`. The class `Friend` has a base class of `WrapsUser` which has a base class of `User`, and we're back to the start.

I have some logic in place to handle certain types of circular dependencies like this, but it's being defeated in this case. The result is that the mro for some of the classes in the cycle is corrupted, and subsequent lookups for methods fail.

I'll look for ways to improve the robustness of the circular dependency handling.

**Comment by erictraut** [comment] 2023-07-21 17:54
I've found a way to handle this case. This will be included in the next release.

**Comment by erictraut** [comment] 2023-07-21 19:38
The circularity resulted in errors some of the time but not others. It depended on the starting point in the cycle — i.e. which of the classes was evaluated first. The order of evaluation is often different between pylance and pyright because pylance includes a semantic token provider, and that evaluates all of the identifiers within a file prior to type checking. In theory, the results should always be the same regardless of evaluation order, but bugs can result in different behaviors.

**Comment by erictraut** [comment] 2023-07-26 03:09
This is addressed in pyright 1.1.319, which I just published. It will also be included in a future release of pylance.

**Closed by erictraut** 2023-07-26 03:09 UTC
Labels: bug, addressed in next version
