### ISSUE TITLE
Possible Metaclass Type Guard Regression in 1.1.380 

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#8988] opened 2024-09-13 19:56 UTC
I previously had a code example that took the form of something like this:

```python

class MyClassMeta(type): ...

class MyClass(metaclass=MyClassMeta): ...

type MyType = str | int |  MyClass | type[MyClass]

def _foo(arg: str | int) -> None: ...

def foo(arg: MyType) -> None:
    casted = "foo" if isinstance(arg, MyClass | MyClassMeta) else arg
    return _foo(casted)
```

Previously `casted` would narrow to `str | int` as including `MyClassMeta` in the guard would have Pyright concluding that casted would end up as "foo" if it were a `MyClass` type. However, this example fails as of 1.1.380. Perhaps there's something I'm missing, but this seems to be a regression to me.

[Pyright Playground
](https://pyright-play.net/?pyrightVersion=1.1.380&pythonVersion=3.14&strict=true&code=FAYwNghgzlAECyBPAwpG8CmAXCAKLiADhgJQBcsAdNcKGnEqtFLgLbYTjMC8j9mOclRrACxBIgAqRDLG6woWAE6wAPrACWAOyxrYEpjD1iMAbT7MAurQAmGAGawA%2BvYD2r3BCUBzCopXq2lgksAC0AHywAHKuWhgU1JS2DrBuHl6%2BEtLEIRHRsfHA%2Bvog0FgYNnKwAERp1ZqOGlDaihBaIBiePgA0BvR6FugcIRhgULIZRcVK2ACuSlrOabilihUkwEA)

**Comment by erictraut** [comment] 2024-09-13 20:14
Thanks for reporting it. I think this is the same issue as #8963, but I'll confirm once I investigate further.

**Comment by erictraut** [comment] 2024-09-14 00:02
I confirmed this is a duplicate of #8963, which I've fixed in pyright's main branch. It will be addressed in the next release.

**Closed** 2024-09-14 00:02 UTC
Labels: bug, addressed in next version

**Comment by Abderrahma77524** [comment] 2024-09-14 12:45
# update ()
import typing

UnionClass = typing.Union['Foo', 'Bar']


class Foo:
    def __init__(self, parent: UnionClass | None):
        self.parent = parent
        self.UnionClass = UnionClass

class Bar:
    def __init__(self, parent: UnionClass | None):
        self.parent = parent
        self.UnionClass = UnionClass

class Outer:
    def __init__(self, a):
        self.a = a

    def jls_extract_def(self):
        # Error here
        return

    def pump(self):
        while self.a:
            self.a = self.a.parent  # Error here = self.jls_extract_def()


‫في السبت، 14 سبتمبر 2024 في 1:03 ص تمت كتابة ما يلي بواسطة ‪Eric Traut‬‏ <‪
***@***.***‬‏>:‬
