### ISSUE TITLE
separate X.pyi file does not get imported besides X.py

### ISSUE THREAD

**Issue by B4rtware** [microsoft/pyright#588] opened 2020-03-26 02:58 UTC
**Describe the bug**
`X.py` file does not get `X.pyi` typings with the same file name.

```
.\utils\server.py   
 Imports     2 files
 Imported by 1 file 

.\typings\utils\server.pyi
 Imports     2 files
 Imported by 0 files

.\main.py
 Imports     3 files
 Imported by 0 files

2 files not explicitly imported
    C:\Users\XXX\Desktop\Test\typings\utils\server.pyi
    C:\Users\XXX\Desktop\Test\main.py
```

**To Reproduce**
- utils/server.py
```
def start_server():
    return 0
```
- typings/utils/server.pyi
```
def start_server() -> str: ...
```
after that inside the main hover over `start_server()`
- main.py
```
from utils.server import start_server
start_server() <-+
                 |
+-------------------------------------------+
| (function) start_server: () -> Literal[0] |
+-------------------------------------------+
```
After renaming `server.py` the `.pyi` file is used.
- main.py
```
from utils.server import start_server
start_server() <-+
                 |
+------------------------------------+
| (function) start_server: () -> str |
+------------------------------------+
```
```
...
.\typings\utils\server.pyi
 Imports     2 files
 Imported by 1 file

.\main.py
 Imports     3 files
 Imported by 0 files

2 files not explicitly imported
    C:\Users\XXX\Desktop\Test\utils\_server.py
    C:\Users\XXX\Desktop\Test\main.py
```
**Expected behavior**
```
.\utils\server.py   
 Imports     2 files
 Imported by 1 file 

.\typings\utils\server.pyi
 Imports     2 files
 Imported by 1 files

.\main.py
 Imports     3 files
 Imported by 0 files

1 file not explicitly imported
    C:\Users\XXX\Desktop\Test\main.py
```
I have read [importance-of-type-stub-files](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md#importance-of-type-stub-files) and according to what I understand is that both `server.py` and `server.pyi` should be imported. While `pyi` should have a higher priority. 

**VS Code extension or command-line**
VS Code: 1.1.29

**Additional context**
I would need this behavior because I generate source code without any kind of typing. If the code changes except the interface I would need to put the typing code there in again. So I was thinking about having a separate `pyi` file.

**Comment by erictraut** [comment] 2020-03-26 04:59
The "typings" directory was designed for type stub files corresponding to external (third-party) imports. It sounds like you want to create type stubs for files that correspond to source files within your workspace. That's a use case I hadn't considered when I wrote the code.

Currently, pyright resolves imports in this order:
1. Root directory of execution environment
2. Any extra paths defined in your execution environment
3. Typings directory
4. Typeshed directory
5. Python search paths (as defined by the configured python interpreter)

To accommodate your scenario, I'd need to move #3 up above #1. I'm a bit uncomfortable making that change because it could have undesirable side effects.

@jakebailey @huguesv I'd appreciate any thoughts you have here.

**Comment by B4rtware** [comment] 2020-03-26 12:58
Alright thanks for your super fast response :) I can understand if you don't want to change that. Maybe I miss interpreted the sentence from the section I have referenced.

Right now I have found a reasonable workaround which I would use if it stays at it is.
I can put my typings at the bottom of the generated file. Which will override the typings and I have a working intellisense. This can be done by a script which will copy it at the bottom.

**Comment by jakebailey** [comment] 2020-03-26 17:09
I think the more common thing to do here is to not put these files into "typings", but place them as files next to the actual code, e.g. have `utils/server.py` and `utils/server.pyi`. Many libraries ship this way (pytorch is my immediate example). I don't think this would interfere with the ordering you've described, as it'd likely then be in group 1.

However in pyright, without merging/mapping and generally the idea that a module can have both code and a stub, I'm not sure how you'll achieve the same thing in user-editable code. In MPLS we're able to augment the Python code with the information from the stub and provide type info when editing the `py` based on the contents of `pyi` such that someone writing both can edit either and it works.

I had actually assumed a while back this was something pyright already covered, but now that I know more about import resolution only ever getting one result (I found module X and it's a stub, I found module Y and it's a regular file, etc) versus distinct resolutions, my assumption was likely wrong.

**Comment by erictraut** [comment] 2020-03-26 17:32
Yes, good point Jake. @B4rtware, if you place the ".pyi" files next to the corresponding ".py" files (i.e. within the same directory), pyright will prefer the ".pyi" files when resolving imports.

I should have thought of that because we use that technique internally for some of our auto-generated files. We auto-generate both the ".py" and ".pyi" files and check them in side by side.

Jake is also correct that pyright won't load _both_ the ".pyi" _and_ ".py" files and attempt to merge their contents. That would result in behaviors that are difficult to understand and debug (at best) or even non-deterministic (at worst).

**Closed** 2020-03-26 17:32 UTC
Labels: as designed

**Comment by jakebailey** [comment] 2020-03-26 17:35
> Jake is also correct that pyright won't load both the ".pyi" and ".py" files and attempt to merge their contents. That would result in behaviors that are difficult to understand and debug (at best) or even non-deterministic (at worst).

Note that I don't know how the editor experience is going to be without this... Will this break if the `py` file is edited? Do you get no info at all given it thinks the module is somewhere else? Again, haven't tested, but I think it's important for people who want to maintain this split.

**Comment by B4rtware** [comment] 2020-03-27 00:44
Placing the `pyi` inside the source folder works like a charm, thanks. I can also currently see no issues with the editor. I will stick to this method :)
