### ISSUE TITLE
The extension doesn't work with 'Create: New File'

### ISSUE THREAD

**Issue by FaresAhmedb** [microsoft/pyright#2181] opened 2021-08-12 12:52 UTC
**Describe the bug**
Pyright doesn't work at all when using `Create: New File` and choosing Python as the language for the file.

**To Reproduce**
1. Press <kbd>Ctrl</kbd>+<kbd>n</kbd> on the keyboard (The shortcut for `File > New File`).
2. Select Python as the language for the file.
3. Start typing some Python code.
4. Pyright is not working.

**VS Code extension or command-line**
VSCode Version 1.59.0 (Latest). Pyright Version 1.1.161 (Latest)

**Comment by erictraut** [comment] 2021-08-12 15:20
If the pyright extension has been loaded and initialized, the above steps work as expected. The problem is that VS Code doesn't load or initialize the pyright extension until you either 1) open a file with a ".py" or ".pyi" extension or 2) there is a "pyrightconfig.json" file in the root of your workspace directory. So this is a limitation of VS Code, and I don't think there's anything the pyright extension can do to change this behavior. If you would like, you could file a bug report or feature request in the [VS Code repo](https://github.com/microsoft/vscode).

**Comment by FaresAhmedb** [comment] 2021-08-12 15:58
Hi @erictraut!

The [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) extension is able to work when using `Create: New File` just fine so I don't get how can this be a problem in VSCode's end. Can you correct me?

P.S. Thanks for the fast reply. Awesome!

**Comment by erictraut** [comment] 2021-08-12 16:02
Pylance is different in that it's an extension to the core "Python" extension; it cannot run on its own, and VS Code doesn't load or initialize it directly. The Python extension loads it. Even in that case, however, the Python extension needs to be loaded by VS Code, and that doesn't happen until you open a ".py" or ".pyi" file.

Out of curiosity, why are you using the pyright VS Code extension? We recommend using pylance if you're a VS Code user. Pylance incorporates a bunch of useful language server features on top of pyright's core type checking functionality.

**Comment by erictraut** [comment] 2021-08-12 16:06
> and that doesn't happen until you open a ".py" or ".pyi" file.

I take that back. Upon more experimentation, it looks like the Python extension is loaded and initialized without opening a ".py" or ".pyi" file. It must be configured to always load. @jakebaily might be able to confirm.

In any case, I don't think it's appropriate for pyright to always load. In general, language server extensions should be loaded only when VS Code decides that they should be loaded. If you want to always load it within a given project, you can add a pyrightconfig.json file.

**Comment by jakebailey** [comment] 2021-08-12 16:27
Actually, I think this is because the client mandates the `file` scheme here: https://github.com/microsoft/pyright/blob/abd41b7273f19cd657db7768821b0e1e84c6d217/packages/vscode-pyright/src/extension.ts#L87

Untitled files have URIs that look like `untitled:Untitled-1`, not `file:///foo/bar/baz`. The extension already correctly activates on Python code (regardless of extension) thanks to:

https://github.com/microsoft/pyright/blob/abd41b7273f19cd657db7768821b0e1e84c6d217/packages/vscode-pyright/package.json#L26

If you remove the `scheme` from the document selector, it should get the right files.

(The core extension does https://github.com/microsoft/vscode-python/blob/3698950c97982f31bb9dbfc19c4cd8308acda284/src/client/common/constants.ts#L8, but there are some other schemes too, so IMO just saying "give me all python" is correct.)

**Comment by erictraut** [comment] 2021-08-12 16:35
Oh, interesting. I didn't know about that.

If I remove the 'file' scheme, it does launch the pyright extension. But it appears that pyright isn't properly reporting diagnostics when using non-file schemas. It's converting everything back to a "file" URI in this case.

**Comment by jakebailey** [comment] 2021-08-12 16:40
Yeah, that's a known issue already thanks to the fact that we don't use URIs everywhere (assuming that everything has a real on-disk path, converting to filenames immediately). That's why we had to add something to fix up schemes for the browser case (for now), with the intent that to make the real fix of using URIs throughout (like other language servers).

**Comment by FaresAhmedb** [comment] 2021-08-12 16:45
Hi again @erictraut!

> Out of curiosity, why are you using the pyright VS Code extension?

Pylance/Python doesn't highlight type checking errors as far as I know (at least out of the box) however Pyright does.

> We recommend using pylance if you're a VS Code user.

I actually read that and tried googling how to enable type checking for the Pylance/Python extension but no luck [this issue](https://github.com/microsoft/vscode-python/issues/2250) is the only thing I came up with so I decided just to use Pyright.

**Comment by jakebailey** [comment] 2021-08-12 16:51
> Pylance/Python doesn't highlight type checking errors as far as I know (at least out of the box) however Pyright does.

It does, you just have to set `python.analysis.typeCheckingMode` (which has a different default there), or in a `pyrightconfig.json`.

**Comment by erictraut** [comment] 2021-08-12 16:59
Ah, that's good to know. We probably need to do more to improve the discoverability of type checking in pylance. FYI: @savannahostrowski

**Comment by erictraut** [comment] 2021-08-12 17:07
I've fixed the registration code as Jake suggested, removing the "file" scheme requirement. I've filed a separate bug https://github.com/microsoft/pyright/issues/2182 to track the other (larger) change that needs to be done to support non-file URIs throughout pyright.

**Comment by savannahostrowski** [comment] 2021-08-12 17:32
> Ah, that's good to know. We probably need to do more to improve the discoverability of type checking in pylance. FYI: @savannahostrowski

Already in progress!

**Comment by erictraut** [comment] 2021-08-13 21:54
This is addressed in pyright 1.1.162, which I just published. It will also be in the next release of pylance.

**Closed by erictraut** 2021-08-13 21:54 UTC
Labels: enhancement request, addressed in next version
