### ISSUE TITLE
internal error in pyright-python/1.1.309

### ISSUE THREAD

**Issue by luochen1990** [microsoft/pyright#5140] opened 2023-05-19 11:15 UTC
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

If you have a question about typing or a behavior that you’re seeing in Pyright (as opposed to a bug report or enhancement request), consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Describe the bug**

```
Error: Debug Failure. False expression.
at a.lock (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeVarContext.ts:372:9)
at validateFunctionArgumentTypes (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10449:28)
at validateFunctionArgumentTypesWithContext (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
at validateFunctionArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at s.validateCallArguments [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateNewMethod (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:317:19)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
at s.useSpeculativeMode [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateConstructorArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at validateCallArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at getTypeOfCall (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
at getTypeOfExpression (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
at validateArgType (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10996:40)
at forEach (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10460:31)
at Array.forEach (<anonymous>)
at validateFunctionArgumentTypes (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10459:32)
at validateFunctionArgumentTypesWithContext (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10319:16)
at validateFunctionArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at s.validateCallArguments [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:299:26)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19126:28)
at s.useSpeculativeMode [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateNewMethod (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:298:34)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
at s.useSpeculativeMode [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateConstructorArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at validateCallArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at getTypeOfCall (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
at getTypeOfExpression (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
at inferLambdaReturnType (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:12996:38)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:13015:17)
at useSpeculativeMode (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
at getTypeOfLambda (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:13012:9)
at getTypeOfExpression (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:1043:30)
at evaluateTypesForExpressionInContext (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18133:21)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:795:13)
at evaluateTypeForSubnode (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:794:16)
at s.getTypeResult (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at L.visitReturn (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/checker.ts:908:48)
Error performing analysis: Error: Debug Failure. False expression.
at a.lock (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeVarContext.ts:372:9)
at validateFunctionArgumentTypes (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10449:28)
at validateFunctionArgumentTypesWithContext (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
at validateFunctionArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at s.validateCallArguments [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateNewMethod (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:317:19)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
at s.useSpeculativeMode [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateConstructorArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at validateCallArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at getTypeOfCall (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
at getTypeOfExpression (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
at validateArgType (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10996:40)
at forEach (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10460:31)
at Array.forEach (<anonymous>)
at validateFunctionArgumentTypes (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10459:32)
at validateFunctionArgumentTypesWithContext (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10319:16)
at validateFunctionArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at s.validateCallArguments [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:299:26)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19126:28)
at s.useSpeculativeMode [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateNewMethod (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:298:34)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
at s.useSpeculativeMode [as timeOperation] (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at validateConstructorArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
at doForEachSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
at expandSubtype (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
at mapSubtypesExpandTypeVars (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
at validateCallArguments (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
at getTypeOfCall (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
at getTypeOfExpression (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
at inferLambdaReturnType (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:12996:38)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:13015:17)
at useSpeculativeMode (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
at getTypeOfLambda (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:13012:9)
at getTypeOfExpression (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:1043:30)
at evaluateTypesForExpressionInContext (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18133:21)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:795:13)
at evaluateTypeForSubnode (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
at callback (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:794:16)
at s.getTypeResult (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
at L.visitReturn (/home/lc/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/checker.ts:908:48)
```

**VS Code extension or command-line**
Are you running pyright as a VS Code extension or a command-line tool? Which version? You can find the version of the VS Code extension by clicking on the Pyright icon in the extensions panel.

No, I'm using `pyright` in the command line directly.

**Additional context**

My config about `pyright` in `pyproject.toml`:

```
[tool.pyright]
include = ["src", "example"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
#ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
#stubPath = "src/stubs"
venvPath = ".venv-py38"

useLibraryCodeForTypes = true
reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.8"
pythonPlatform = "Linux"
```

**Comment by erictraut** [comment] 2023-05-19 14:59
Thanks for the bug report. This is a duplicate of https://github.com/microsoft/pyright/issues/5129, which has already been fixed and will be addressed in the next release.

**Comment by erictraut** [comment] 2023-05-21 21:28
Closing because this is a duplicate.

**Closed by erictraut** 2023-05-21 21:28 UTC
Labels: bug, addressed in next version
