### ISSUE TITLE
Argument of type "bool" cannot be assigned to parameter "x" of type "Literal[True]"

### ISSUE THREAD

**Issue by owocado** [microsoft/pyright#9149] opened 2024-10-04 18:01 UTC
**Describe the bug**
Similar to #2867 and #2796 though my use case involves `typing.Literal` and `typing.overload`

Why pyright cannot infer `Literal[True]` as valid `bool` type? Is the reason still same as outlined in the comments of linked issues?

**Code or Screenshots**

```python
from typing import Literal, overload

@overload
def foo(x: str, *, with_counts: Literal[False]) -> None:
    ...

@overload
def foo(x: str, *, with_counts: Literal[True]) -> bool:
    ...

def foo(x: str, *, with_counts: bool = False) -> bool | None:
    if with_counts:
        return True
    return None

def bar(_id: int, *, with_counts: bool = True):
    ret = foo('1', with_counts=with_counts) # raises error here
    return ret
```
![image](https://github.com/user-attachments/assets/742a7880-2d49-4d44-9bfd-7d954329e891)

Though, I ran into this error while I was doing stuff on my fork of discord.py
https://github.com/owocado/discord.py/blob/main/discord/interactions.py#L769-L848
and `@overload` is defined at https://github.com/owocado/discord.py/blob/main/discord/webhook/async_.py#L431-L469

![image](https://github.com/user-attachments/assets/87bf6f9b-c35c-496f-961a-c00a37de8330)

**VS Code extension or command-line**
VS Code: 1.94.0 with pyright extension v1.1.383
```
Version: 1.94.0
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.11.1-arch1-1
```

**Comment by erictraut** [comment] 2024-10-04 19:06
Please refer to the documentation for pyright's [handling of overloads](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=overloads). 

The behavior for overload resolution isn't currently specified in the Python typing spec, so there are minor variations across type checkers. However, pyright's behavior in this case matches that of mypy's. 

I recently submitted a [proposed update to the Python typing spec](https://discuss.python.org/t/draft-typing-spec-chapter-for-overloads/60788) that defines the standard behaviors for overload resolution. If this proposal is adopted in its current draft form, it will require that type checkers expand `bool` into `Literal[True] | Literal[False]` for purposes of overload matching. That is, your code sample would then work without any type errors.

I don't plan to make modifications to pyright's overload resolution behavior until the new specification has been accepted. Making changes now will create unnecessary churn, and they may need to be undone if the draft spec is modified.

I'm going to close the issue because pyright is working as intended currently, but the behavior may change to accommodate your use case in the future.

In the meantime, you can work around this limitation by providing a third overload that accepts a `bool` and produces a return result of `bool | None`.

**Closed by erictraut** 2024-10-04 19:06 UTC
Labels: bug

**Comment by anentropic** [comment] 2024-10-07 13:40
>  If this proposal is adopted in its current draft form, it will require that type checkers expand bool into Literal[True] | Literal[False] for purposes of overload matching

just to add that currently it seems as if the reverse happens...

I ran into the same case as the OP today

I thought I might be able to work around it by annotating the arg in the caller function as `Literal[True] | Literal[False]` instead of `bool`, but hovering over that in VS Code just shows `bool` - so it's been substituted in the opposite direction

this seems slightly inconsistent - on one hand it's saying these two types are identical, on the other that they are not
