### ISSUE TITLE
crash: --verifytypes causes "Cannot read properties of undefined (reading 'startsWith')"

### ISSUE THREAD

**Issue by bukzor-sentryio** [microsoft/pyright#6748] opened 2023-12-15 18:23 UTC
Minimal reproduction:

```
$ pyright --version
pyright 1.1.340

$ mkdir ~/tmp/pyright-verifytypes-broken
$ cd ~/tmp/pyright-verifytypes-broken
$ mkdir -p src/lib
$ touch src/lib/py.typed
$ echo 'x = 1' > src/lib/x.py
$ touch src/lib/__init__.py
$ pyright --verifytypes $PWD/src/lib
Module name: "~/tmp/pyright-verifytypes-broken/src/lib"
Package directory: "file:///tmp/pyright-verifytypes-broken/src/lib"
Module directory: "file:///tmp/pyright-verifytypes-broken/src/lib"
Path of py.typed file: "file:///tmp/pyright-verifytypes-broken/src/lib/py.typed"

Public modules: 2
   /tmp/pyright-verifytypes-broken/src/lib
   /tmp/pyright-verifytypes-broken/src/lib.x
   error: An internal error occurred while verifying types: "TypeError: Cannot read properties of undefined (reading 'startsWith')
      at Object.file (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/common/uri/uri.ts:167:33)
      at forEach (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/packageTypeVerifier.ts:592:38)
      at Map.forEach (<anonymous>)
      at b._getTypeKnownStatusForSymbolTable (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/packageTypeVerifier.ts:515:21)
      at b._verifyTypesOfModule (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/packageTypeVerifier.ts:398:22)
      at forEach (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/packageTypeVerifier.ts:185:30)
      at Array.forEach (<anonymous>)
      at b.verify (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/analyzer/packageTypeVerifier.ts:184:35)
      at verifyPackageTypes (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/pyright.ts:493:33)
      at processArgs (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/pyright.ts:370:16)
      at main (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright-internal/src/pyright.ts:970:28)
      at Object.call (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright/src/pyright.ts:3:1)
      at __webpack_require__ (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/webpack/bootstrap:19:32)
      at fn (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/webpack/bootstrap:35:79)
      at Function.O (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/webpack/runtime/chunk loaded:23:12)
      at next (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/webpack/bootstrap:36:44)
      at Function.x (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/webpack/runtime/startup chunk dependencies:5:9)
      at /.vim/data/mason/packages/pyright/node_modules/pyright/dist/webpack/startup:2:47
      at Object.<anonymous> (/.vim/data/mason/packages/pyright/node_modules/pyright/dist/pyright.js:1:2038)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Function.Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1143:19)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> (/.vim/data/mason/packages/pyright/node_modules/pyright/index.js:8:1)
      at Module._compile (node:internal/modules/cjs/loader:1256:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
      at Module.load (node:internal/modules/cjs/loader:1119:32)
      at Function.Module._load (node:internal/modules/cjs/loader:960:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
      at node:internal/main/run_main_module:23:47"

Symbols used in public interface:

Symbols exported by "/tmp/pyright-verifytypes-broken/src/lib": 0
  With known type: 0
  With ambiguous type: 0
  With unknown type: 0
  Functions without docstring: 0
  Functions without default param: 0
  Classes without docstring: 0

Other symbols referenced but not exported by "/tmp/pyright-verifytypes-broken/src/lib": 0
  With known type: 0
  With ambiguous type: 0
  With unknown type: 0

Type completeness score: 0%

Completed in 0.644sec
```

**Comment by erictraut** [comment] 2023-12-15 18:25
Thanks for reporting. This is a duplicate of https://github.com/microsoft/pyright/issues/6722, which has already been fixed in the main branch.

**Closed by erictraut** 2023-12-15 18:25 UTC
Labels: bug
