### ISSUE TITLE
Cache return types of functions to make pyright faster

### ISSUE THREAD

**Issue by collinanderson** [microsoft/pyright#3269] opened 2022-03-29 17:21 UTC
**Is your feature request related to a problem? Please describe.**
I noticed if I have a function that gets used many times, and it's not annotated with a return type, then pyright ends up being slow. If I annotate the function with a return type then it's much faster. I assume this is because pyright re-computes the return type for a function every time it gets called.

**Describe the solution you'd like**
Ideally pyright should compute the return type for a function only once, and then used the cached value whenever the function gets called, instead of re-computing the return type every time.

If nothing else, it would be nice if there was a way pyright would warn about functions getting called without return value annotation. (I assume that happens in strict mode but I'm not there yet.)

**Additional context**
Example:

```
def my_big_function(args):
    # lots of stuff
    return eventual_obj

def using_my_big_function():
    print(my_big_function(123).data)
    print(my_big_function(234).data)  # return type of my_big_function gets recomputed
    print(my_big_function(345).data)  # return type of my_big_function gets recomputed
    print(my_big_function(456).data)  # return type of my_big_function gets recomputed
```

If I add a return annotation, typechecking goes much faster.
```
def my_big_function(args) -> ReturnType:
    # lots of stuff
    return eventual_obj

```

**Comment by erictraut** [comment] 2022-03-29 17:26
Pyright aggressively caches type information when it can. There are times when it needs to speculatively evaluate types (e.g. when evaluating overloads) and needs to reevaluate because of this, but that's a relatively rare edge case.

I've made some big performance improvements in the past few days that improve type analysis of complex functions. I'll be publishing a new version of pyright within the next 12 hours or so. Let's see if that improves what you're seeing.

If you'd like me to investigate the particular case that you're seeing, I'll need significantly more detail — preferably a repro case. Is the code in a public repo? If not, could you extract the function(s) involved and create a small sample repo on github that I have access to?

**Comment by erictraut** [comment] 2022-03-29 17:29
Also, when you say that the function is unannotated, are you referring only to the return type? Or are you also referring to the input parameters? If it's just the return type annotation that's omitted, pyright will evaluate the return type once based on the annotated input parameter types. If the input parameter types are also omitted, pyright will attempt to use a technique that I call "[call-site return type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#call-site-return-type-inference)". This is more expensive because it needs to evaluate the return type once for each combination of argument types. But in your example above, you're calling `my_big_function` with the same argument type (`int`), so that return type will be cached.

**Comment by collinanderson** [comment] 2022-03-29 18:02
Here's a little bit more of what i'm doing, with the the actual function definition, so no input param annotations, and I am sometimes calling it with the `json` argument, sometimes not, so more complicated than the original example. I'm also on 1.1.232 because #3261, so I'll try again on the next release.

```
MyReturnClass(OrigReturnClass):
    data: 'list | dict | None'

def req(method, path, headers=None, form_data=None, json=None, body=None, eta=4, verbose=settings.DEBUG, **kwargs):
    # ...
    resp = orig_func(...)  # returns OrigReturnClass()
    resp.__class__ = MyReturnClass
    assert isinstance(resp, MyReturnClass)
    resp.data = mydata
    return resp
```

And then I have a lot of  `req(...).data` calls.

If I add `-> MyReturnClass` to the function it's way faster.

Again, I'll try again with the next release.

**Comment by erictraut** [comment] 2022-03-29 18:37
It sounds like pyright is using call-site return type inference, and you're calling the function with different argument types in different call sites, so that forces it to reevaluate the return type once for each combination of argument types.

I'm cautiously optimistic that the next version will address the issue you're seeing.

**Comment by erictraut** [comment] 2022-03-29 19:49
I'm going to close this as "as designed".

If it's still slow after the next release and you are able to provide me with a detailed repro, I'm happy to take a look at it.

**Closed by erictraut** 2022-03-29 19:49 UTC
Labels: as designed

**Comment by collinanderson** [comment] 2022-03-30 13:48
I'm not able to reproduce the issue on 1.1.234 so I think it's fixed. Thanks.
