### ISSUE TITLE
Type Comment Support

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#7164] opened 2024-01-30 15:30 UTC
**Describe the bug**
PEP 484 on typing (https://peps.python.org/pep-0484/#type-comments) indicates that type comments are allowed.  Code below works with `mypy`, but not with `pyright`

**Code or Screenshots**

```python
from typing import Literal, get_args

FooBarType = Literal["foo", "bar"]
for key in get_args(FooBarType):  # type: FooBarType
    reveal_type(key)
    print(key)

```

Pyright reports:
```text
  typecomment.py:4:43 - error: Type annotation not supported for this statement (reportInvalidTypeForm)
  typecomment.py:5:17 - information: Type of "key" is "Any"
```
mypy 1.8.0  reports:
```text
typecomment.py:5: note: Revealed type is "Union[Literal['foo'], Literal['bar']]"
```

**VS Code extension or command-line**
pyright 1.1.349 command line

**Comment by erictraut** [comment] 2024-01-30 17:03
This is a duplicate of https://github.com/microsoft/pyright/issues/1650. It's also addressed in the pyright documentation [here](https://microsoft.github.io/pyright/#/mypy-comparison?id=support-for-type-comments).

Type comments were required back when PEP 484 was created because there was no support for variable annotations. [PEP 526](https://peps.python.org/pep-0526/) (which was introduced back in Python 3.6) changed that, effectively making type comments no longer necessary. 

Pyright provides minimal type comment support only in places where type annotations are supported, but we intentionally do not support type comments in places where a PEP 526 annotation is not supported, such as in a `for` statement. We have no plans to add more support for type comments.

The [latest version of the typing spec](https://typing.readthedocs.io/en/latest/spec/historical.html#type-comments) retains mention of typing comments in the "Historical and deprecated features" section. It's likely that type comments will be completely deprecated and removed in future versions of the typing spec. If you are still using them, you should move away from them. If you enable the `reportTypeCommentUsage` check in pyright, it will flag all type comment usage as errors so you can replace them in your code.

The way to declare the type of `key` in your code sample above is:

```python
from typing import Literal, get_args

FooBarType = Literal["foo", "bar"]
key: FooBarType
for key in get_args(FooBarType):
    reveal_type(key)
    print(key)
```

**Closed by erictraut** 2024-01-30 17:03 UTC
Labels: bug
