### ISSUE TITLE
Parameter "**kwargs" has no corresponding parameter

### ISSUE THREAD

**Issue by lexicalunit** [microsoft/pyright#3581] opened 2022-06-16 17:49 UTC
**Describe the bug**
Coming from the discussions here: https://github.com/microsoft/pyright/issues/3559#issuecomment-1157930375

I was getting the error:
```
(function) inner: (n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T@make_n]
Expression of type "(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T@make_n]" cannot be assigned to return type "BulkFactory[T@make_n]"
  Type "(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T@make_n]" cannot be assigned to type "(n: int, /, *args: Any, **kwargs: Any) -> List[T@make_n]"
    Parameter "**kwargs" has no corresponding parameter
```
On the return statement in a function returning an inner function.

**To Reproduce**
```python
from __future__ import annotations

from typing import Any, Callable, Generic, List, Optional, Protocol, TypeVar

from typing_extensions import ParamSpec, TypeAlias


def i_default() -> int:
    return 4


def s_default() -> str:
    return "foo"


class Company:
    id: int

    def __init__(
        self,
        id: Optional[int] = None,
        # ... dozens more optional properties go here
    ):
        self.id = id or i_default()  # each property has its own default
        print(self)

    def __repr__(self) -> str:
        return f"<company {self.id}>"


class User:
    id: int

    def __init__(
        self,
        uuid: Optional[str] = None,
        # ... dozens more optional properties go here
    ):
        self.uuid = uuid or s_default()  # each property has its own default
        print(self)

    def __repr__(self) -> str:
        return f"<user {self.uuid}>"


def make_company(*args: Any, **kwargs: Any) -> Company:
    return Company(*args, **kwargs)


def make_user(*args: Any, **kwargs: Any) -> User:
    return User(*args, **kwargs)


T = TypeVar("T")
P = ParamSpec("P")


class BulkFactory(Protocol, Generic[T]):
    def __call__(
        self,
        n: int,
        /,
        *args: Any,
        **kwargs: Any,
    ) -> List[T]:
        ...


def make_n(maker: Callable[P, T]) -> BulkFactory[T]:
    def inner(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T]:
        return [maker(*args, **kwargs) for _ in range(n)]

    return inner  # pylance error here
```

**Expected behavior**
The error given here doesn't make much sense. I _think_ the error stems from the mismatch of `Any` to `P.args`/`P.kwargs`. I'm not sure if this should _just work_ or if there should be a more descriptive error here.

**VS Code extension or command-line**
- Are you running pyright as a VS Code extension or a command-line tool? Both
- Which version? `pyright 1.1.253` and `pylance v2022.6.10`
- Error is seen when using `python 3.8`

**Additional context**
I was able to workaround the error using this code:
```python
T = TypeVar("T")
P = ParamSpec("P")


class BulkFactory(Protocol, Generic[T, P]):
    def __call__(
        self,
        n: int,
        /,
        *args: P.args,
        **kwargs: P.kwargs,
    ) -> List[T]:
        ...


def make_n(maker: Callable[P, T]) -> BulkFactory[T, P]:
    def inner(n: int, /, *args: P.args, **kwargs: P.kwargs) -> List[T]:
        return [maker(*args, **kwargs) for _ in range(n)]

    return inner
```

**Comment by erictraut** [comment] 2022-06-16 23:22
Thanks for the bug report. This will be addressed in the next release.

**Comment by erictraut** [comment] 2022-06-20 08:19
This is included in pyright 1.1.255, which I just published. It will also be included in the next release of pylance.

**Closed by erictraut** 2022-06-20 08:19 UTC
Labels: bug, addressed in next version

**Comment by tjdcs** [comment] 2023-06-27 06:13
This appears to have been re-introduced in when updating pyright from 1.1.311 -> 1.1.316

```python
#definition
def plot_single_function(
    function: Callable,
    samples: ArrayLike | None = None,
    log_x: int | None = None,
    log_y: int | None = None,
    plot_kwargs: dict | List[dict] | None = None,
    **kwargs: Any,
) -> Tuple[plt.Figure, plt.Axes]: ...
```

```python
#usage
plot_single_function(
    lambda x: (  # noqa: ARG005
        1
        / colour.contrast.contrast_sensitivity_function_Barten1999(
            u=u, sigma=sigma, E=E, X_0=X_0, Y_0=Y_0, **settings_BT2246
        )
        * 2
        * (1 / 1.27)
    ),
    samples=L,
    log_x=10,
    **{
        "title": "Examples of HVS Minimum Detectable Contrast Characteristics",
        "x_label": "Luminance ($cd/m^2$)",
        "y_label": "Minimum Detectable Contrast",
        "axes.grid.which": "both",
    }
)
```

In this example we are iterating a `dict` literal to pass arguments into kwags, which is then forwarded to various other plotting functions.

**Comment by debonte** [comment] 2023-06-27 15:51
@tjdcs, this change in behavior was by design. See Eric's comment [here](https://github.com/microsoft/pyright/issues/5351#issuecomment-1601094654) for an explanation and workarounds.

For what it's worth, what you are describing is different than this issue. The original poster's code above is still diagnostic-free on 1.1.316.
