### ISSUE TITLE
Pylance does not recognize 'import cpuinfo'

### ISSUE THREAD

**Issue by ullix** [microsoft/pyright#6837] opened 2023-12-28 17:23 UTC
It reports:

"Import "cpuinfo" could not be resolvedPylance(reportMissingImports(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)"

![image](https://github.com/microsoft/pyright/assets/9335726/958171d3-582f-48a7-9f7f-b004734e48bf)

though Python does import it and software using it runs correctly. https://pypi.org/project/py-cpuinfo/

My system:
Linux Mint 21
Python 3.10.12

Visual Studio Code:
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-91-generic

**Comment by erictraut** [comment] 2023-12-28 17:27
This is a duplicate of #6823, which I've already closed. I think you mean to open a new bug report in the [pylance-release issue tracker](https://github.com/microsoft/pylance-release/issues).

**Closed by erictraut** 2023-12-28 17:27 UTC
Labels: bug

**Comment by ullix** [comment] 2023-12-28 17:33
:-/ Sorry!
