### ISSUE TITLE
Modules in symlinked  directories cannot be resolved

### ISSUE THREAD

**Issue by robertocarta** [microsoft/pyright#752] opened 2020-06-23 08:30 UTC
**Describe the bug**
importing modules from symlinked subdirectories causes [Pyright (reportMissingImports)]

**VS Code extension or command-line**
Running pyright with macos on neovim with coc-pyright on MacOS

**Comment by erictraut** [comment] 2020-06-27 03:41
Could you provide more detailed repro steps? It seems to be working for me. 

Here's what I did... I created a subdirectory called "dir1" and placed within it a file called "file1.py". Then I created a symlink dir2 that points to dir1. Here's what my hierarchy looks like:
Workspace:
   dir1
       file1.py
   file2.py
   dir2 (symlink pointing to dir1)

Within file2.py, I typed:
```
import dir1.file1
import dir2.file1
```
Both of these imports resolved as expected.

**Comment by erictraut** [comment] 2020-06-30 19:04
@robertocarta, do you have any further details here? Without a reproducible case, I won't be able to address the issue you've reported.

**Comment by erictraut** [comment] 2020-07-01 08:55
Closing for now, since I don't have enough information to repro. I'm happy to re-open it if more details are provided.

**Comment by adrianimboden** [comment] 2021-03-09 15:37
I happen to have the same problem here (Ubuntu).
https://github.com/adrianimboden/pyright_with_symlink
![image](https://user-images.githubusercontent.com/2713705/110496292-a0ea8900-80f5-11eb-8c2c-d7169c2595aa.png)

**Comment by erictraut** [comment] 2021-03-09 23:52
Thanks for the great repro. This will be addressed in the next release.

**Comment by erictraut** [comment] 2021-03-10 06:22
This is addressed in pyright 1.1.120, which I just published. It will also be included in the next release of pylance.

**Closed by erictraut** 2021-03-10 06:22 UTC
Labels: addressed in next version, enhancement request

**Comment by carschandler** [comment] 2023-10-19 17:35
@erictraut did this issue also address single files that were symlinked? I have a single `.py` file that I'd like to symlink from another directory on my system into the project root of my current project. I've verified that python can import it, but pyright cannot resolve the import.

Thanks!

**Comment by eekhof** [comment] 2025-03-16 15:05
> [@erictraut](https://github.com/erictraut) did this issue also address single files that were symlinked? I have a single `.py` file that I'd like to symlink from another directory on my system into the project root of my current project. I've verified that python can import it, but pyright cannot resolve the import. When I copy the file itself, pyright is able to resolve.
> 
> EDIT: I think this must be an issue with neovim/lspconfig's configuration because it resolves the import in VS Code.
> 
> Thanks!

Hey, did you by chance find a solution? I am struggling with the same issue
Best
