### ISSUE TITLE
tuple(numpy.sum([1, 2, 3])) gives error

### ISSUE THREAD

**Issue by nschloe** [microsoft/pyright#1226] opened 2020-12-03 10:00 UTC
Running pyright on
```python
import numpy

# a = numpy.prod([1, 2, 3])  # same
a = numpy.sum([1, 2, 3])

tuple(a)
```
gives
```
  6:7 - error: Argument of type "number[Unknown] | ndarray" cannot be assigned to parameter "iterable" of type "Iterable[_T_co]" in function "__new__"
    Type "number[Unknown] | ndarray" cannot be assigned to type "Iterable[_T_co]"
      "__iter__" is not present (reportGeneralTypeIssues)
```
This is probably because numpy's sum might return a `numpy.array` if the input array is multidimensional and one uses the `axis` argument. I'm not sure if to call this a pyright or a numpy bug.

**Comment by erictraut** [comment] 2020-12-03 15:21
The latest published version of numpy doesn't include inlined types or packaged type stubs. It doesn't contain a "py.typed" file, and therefore doesn't claim to be typed. If you use the default settings in pyright, all imports from numpy will be treated as "unknown" types, and you won't see this error. I'm guessing that you have "useLibraryCodeForTypes" set to true. (This is not the default setting in pyright, but it is in pylance.) If you enable this feature, pyright will attempt to infer type information from the library implementation. This is typically sufficient for basic language server features like completion suggestions and signature help, but it's not sufficient for type checking. It will produce many errors like the one above.

So you need to either disable "useLibraryCodeForTypes" or find/create type stubs for numpy. Otherwise you'll see errors like this one.

**Comment by nschloe** [comment] 2020-12-03 15:27
I should have said I'm running on numpy master,
```
python3 -c "import numpy; print(numpy.__version__)"
```
```
1.21.0.dev0+20201201232031_33dc7be
```
which does have stubs.

**Comment by erictraut** [comment] 2020-12-04 20:21
I haven't been able to successfully install numpy from the master branch, so I haven't been able to repro this. @jakebailey, if you have time, could you take a look at this one?

**Comment by erictraut** [comment] 2020-12-07 22:39
Looking at the type stubs for the numpy master branch, the `sum` method has three overloads. The one that pertains here is:
```python
    @overload
    def sum(
        self,
        axis: Optional[_ShapeLike] = ...,
        dtype: DTypeLike = ...,
        out: None = ...,
        keepdims: bool = ...,
        initial: _NumberLike = ...,
        where: _ArrayLikeBool = ...,
    ) -> Union[number, ndarray]: ...
```

The `number` symbol refers to a generic class with a single type parameter, but no type argument is provided here. I consider that a bug in the type stub. It should probably be `number[Any]`. In any case, that's not the problem you're seeing here.

The problem is that you're trying to initialize a tuple with the return result of the `sum` call. The `tuple`'s constructor requires an Iterable type. The `ndarray` type is iterable, but `number` is not. So pyright is correctly reporting a type error here. 

If you think the `sum` function is annotated incorrectly in the type stub, please report the problem in the numpy repo. 

I'm going to close this because pyright is doing the right thing here.

**Closed** 2020-12-07 22:39 UTC
Labels: as designed

**Comment by nschloe** [comment] 2021-08-04 10:52
FWIW, numpy has fixed the issue now; the warnings now longer occur.
