### ISSUE TITLE
Clarification on "Guidance for Library Authors"

### ISSUE THREAD

**Issue by smackesey** [microsoft/pyright#3147] opened 2022-03-04 16:04 UTC
I'm working on getting the large library [Dagster](https://github.com/dagster-io/dagster) to fully-typed status.

I read the [Typing Guidance for Python Libraries](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) doc in this repo. While this doc makes many recommendations that directly cite various PEPs (most importantly PEP 561), it also includes specific directions for defining the public interface of a library. No PEP is cited for these directions and I'm not aware of any PEP that specifies them:

>If a “py.typed” module is present, a type checker will treat all modules within that package (i.e. all files that end in “.py” or “.pyi”) as importable unless the file name begins with an underscore. These modules comprise the supported interface for the library...

>A module can expose an __all__ symbol at the module level that provides a list of names that are considered part of the interface. This overrides all other rules above, allowing imported symbols or symbols whose names begin with an underscore to be included in the interface.

Two questions on this:

(1) Is this way of specifying a public interface a Python standard or a Pyright-specific requirement? If it's a Python standard, is there an "official" reference or spec of some kind?

(2) The library I work on exposes its entire intended public interface at the top level-- that is, all use as a library is intended to start from `from dagster import ...`. The top-level module is also the only one containing an `__all__` declaration. There are 100s of internal submodules not intended for public access. Am I correctly understanding that, in order to align this public interface definition with the standard in the doc, we either have to:

- Prefix every single internal module with an underscore.
- Add `__all__ = []` to every single internal module.

If I understand correctly, IMO this means of declaring a public interface is unnecessarily cumbersome and will seriously slow adoption of typing standards. Large codebases often have much more internal than public code, but this standard forces code to opt out of being public rather than opt in. It would be helpful if there were a way to reverse that logic, e.g. simply treat the public interface as all `__all__` declarations in the codebase.

**Comment by erictraut** [comment] 2022-03-04 17:40
Thanks for reaching out.

The typing guidelines document was meant to consolidate relevant information from various PEPs and fill in missing recommendations that are not (currently) covered in any PEP. I wrote it with input from multiple Python package maintainers, typeshed maintainers, and members of the Python typing community (including the maintainers of the three other major Python type checkers — mypy, pyre and pytype).

Pyright is the reference implementation for this set of guidelines. A version of the document (which has the pyright-specific sections removed) has been checked in to the [python/typing](https://github.com/python/typing/blob/master/docs/source/libraries.rst) repo, the community forum for all things related to Python typing.

Some additional background that might be useful here... Pyright is Microsoft's open-source Python type checker. It is actively used by ~50K developers for static type checking. Pylance is Microsoft's default Python language server for VS Code. It builds on top of pyright to provide programming efficiency features like completion suggestions (Intellisense), in-editor documentation, auto-import, refactoring tools, etc. Pylance is actively used by ~4M Python developers. Most of these users (98%+) don't enable static type checking diagnostics, but they still benefit from static type information provided by libraries. The investments that you and other library maintainers are making in type annotations is helping all of these users, so we're very grateful for your contributions!

We (the maintainers of pyright and pylance) were especially motivated to clarify aspects of inlined typing that were otherwise left unspecified in PEP 484, 561, etc. We want to ensure that type information in libraries works well not only for static type checkers like mypy and pyright but also for language servers like pylance.

Now, to answer your questions...

> Is this way of specifying a public interface a Python standard or a Pyright-specific requirement?

It's effectively a standard but not one that is documented in a PEP. The use of an underscore to specify private files is used extensively throughout typeshed, and most (all?) type checkers enforce this convention for type stubs. These guidelines extend this convention to "py.typed" packages that include type information inline. Likewise, PEP 484 documents the use of certain redundant forms of an `import` statement to specify that a symbol is meant to be re-exported from within a type stub. These guidelines extend this mechanism to "py.typed" packages.

> Am I correct in understanding that, in order to align...

That depends on your intent as a library author. If your intent is to export all public symbols _only through the top-level module_, then you would need to prefix all of your other modules with an underscore. You wouldn't need to add `__all__` to any of your internal modules; that's required only for the public modules — and only if you intend to support wildcard imports.

If your intent is to support imports directly from other submodules (e.g. `from dagster.api.get_server_id import sync_get_server_id`), then you would retain the public names for these modules.

Our goal was to give you, as a library author, the mechanisms needed to define your library's public interface. The tools then help enforce that interface contract and help you validate that it is "type complete".

> this standard forces code to opt out of being public

Yes. Many library authors intentionally allow the consumers of their libraries to import directly from submodules even if they also re-export many of the symbols from the top-level module. So the feedback from other library authors was that "opt out" was preferable to "opt in". This also followed the standard that was established in typeshed where all type stubs for all submodules were assumed to be public unless named with an underscore.

I can understand why you would prefer "opt in" rather than "opt out". That's reasonable given your library's structure, but it's contrary to what I've heard from most other library authors.

In my first draft of this document, I proposed an extension to the "py.typed" file format to allow library authors to specify which submodules should be considered public versus private. I received rather strong pushback on this proposal because it was deemed too complicated and unnecessary given that there was already an established convention based on file naming. I'm not opposed to bringing back such a proposal if there is sufficient interest from library maintainers, but I fear that it would be an uphill battle to get it standardized.

What downsides do you see in renaming your internal modules? It's a one-time change, and I would think that it could be largely automated. There are probably various unit tests and other code that would need to be adapted, but I would think that could be done pretty quickly. Pylance and PyCharm both have features that will do this renaming automatically throughout the code base.

Do you see other downsides? Are you worried that some consumes of dagster might be importing directly from these submodules, and their code would consequently break if you made this change?

Thanks again for reaching out, and let me know if/how I can help you out on the tooling side of things.

**Comment by smackesey** [comment] 2022-03-04 18:10
Thanks @erictraut for this very thorough response. A few questions:

First, what is the effect of prefixing a package with an underscore? I didn't see that specified in the doc, but if marking a package private in this way applies recursively to its submodules (which wouldn't then need to be underscore-prefixed), that would ease the burden of the transition.

>...I proposed an extension to the "py.typed" file format...

I wish your proposal had passed. But putting that aside, your statement suggests that`py.typed` has a format? Is this true? I thought it was just an empty marker file, is there content that can go in there (or was that just your proposal)?

> What downsides do you see in renaming your internal modules? It's a one-time change, and I would think that it could be largely automated.

I agree that the mechanics of the transition are not difficult given the right tools. Mostly my concerns are around aesthetics and an extra (nuisance) layer of complexity. We have loads of cross-cutting internal submodule imports, if they all look like this: `from dagster._foo._bar._baz import x` it's kind of ugly. It's also unusual, and is just one more deviation (every new module you add must be prefixed by underscore) from "standard" Python for new devs on the project to internalize. Also, I'm not sure of the tooling everyone uses-- for those who are not making heavy use of auto-imports from a language server, it will be an annoying transition causing lost productivity.

**Comment by erictraut** [comment] 2022-03-04 19:05
> what is the effect of prefixing a package with an underscore?

I'm not sure I understand the question. Maybe I'm using the wrong terms, but I think "package" refers to a unit of installation, and "module" refers to an import target within a package. Is that consistent with how you're using the terms? If so, I'm not sure what it would mean to "prefix a package with an underscore". Can you elaborate?

> Is this true [that py.typed has a format]?

I guess it's a stretch to call it a "file format" currently :). PEP 561 says that it can either be empty or contain a single line "partial". My proposal called for it to become a yaml file with a few specified keys.

> Mostly my concerns are around aesthetics

I see. Yeah, aesthetics are subjective, and I'm not sure there's much I can offer here in terms of a workaround. I suppose it could be possible to post-process the source files when running the scripts that build & publish the package, but that sounds error-prone.

> It's also unusual

Actually, it's quite common among libraries I've seen — especially among newer libraries.

One thing that you might find useful is the "--verifytypes" command-line option that I added to pyright. It allows you to verify the "type completeness" of a library. A number of library authors have incorporated it into their CI pipelines. That helps prevent regressions and teach new devs on the project about these issues. Just a thought.

**Comment by smackesey** [comment] 2022-03-04 19:14
>Maybe I'm using the wrong terms, but I think "package" refers to a unit of installation, and "module" refers to an import target within a package.

I'm using "package" in the sense that it's defined in the [Python docs](https://docs.python.org/3/tutorial/modules.html#packages)-- not as a unit of installation, but as a module that itself contains other modules. Here's a concrete example of what I'm asking:

I have a module `dagster.core.definitions`. If I change `dagster.core` to `dagster._core`, does that mean that `dagster._core.definitions` is now also treated as private? Or do I have to make it `dagster._core._definitions`?

**Comment by erictraut** [comment] 2022-03-04 19:16
Ah, thanks for the clarification. Yes, if you rename `core` to `_core`, then everything under it is effectively private as well.

**Comment by smackesey** [comment] 2022-03-04 19:30
>Yes, if you rename core to _core, then everything under it is effectively private as well.

Ah, that makes things much easier-- if I understand, then for our library architecture we only need to rename the submodules one level under `dagster` rather than _every_ submodule.

FWIW I think it's worth adjusting the typing doc to clarify this, maybe:

If a “py.typed” module is present, a type checker will treat all modules within that package (i.e. all files that end in “.py” or “.pyi”) as importable unless the module is marked private. There are two ways to mark a module private: (1) the module's filename begins with an underscore; (2) the module in inside a sub-package marked private. For example:

- `foo._bar` (`_bar` is private)
- `foo._bar.baz` (`_bar` and `baz` are private)
- `foo._bar.baz.bop` (`_bar`, `baz`, and `bop` are private)

**Comment by erictraut** [comment] 2022-03-05 00:53
Good suggestion. I've incorporated your suggested clarification into the document.

**Closed** 2022-03-05 00:53 UTC

**Comment by smackesey** [comment] 2022-03-11 23:47
Since this conversation I've been experimenting with getting `dagster` to fully-typed status. The first thing I did was, as discussed, prefix all top-level submodules with an underscore. This seemed to "work" in the sense that `pyright --verifytypes` adjusted its estimate (prior to the rename, "Type Completeness Score" was in the 40s):

```
$ pyright --verifytypes dagster

Symbols exported by "dagster": 263
  With known type: 212
  With ambiguous type: 9
  With unknown type: 42
  Functions without docstring: 25
  Functions without default param: 59
  Classes without docstring: 0

Other symbols referenced but not exported by "dagster": 4751
  With known type: 3475
  With ambiguous type: 70
  With unknown type: 1206

Type completeness score: 80.6%

Completed in 3.699sec
```

However, our team is reluctant to proceed with the rename because it breaks outstanding PRs and any user code importing from submodules (even though they should be importing from top-level), in addition to whatever unknown unknowns will result from the change.  So I decided to go with plan B, adding an `__all__ = []` to all of our submodules. However, this appears to have had virtually no effect on the Type Completeness Score:

```
Symbols exported by "dagster": 6665
  With known type: 3262
  With ambiguous type: 234
  With unknown type: 3169
  Functions without docstring: 3134
  Functions without default param: 345
  Classes without docstring: 394

Other symbols referenced but not exported by "dagster": 5418
  With known type: 4897
  With ambiguous type: 36
  With unknown type: 485

Type completeness score: 48.9%

Completed in 6.847sec
```

Based on the doc, I was under the impression that adding `__all__ = []` to all submodules should effectively make them private, but that doesn't seem to be the case-- their symbols are still being included in the "Symbols exported by "dagster"" count. Is this intended behavior? Am I missing something?

**Comment by erictraut** [comment] 2022-03-12 00:49
The `__all__` symbol is primarily meant to control the set of symbols that are imported with a wildcard import. Any symbol in an `__all__` statement is considered public, but there are other ways to mark a symbol as public as well. In particular, any imported symbol that is re-exported via a redundant form of import (i.e. `from x import y as y`). Also, any symbol declared in the global namespace of a module is considered public unless its name begins with an underscore. If a symbol is otherwise public, setting `__all__ = []` doesn't make it private. Does that help?

**Comment by smackesey** [comment] 2022-03-12 01:04
Thank you for clarifying, but this seems inconsistent with what is written in [the standard] you linked (https://github.com/python/typing/blob/master/docs/source/libraries.rst#library-interface):

>Each module exposes a set of symbols. Some of these symbols are considered "private” — implementation details that are not part of the library’s interface. Type checkers can use the following rules to determine which symbols are visible outside of the package.
>
>- Symbols whose names begin with an underscore (but are not dunder names) are considered private.
>- Imported symbols are considered private by default. If they use the import A as A (a redundant module alias), from X import A as A (a redundant symbol alias), or from . import A forms, symbol A is not private unless the name begins with an underscore. If a file __init__.py uses form from .A import X, symbol A is treated likewise. If a wildcard import (of the form from X import *) is used, all symbols referenced by the wildcard are not private.
>- A module can expose an __all__ symbol at the module level that provides a list of names that are considered part of the interface. **This overrides all other rules above** , allowing imported symbols or symbols whose names begin with an underscore to be included in the interface.

If `__all__` "provides a list of names that are considered part of the interface" and "overrides all other rules above", then the straightforward reading of this is that, if `__all__` is present, a symbol is not public unless it is in `__all__`. 

If this is not intended, I strongly encourage you to consider it as a workaround to the opt-in/opt-out problem. It allows large projects an alternative approach to becoming typed. I doubt think our team are the only ones who will be hesitant to do a mass module rename.

**Comment by erictraut** [comment] 2022-03-12 01:09
I can understand how you would interpret the documentation in that manner. I'll work on a clarification.

I don't think this is something we can easily change. The current recommendations were based on PEP 484 behaviors dictated for type stubs and further hammered out with the authors of the other major Python type checkers. 

I think most libraries — at least those that were written or rev'ed within the past few years — already use the underscore convention. I understand that it may be painful to do a rename, but it's a one-time change. I think you're going to need to either bite the bullet and do the rename or live with the consequences of having all of your submodules considered part of your public interface.

**Comment by erictraut** [comment] 2022-03-12 01:12
Documentation has been updated for clarity.

**Comment by smackesey** [comment] 2022-03-16 23:21
I have continued to experiment with this and, while `pyright --verifytypes` is behaving as I would expect with respect to marking symbols public/private, the exposed completion candidates are not. I was under the impression that all private symbols should be filtered out of completion candidates, while all public symbols should appear as candidates given a suitable prefix.

That's not what I'm seeing, so maybe the assumption is wrong. I can post some more concrete results if necessary, but first @erictraut could you please clarify the following:

1. Are the public/private symbol rules described in the [Typing Spec](https://github.com/python/typing/blob/master/docs/source/libraries.rst) supposed to apply to completion candidates?
2. If the same name and value is public in multiple modules in the same library, will I see that name listed twice in the candidate list. If not, how is the de-dup done/how is the module for auto-import resolution chosen?
3. Given the same `pythonPath` and `useLibraryCodeForTypes` setting, is the list of candidates (not necessarily the order) from a given library in `pyright` and `pylance` supposed to be identical?

**Comment by erictraut** [comment] 2022-03-17 06:03
The notion of which completion candidates should appear is somewhat independent of symbols are public or private. Currently the completion providers in pyright and pylance offer both public and private completion suggestions. A diagnostic rule (`reportPrivateUsage`) emits errors if a private symbol is used. We've talked about omitting private symbols from completion suggestion lists, but I'm guessing we'd get a fair amount of negative feedback from Pylance users if we do that. I'm hoping that as more libraries adopt the guidance we've published, it will become more feasible to omit private symbols from the completion suggestion lists. That might take a while though. Perhaps we should be more aggressive about omitting private symbols to encourage library authors to make the necessary changes. I'm interested in hearing your thoughts on this.

If the same name is exported from multiple modules, the auto-import logic in pyright and pylance prefer the shortest module path. Only the shortest path is listed in the completion list, and the longer paths are de-duped. Currently there's no way for a library author to override that heuristic. So far, that heuristic seems to work well.

The completion provider in pyright is a minimal implementation and lacks some of the more sophisticated features found in pylance. So no, the two will not be identical. For example, pylance includes background indexing mechanism that proactively identifies public module-level symbols in installed libraries so it can offer a complete set of auto-import suggestions. Pyright offers only the suggestions that it has previously encountered and cached in memory.

**Comment by smackesey** [comment] 2022-03-17 16:33
Thanks. Some follow-ups:

> The notion of which completion candidates should appear is somewhat independent of symbols are public or private.

Interesting-- FWIW I find this quite unintuitive-- why mark a symbol private if tooling is going to expose it to users as a value they should access (implied by it appearing in autocomplete)? And if it doesn't affect completion, then what exactly _are_ the effects of marking a symbol private? From what I can tell, the only effects are:

a. It affects how the symbol's status is tallied when running `pyright --verifytypes`
b. It guides the `reportPrivateUsage` diagnostic rule.

Am I missing anything else?

>We've talked about omitting private symbols from completion suggestion lists, but I'm guessing we'd get a fair amount of negative feedback from Pylance users if we do that. I'm hoping that as more libraries adopt the guidance we've published, it will become more feasible to omit private symbols from the completion suggestion lists.

Seems to me that there is an easy win-win available here-- why not omit private symbols if and only if a module declares itself to be fully typed (i.e. has an empty `py.typed`, no `"partial\n"`). This allows libraries with a complete public API definition to give their users the full benefit of it, without compromising UX for libraries that aren't there yet. For a large library like Dagster, the UX is much improved by hiding private symbols, the APIs are complex enough already without bombing the user with autocomplete noise.

> If the same name is exported from multiple modules, the auto-import logic in pyright and pylance prefer the shortest module path.

I've observed (from playing around with both) that this rule describes the current behavior of `pylance` but not `pyright`.  Is that expected? BTW I posted [an issue](https://github.com/microsoft/pylance-release/issues/2150) about this some months ago.

> If the same name is exported from multiple modules, the auto-import logic in pyright and pylance prefer the shortest module path. Only the shortest path is listed in the completion list, and the longer paths are de-duped. 

Just to be clear-- do you mean literally just the same _name_, or does the name also need to have the same referent? i.e. If I have two modules `a.py` and `b.py`:

```
# a.py
THE_VALUE = 'value_in_a'

# b.py
THE_VALUE = 'value_in_b`
```
Will `THE_VALUE` be deduped in this scenario?

> Pyright offers only the suggestions that it has previously encountered and cached in memory.

Could you explain a little more about this? When using pyright as a language server, when does it first encounter symbols? My experience now is that, if I take a fresh instance of pyright LSP in a blank file and invoke completion for the prefix `Asset` (common in Dagster):

- When the file is totally blank, no completion candidates
- If there is one line in the file with `import dagster`, no completion candidates
- If there is one line in the file with `from dagster import op`, I get the full set of completion candidates

> For example, pylance includes background indexing mechanism that proactively identifies public module-level symbols in installed libraries so it can offer a complete set of auto-import suggestions. Pyright offers only the suggestions that it has previously encountered and cached in memory.

Interesting-- from this description I would expect Pylance to offer _more_ candidates, but from what I've seen it actually offers fewer. If I have the single-line file `from dagster import op`, and invoke completion for `Asset`, then Pylance seems to be showing me only public symbols for completion, while Pyright shows me all symbols starting with `Asset` in dagster.

**Comment by erictraut** [comment] 2022-03-18 15:24
> why not omit private symbols if and only if a module declares itself to be fully typed

Because we've seen a number of libraries that declare themselves to be fully typed but are lacking types and do not fully follow the guidance. As I said, we'll likely get negative feedback from Pylance uses if we make this change. But maybe it's still a worthwhile change to force authors of "py.typed" libraries to make the necessary changes to their libraries. I'll discuss this with my colleagues on the pylance team. 

I wouldn't be in favor of adding another configuration knob to control this, but it is an option.

> Just to be clear-- do you mean literally just the same name, or does the name also need to have the same referent?

It needs to be the same name _and_ refer to the same symbol. If there are two different symbols with the same name, they will both appear in the completion list.

> Could you explain a little more about this? When using pyright as a language server, when does it first encounter symbols?

Pyright is a lazy type evaluator, so it encounters types on demand. If a code file references a type (via an import), pyright will evaluate the imported type. If a code file doesn't reference a type either directly or indirectly, then pyright will not evaluate the type and won't know about it for purposes of auto-import. The appearance of auto-import suggestions can appear somewhat random to the end user in pyright. That's why pylance added a background indexing mechanism so it is more deterministic.

If you see behaviors in auto-import that you think are suspect, please file bugs in the [pylance-release project](https://github.com/microsoft/pylance-release) so the pylance team responds to them.

**Comment by smackesey** [comment] 2022-03-19 14:14
>If you see behaviors in auto-import that you think are suspect, please file bugs in the [pylance-release project](https://github.com/microsoft/pylance-release) so the pylance team responds to them.

Well, the issue I see only happens in `pyright`. I initially filed it here months ago, and you transferred it to the Pylance repo: https://github.com/microsoft/pylance-release/issues/2150

Given that the issue only occurs in `pyright`, is that still the best place for it?

**Comment by erictraut** [comment] 2022-03-19 14:22
The pylance team owns and maintains the language server features in pyright.

Pyright is primarily a type checker. It does have some simple language server features, but if you want full language server features like auto-import backed by indexing, you should use pylance instead. We currently have no plans to backport these more advanced language server features to pyright, so if you want to take advantage of these features, we recommend switching to pylance.

**Comment by bluss** [comment] 2024-10-13 09:47
[PEP 561](https://peps.python.org/pep-0561/) links to https://typing.readthedocs.io/en/latest/spec/distributing.html#packaging-typed-libraries  as the authoritative doc, and that doc still has the wording “This overrides all other rules above” about `__all__`.

I'm mentioning this because I came here needing the same clarifications - or with the same expectations - about `__all__`, after reading Python documentation.

**Comment by erictraut** [comment] 2024-10-13 15:38
@bluss, if you'd like to suggest changes to the Python typing spec, the process is documented [here](https://github.com/python/typing-council#decisions).
