### ISSUE TITLE
"extend" option to inherit config from the specified path

### ISSUE THREAD

**Issue by uKaigo** [microsoft/pyright#6975] opened 2024-01-13 20:39 UTC
**Is your feature request related to a problem? Please describe.**
No. I simply would like to have the option to extend a "base" configuration file.

**Describe the solution you’d like**
I'd like to have the option `extends`, similar to tsconfig. This way I could have a global `pyproject.toml` (or `pyrightconfig.json`) with configuration for all my projects, and make specific changes locally.

**Comment by erictraut** [comment] 2024-01-13 20:46
This is a duplicate of https://github.com/microsoft/pyright/issues/4366. Please upvote the original issue. So far, it hasn't received many upvotes.

**Closed by erictraut** 2024-01-13 20:46 UTC
Labels: enhancement request
