### ISSUE TITLE
auto importing exposing "lib.site-packages"

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pyright#665] opened 2020-05-10 16:26 UTC
**Describe the bug**
See this test "https://github.com/microsoft/pyright/blob/master/server/src/tests/fourslash/completions.autoimport.Lib.Found.duplication.fourslash.ts#L36" for more detail.

Basically, when auto import adding a module, in a certain condition, it exposes lib.site-packages.

**To Reproduce**
See the test above for repro steps

**Expected behavior**
Rather than "from lib.site-packages import xxx", it should just add "import xxx"

**Screenshots or Code**
![site-packages](https://user-images.githubusercontent.com/1333179/81504975-354f4980-92a1-11ea-921b-d4467e8e42ff.gif)

**VS Code extension or command-line**
vscode extensions

**Comment by erictraut** [comment] 2020-05-12 07:56
Auto-import is designed to import using only "from X import Y" syntax, not the older (and not recommended) "import X" syntax. As such, it should never recommend a top-level module for completion. 

In this case, it was offering "testLib" because of a bug in the auto-completion logic. I've fixed that bug, and it no longer offers "testLib" as a completion suggestion, as designed. It does now offer "test1" and "test2" as completion options. If you select "test1", for example, it inserts the line "from testLib import test1".

**Comment by erictraut** [comment] 2020-05-16 16:57
This is now addressed in Pyright 1.1.37, which I just published.

**Closed by erictraut** 2020-05-16 16:57 UTC
Labels: bug, fixed in next version
