### ISSUE TITLE
`self` type is incorrect after isinstance call

### ISSUE THREAD

**Issue by Hunterlige** [microsoft/pyright#8350] opened 2024-07-09 15:37 UTC
**Describe the bug**
Hi

`isinstance(self, type)` no longer updates the type of the self. The behavior change between v1.1.369 and v1.1.370.

**Code or Screenshots**
Playground reproduction:
https://pyright-play.net/?pyrightVersion=1.1.370&pythonVersion=3.13&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMogCmAboQIYA2A%2BvAoQLABQTAxhWQM4dQBCnhACgCUALiZQJUACaFgsQhxgCOhCsFHjJWmXJgKlADxFQA8gg2MtVyQhCpDQzdaRyUYfEg6pFZFC0EqagA0puZiltZWIGSehFAAapQAroQAoiDgIMJOUSTk1LQBquo5WnqKysWOjGyc3ACCAnwqFloIdazsXLxN-K02HcyMZlAAvFAC9VAAPrzVTAtDi4tAA

```python
from typing import reveal_type

class Base():
    def test(self):
        def test(x: Op):
            print(x)
        if not isinstance(self, Op):
            raise ValueError()
        reveal_type(self)
        test(self)
class A(Base):
    pass
class B(Base):
    pass

Op = (A | B)
```

Works with pyright v1.1.369, but does not work with pyright v1.1.370

**VS Code extension or command-line**
Command-line, pyright v1.1.370

**Comment by erictraut** [comment] 2024-07-09 16:34
Although it may not be immediately obvious, this is a duplicate of #8302. A fix is in place and will be included in the next release. Apologies for the regression.

**Comment by Hunterlige** [comment] 2024-07-09 16:49
Thank you for your detailed explanation and for taking the time to explain the underlying issue.

**Closed** 2024-07-10 00:40 UTC
Labels: bug, addressed in next version
