### ISSUE TITLE
Discrepancy in handling LiteralString with pre-PEP695 and PEP695 syntax

### ISSUE THREAD

**Issue by luwqz1** [microsoft/pyright#9052] opened 2024-09-22 16:21 UTC
```python
from typing import LiteralString, Annotated, TypeVar, TypeAlias, reveal_type

type A[String: LiteralString] = Annotated[String, ...]

String = TypeVar("String", bound=LiteralString)
B: TypeAlias = Annotated[String, ...]

reveal_type(A["pyright"])  # Type of "A["pyright"]" is "GenericAlias" and Pyright nothing to report
reveal_type(B["pyright"])  # Type of "B["pyright"]" is "Unknown" and Pyright reports an error "reportUndefinedVariable"
```

**Comment by erictraut** [comment] 2024-09-23 18:46
I think pyright is working as intended here, so I don't consider this a bug.

Type aliases are intended to be used in [annotation expressions](https://typing.readthedocs.io/en/latest/spec/annotations.html#type-and-annotation-expressions). You're using them here in value expressions, which means that pyright will attempt to interpret them as their corresponding runtime types. I say "attempt" because the runtime implementation details for many of these special forms (including `Annotated`) are undocumented. 

Within a type expression, explicit specialization of a generic type alias, the subscripts are interpreted as type arguments and must follow the rules of type expressions. The subexpression `"pyright"` will be interpreted in this context as a forward declaration, and the contents of the string will treated as a type expression. If your intent is to specify a literal string type, you would need to use the `Literal` special form, as in `A[Literal["pyright"]]`.

The Python typing spec was recently updated to define the concept of a "type expression" and [where such expressions](https://typing.readthedocs.io/en/latest/spec/annotations.html#type-and-annotation-expressions) are expected to appear within the Python grammar. The typing spec is currently silent on how type checkers should evaluate type expressions when they appear outside of normal type annotation locations.

If you use your specialized type aliases in type annotations, you'll see that the behavior is consistent (and in conformance with the typing spec).

```python
v1: A["pyright"]  # Error: "pyright" is not defined
v2: B["pyright"]  # Error: "pyright" is not defined
```

Draft [PEP 747](https://discuss.python.org/t/pep-747-typeexpr-type-hint-for-a-type-expression/55984/44) attempts to provide some clarity about how type expressions should be treated when they're used outside of type annotations. This PEP hasn't yet been finalized, but pyright has provisional support for the latest draft. You can enable this by setting "enableExperimentalFeatures" to true in your pyright configuration. When you do this, you'll see that the behavior for your code sample above changes somewhat.

**Closed by erictraut** 2024-09-23 18:46 UTC
Labels: bug
