### ISSUE TITLE
Checking If multiple values are None or not

### ISSUE THREAD

**Issue by Mustafasavran** [microsoft/pyright#1730] opened 2021-04-05 07:12 UTC
**Describe the bug**
Pyright detects not supported operator like '*' if we pass one None value to a function and we can easily check If one value is equal to None or not but  If we have 3 or more variable to check, we need to check every value.

**To Reproduce**

Pyright reports an issue for the below code:

`
    if None not in (x, y, z):
        res =  x * y * z`

However when we change if statement to this one, It does not report an issue:

`if x is not None and y is not None and z is not None`

**Comment by erictraut** [comment] 2021-04-05 16:15
Thanks for the feature request. For a complete list of supported type narrowing patterns in pyright, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-guards).

This is effectively a duplicate of this issue: https://github.com/microsoft/pyright/issues/1714. (I say "effectively" because the other issue used a list, whereas your sample used a tuple, and those are different patterns.)

As I said in the other issue, pyright's list of detected patterns for type narrowing is already longer than any other type checker. Each new pattern that's added requires custom logic and adds to the complexity and computation overhead of the analyzer, so I'm reluctant to add more patterns unless they are proven to be sufficiently common. I am not convinced that this pattern (and the one in the linked bug) are common enough to justify adding the custom logic in this case.

I'll take this request as an upvote for the feature, but for now I'm going to close the issue.

**Closed** 2021-04-05 16:15 UTC
Labels: as designed
