### ISSUE TITLE
pandas droplevel

### ISSUE THREAD

**Issue by gokturksm** [microsoft/pyright#735] opened 2020-06-17 17:47 UTC
**_edit:_**
same for groupby and concat:
https://github.com/gokturksm/Fikirler/blob/master/so_6.py

**Description**
Pandas dataframe object unstacked, dropped NAs, and lastly dropped a level. Drop level returns a dataframe without the specified column level(s). This process has no problem but pyright says "Cannot access member "droplevel" for type "NoReturn" and "Member "droplevel" is unknownPyright (reportGeneralTypeIssues)". I don't exactly know why, so I'm opening this issue.

**To Reproduce**
https://github.com/gokturksm/Fikirler/blob/master/so_10.py#L27

**Expected behavior**
No problem would be produced by pyright.

**Screenshots or Code**
shared already

**VS Code extension or command-line**
extension

**Additional context**
disabled all other completion engines or python-related things.
"pyright.useLibraryCodeForTypes": true

**Comment by falan** [comment] 2020-06-18 01:21
Pandas itself have no complete type hints.
You need type stub files for Pandas. Unfortunately, there are no mature type stubs for Pandas. The closest one maybe on  [https://pypi.org/project/data-science-types/](url). You can use it as a starting point to typing the Pandas stub files.

**Comment by erictraut** [comment] 2020-06-18 02:47
Thanks for reporting the issue.

Pyright is able to extract some type information from the implementation, so this case should still work. The problem is that when Pyright infers the return type of `dropna`, it is included a `NoReturn` type in the union. The `NoReturn` type should be stripped out of any union that includes it. Once it's removed, this error goes away.

This fix will be in the next published version of Pyright.

**Comment by erictraut** [comment] 2020-06-20 21:45
This is now fixed in version 1.1.44, which I just published.

**Closed by erictraut** 2020-06-20 21:45 UTC
Labels: bug, fixed in next version

**Comment by nyngwang** [comment] 2022-05-30 11:24
FYI: a similar problem seems to persist: the `groupby` doesn't show up with pyright. This happened on pandas 1.4.2.

<img src="https://user-images.githubusercontent.com/24765272/170982153-74d932fa-a104-4186-a366-22a5459debdd.png" width="600">
