### ISSUE TITLE
False positive when using an unpacked typed dict for variadic keyword arguments with a field overlapping a positional only argument

### ISSUE THREAD

**Issue by Viicos** [microsoft/pyright#9043] opened 2024-09-20 16:00 UTC
Code sample in [pyright playground](https://pyright-play.net/?pythonVersion=3.12&strict=true&locale=en-us&enableExperimentalFeatures=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcANFAKooICGAxgNZkAqiApgCYAiStMAsAChBg9q2BRgqVgApqALkwoYZAPRkAVOvoB3aiDQBnBUTgBKOYKhWoCEKhiyyOvYdPCBklDICMZagF4AJjcBAGIAPihfKABvAHJqOIVAgF93WgAbagMDKCZOaRYEDm5ec0treUV%2BIQFRcQAjAFc0WQV7VQ0tXX0jCio6egBtfIBdcoFrG2yDd2bW6IDgq1CoVhBwEAUABT1qCFYYdagAImoTzFzqDJBWanY4KBmkNC92QQiosnjE5LSBIA)

```python
from typing import Any, Unpack, TypedDict


def fine(a: int, /, **kwargs: Any):
    print(a, kwargs)

fine(1, a=2)
#> 1, {'a': 2}

class TD(TypedDict):
    a: int

def bug(a: int, /, **kwargs: Unpack[TD]):
    pass

bug(1, a=2)  # error: Parameter "a" is already assigned
#> 1, {'a': 2}
```

**Comment by erictraut** [comment] 2024-09-20 16:12
Thanks for the issue.

This has the same root cause as #8964, so fixing one will fix the other.

**Comment by erictraut** [comment] 2024-09-25 01:01
This is addressed in pyright 1.1.382.

**Closed by erictraut** 2024-09-25 01:01 UTC
Labels: bug, addressed in next version
