### ISSUE TITLE
False Positive for "Code is unreachable"

### ISSUE THREAD

**Issue by ELC** [microsoft/pyright#1104] opened 2020-10-17 10:13 UTC
**Describe the bug**
When using context managers defined with classes, and an exception is raised and handled in the `__exit__ `block **without** a try/except, the rest of the code is marked as unreachable although it is perfectly reachable **_if_** the `__exit__ `method returns `True`

**To Reproduce**

```python
class Example:
    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        return True

with Example() as example:
    raise ValueError

print("Hello World")
```

The print statement is marked with "Code is unreachable" although it is.

**Expected behavior**
The return of the `__exit__ `method should be checked and the warning should be applied only if it is `False`

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/14986783/96334530-cc4ed780-1071-11eb-8f59-b395cd14ba0c.png)

**VS Code extension or command-line**
Pyright was used as a VS Code extension.

Pyright Version: v1.1.79

VS Code Info:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by erictraut** [comment] 2020-10-17 15:10
Marking this as a duplicate of https://github.com/microsoft/pylance-release/issues/494

**Closed** 2020-10-17 15:11 UTC
