### ISSUE TITLE
hypothesis.extra.numpy.arrays reportUnknownVariableType error

### ISSUE THREAD

**Issue by JonathanPlasse** [microsoft/pyright#7279] opened 2024-02-16 16:41 UTC
**Describe the bug**
Importing `arrays` from `hypothesis.extra.numpy` cause the error `reportUnknownVariableType`
The return type is `SearchStrategy[ndarray[Any, dtype[Unknown]]]` where `dtype` is said to be unknown.

**Code or Screenshots**
Minimal code used to reproduce the error
![image](https://github.com/microsoft/pyright/assets/13716151/19ecd30a-c6c1-4feb-92af-124b43ac49bb)
Code of `hypothesis/extra/numpy.py` after Go to definition from `arrays`
![image](https://github.com/microsoft/pyright/assets/13716151/49e4ec6c-35ae-43e1-b132-8ac2217f8ad0)
Code of `numpy/_typing/_array_like.py` after Go to definition from `NDArray`
![image](https://github.com/microsoft/pyright/assets/13716151/d2233c86-3e5e-4a3a-9936-5ff030d5f5aa)

```python
from hypothesis.extra.numpy import arrays
```
hypothesis: v6.98.6
numpy: 1.26.4

**VS Code extension or command-line**
Pyright: v1.1.350

**Comment by erictraut** [comment] 2024-02-17 22:44
This behavior is due to a bug in the hypothosis library. The problem is that the return type of the `arrays` function is annotated as `st.SearchStrategy[NDArray[D]]`. The type variable `D` is bound to `DTypeLike`, but `NDArray` requires a type argument that is compatible with `generic`. That means `NDArray[D]` is invalid, and pyright is converting `D` to `Unknown` in this case.

I'm going to close this issue because I think pyright is behaving correctly here. You may want to file an issue with the maintainers of the hypothesis library to bring this bug to their attention.

**Closed by erictraut** 2024-02-17 22:44 UTC
Labels: bug
