### ISSUE TITLE
tuple "index" is not a known memeber

### ISSUE THREAD

**Issue by jerryc05** [Microsoft/pyright#47] opened 2019-04-03 07:04 UTC
**Describe the bug**
```
a=('1','2')
a.index('1')
```
A red underscore is shown under "index" method

**To Reproduce**
type
```
a=('1','2')
a.index('1')
```

**Expected behavior**
no red underscore

**Screenshots or Code**
```
a=('1','2')
a.index('1')
```

**VS Code extension or command-line**
VS Code extension v1.0.8

**Additional context**

**Comment by erictraut** [comment] 2019-04-04 08:15
Thanks for the bug report. I've found and fixed the cause of the bug. The fix will be in the next published version.

**Comment by erictraut** [comment] 2019-04-06 21:51
This is fixed in 1.0.9, which I just published. Thanks again for the report.

**Closed by erictraut** 2019-04-06 21:51 UTC
