### ISSUE TITLE
`TypeIs` narrowing for certain parameterized containers doesn't make sense

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [microsoft/pyright#8109] opened 2024-06-10 01:08 UTC
**Describe the bug**
When using `TypeIs` with a guard function that's meant to narrow the parameterized type of some types of containers, the type pyright infers when that function is used doesn't make sense. I didn't narrow down which containers this occurs with, but gave two as an example below.

**Code or Screenshots**

```python
from typing import MutableSequence
from typing_extensions import TypeIs, reveal_type

# ==== 1) With a list:

def _is_list_of_str(lst: list[str | tuple[str, object]]) -> TypeIs[list[str]]:
    """A relatively weak heuristic to narrow the type of the list to list[str]."""

    return isinstance(lst[0], str)


def example1(thing: list[str | tuple[str, object]]):
    if _is_list_of_str(thing):
        reveal_type(thing)  # Type of "thing" is "<subclass of list and list>"
        # This result doesn't make sense to me. Expected "list[str]".
    else:
        reveal_type(thing)  # Type of "thing" is "list[str | tuple[str, object]]"
        # This doesn't take into account that list[str] would be eliminated as a possibility in this branch. Expected "list[tuple[str, object]]".


# ==== 2) With a MutableSequence:

def _is_mut_sequence_of_str(
    seq: MutableSequence[str | tuple[str, object]],
) -> TypeIs[MutableSequence[str]]:
    return isinstance(seq[0], str)


def example2(thing2: MutableSequence[str | tuple[str, object]]):
    if _is_mut_sequence_of_str(thing2):
        reveal_type(thing2)  # Type of "thing2" is "<subclass of MutableSequence and MutableSequence>"
        # Again, doesn't make sense to me. Expected "MutableSequence[str]".
    else:
        reveal_type(thing2)  # Type of "thing2" is "MutableSequence[str | tuple[str, object]]"
        # Again, doesn't take into account narrowing from being in this branch. Expected "MutableSequence[tuple[str, object]]".
```

**VS Code extension or command-line**
This was replicated in VSCode via Pylance, version 2024.6.1.

**Comment by erictraut** [comment] 2024-06-10 01:32
These are invalid uses of `TypeIs`. The `TypeIs` form requires that the narrowed type is a subtype of the pre-narrowed type. In both of your examples, this condition isn't met. The type `list[str]` is not a subtype of `list[str | tuple[str, object]]`. 

If you enable basic type checking diagnostics, you will observe that pyright displays errors about your usage of `TypeIs`. 

The `TypeGuard` form allows you to specify a narrowed type that is not a subtype of the pre-narrowed type, but this is technically unsafe from a type perspective.

In any case, this is not a bug in pyright, so I'm closing the issue.

**Closed** 2024-06-10 01:32 UTC
Labels: bug, as designed

**Comment by Sachaa-Thanasius** [comment] 2024-06-10 12:06
Interesting. I feel like this behavior is disputable, but if I choose to pursue that, it'll be later. For now, I'll just note that I set pyright on strict mode, but Pylance didn't actually point out that this TypeIs usage is invalid. I'll see if there's a bug in my setup.

**Comment by DiscordLiz** [comment] 2024-06-10 14:57
Neither the consistency nor the subtyping rule would actually be type safe. I think the consistency rule is correct, and this falls under users writing potentially unsafe TypeIs functions and that TYpeIs would be unsafe in concurrent access situations.

Here's an example that type checks fine by using sequence, but will error at runtime.

Code sample in [pyright playground](https://pyright-play.net/?code=JYWwDg9gTgLgBAQwM4E8B2BjYECwAoAMyghDhhTGDQHM5RJY4BlAUwEcBXFzF-IkshSrUA%2BiwAeMbkmxokdcNHgAVCiwCSSfPgwAbZPICCALjhwwBnfqTyAQgApDASmP4zZgCYsCcESKrAMH72SCy6BAA0cByhIhgQHGgwplTwALxwAAwubu55oeEAdDEscQlJcBklZYkw2nhePsBIIqFsIgBG9uKmrJzcGCxOcAC0AHxwqmAaSADafVw8s7YAuiuueHlQLDAcUGiIurr2zVRIMAg8J1G2wwTQdHQH4k71yOgYcI1kCADWLC02t1euxFoNZoYVjlNu5gE1AexOt1oXk8ggAO4IQKIVCYbCFJC6FgsMD2ACM2VyqOioSg8gySA4IBOxVi8VqcHuUEeVDgLzeuM%2B3wu-xaumaMGBcHF5whUI2eXSOI%2B%2BIw2wQUhEFyQv3sIoBrXYyNeMLMGKx8HeeIgBKJJPJJry4kKCDA0zQHkc9icTiAA)

```python
import asyncio
from typing import Sequence
from typing_extensions import TypeIs

class A:  pass
class B(A):
    def __init__(self, use_count: int = 0):
        self.use_count = use_count

def is_seq_b(x: Sequence) -> TypeIs[Sequence[B]]:
    return all(isinstance(i, B) for i in x)

async def takes_seq(x: Sequence[A]):
    if is_seq_b(x):
        await asyncio.sleep(10)
        users = sum(i.use_count for i in x)

async def takes_list(x: list[A]):
    t = asyncio.create_task(takes_seq(x))
    await asyncio.sleep(1)
    x.append(A())
```
