### ISSUE TITLE
high cpu comsumption when pyright enabled

### ISSUE THREAD

**Issue by vec20** [microsoft/pyright#128] opened 2019-05-18 03:45 UTC
- pyright version: `1.0.28`
- vscode version: `1.34.0`
- os version: `windows 7`

CPU %	Memory (MB)	pid	Name
1	124	26596	code main
0	66	20076	     shared-process
0	152	20560	     window
0	207	23940	     window (Running Extensions - Visual Studio Code [Administrator])
0	109	5740	         extensionHost
13	125	23256	             electron_node server.js 
0	116	25884	     gpu-process
0	57	27148	     window (Process Explorer)

[CPU-20190518T034059.896Z.cpuprofile.txt](https://github.com/microsoft/pyright/files/3193622/CPU-20190518T034059.896Z.cpuprofile.txt)

**Comment by erictraut** [comment] 2019-05-18 03:51
I'll need more information to diagnose what you're seeing.
1. Does the high CPU consumption continue for a long time (more than 30 sec after opening a project)?
2. Do you see the progress spinner at the bottom of the VS Code status window? It should show how many files are left to analyze. Does this file count decrease, or does it appear to be "stuck"?
3. How many python source files are in your project?
4. If you install and run the command-line version of pyright, you can specify a "--verbose" option which will print detailed timing stats. Installation instructions for the command-line version can be found on the [pyright GitHub site](https://github.com/microsoft/pyright#installation).
Thanks for the additional information.

**Comment by vec20** [comment] 2019-05-18 04:33
1. Yes. CPU's single core starts to run at 100% all day long when I open single .py file, even empty one.
2. No. 
![0](https://user-images.githubusercontent.com/50211469/57964493-448f0600-7971-11e9-98fe-8bcbaf14480a.png)
![1](https://user-images.githubusercontent.com/50211469/57964496-48bb2380-7971-11e9-9f43-ba102682d798.png)
3. One.
4. I tried command-line version. I think the command-line version runs without any problem.

**Comment by erictraut** [comment] 2019-05-18 04:44
Thanks for the additional information. This is the first I've heard of this behavior, and I'd like to figure out the cause.

Could you go tot he OUTPUT tab and choose the Pyright output view, and see what logged information is shown? It should start with something like "Pyright language server starting".

**Comment by vec20** [comment] 2019-05-18 04:56
1. OUTPUT tab:
![3](https://user-images.githubusercontent.com/50211469/57964688-5e7e1800-7974-11e9-85a3-24b7412bd6a3.png)
2. ugh while running some 'problems' appeared.
It looks like pyright is processing some files background?
The `\HashiCorp\Vagrant\embedded\mingw\bin\lib` is located at `C:\HashiCorp\Vagrant\embedded\mingw\bin\lib`.
I have never opened that directory/files. I have no idea why the files are being processed...
![2](https://user-images.githubusercontent.com/50211469/57964706-b583ed00-7974-11e9-97c4-ce62ec73dce4.png)

**Comment by vec20** [comment] 2019-05-18 04:58
OUTPUT tab -> pyright log is attahced.
[output_pyright.txt](https://github.com/microsoft/pyright/files/3193666/output_pyright.txt)

**Comment by erictraut** [comment] 2019-05-18 05:04
Pyright normally scans for python files anywhere beneath the root directory of your project (the folder you opened in VS Code). I suspect that it's somehow using the root of your drive instead. That would explain the high CPU utilization and why you're seeing errors in files that you don't expect.

This could be Windows-specific behavior. I'll dust off my Windows machine and see if I can repro the problem.

Here's a possible workaround. Try adding a "pyrightconfig.json" file to the root of your project.

**Comment by vec20** [comment] 2019-05-18 05:13
I added a "pyrightconfig.json" file and it looks like the problem is solved, thanks!

**Comment by erictraut** [comment] 2019-05-18 05:14
OK, that's a great clue. I should have enough to repro the problem now.

**Comment by vec20** [comment] 2019-05-18 05:55
I tried out a few cases (open as folder/single file, or `pyrightconfig.json` exists/not exists)...
I suspect the problem occurs only when the .py is opened as single file (not as an entry of opened folder), regardless of whether the `pyrightconfig.json` file exists or not.

**Comment by erictraut** [comment] 2019-05-18 08:08
Thanks for the bug report. This is now fixed in 1.0.29, which I just published. If you still see a problem, please re-open the bug.

**Closed by erictraut** 2019-05-18 08:08 UTC
Labels: bug, fixed in next version

**Comment by kaar** [comment] 2021-11-22 12:48
I just experiences the same same issue running with 100% CPU and total lock of nvim in my case.
pyright 1.1.189
NVIM v0.6.0-dev+493-g035d82e0d

Workaround with adding an empty `pyrightconfig.json` worked for me.

**Comment by mmngreco** [comment] 2021-12-16 06:35
I have similar problems. @kaar can I ask you about the content of `pyrightconfig.json` ?

**Comment by kaar** [comment] 2021-12-16 08:04
> I have similar problems. @kaar can I ask you about the content of `pyrightconfig.json` ? 
> 
> 
> 
> Update:
> 
> 
> 
> In the [docs there's a sample `pyrightconfig.json`](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-config-file) file.

I had no content at all. Just put an empty file. I've not ran into the issue in a while now. Had this issue with neovim 0.5 and lsp pyright but has after this also upgraded nvim to 0.7 so no longer sure I can reproduce the issue.

**Comment by pogopaule** [comment] 2022-02-14 15:42
Same here, using pyright with neovim LSP. Adding pyrightconfig.json fixes the problem, otherwise I got one core at 100%.

**Comment by ristillu** [comment] 2022-03-25 10:25
I have 100% CPU. Neovim LSP. Neovim version 0.7.0 build 1319. I have always had a pyrightconfig.json. I can't say if the issue was present before, I just noticed today. Lucky I've got 12 cores. It might be because we've got ~3200 python files in the repo.

Emptying my pyrightconfig.json doesn't reduce CPU usage.

**Comment by kaar** [comment] 2022-03-25 10:48
> Emptying my pyrightconfig.json doesn't reduce CPU usage.

To clarify it was the existence of the file that made a difference and not its content.

**Comment by ristillu** [comment] 2022-03-25 11:22
Thanks kaar, acknowledged.

**Comment by jandvanegas** [comment] 2022-08-18 11:11
For people using pyright with neovim LSP, setting `diagnosticMode = "openFilesOnly"` in the configuration solved the issue for me. Of course, that if you just want feedback in open files.

**Comment by AXGKl** [comment] 2022-10-02 00:37
Had 100% CPU when opening a file within venvs outside of my project root. 
Solution: `cd $HOME; touch pyrightconfig.json` (i.e. an empty pyright config file in the home folder)

**Comment by yudhiesh** [comment] 2022-10-03 01:11
> I have 100% CPU. Neovim LSP. Neovim version 0.7.0 build 1319. I have always had a pyrightconfig.json. I can't say if the issue was present before, I just noticed today. Lucky I've got 12 cores. It might be because we've got ~3200 python files in the repo.
> 
> Emptying my pyrightconfig.json doesn't reduce CPU usage.

Did you manage to find a fix? I am facing the same issue.

**Comment by erictraut** [comment] 2022-10-03 01:29
This issue has been fixed and closed for over three years. If you are experiencing a problem that you would like to report, please open a new bug report and provide logs and/or repro instructions.

I'm going to lock this issue to prevent further posts.
