### ISSUE TITLE
`--watch` flag no longer watches as of version `1.1.236`.

### ISSUE THREAD

**Issue by Axelancerr** [microsoft/pyright#3341] opened 2022-04-13 22:38 UTC
**Describe the bug**
The `--watch` flag no longer reruns type checking when making changes to files.

**To Reproduce**
1. Run `npm -g install pyright@1.1.236`
2. Run `pyright --watch`

**Expected behavior**
I expect pyright to rerun when making changes to files.

**Screenshots or Code**
![Wednesday 13 April 2022 at 23-36 chrome Limited](https://user-images.githubusercontent.com/26942107/163281330-90f0c28e-d97c-44fb-8d9b-88020d38b383.gif)
(File was saved)

**VS Code extension or command-line**
CLI pyright 1.1.236+ on Windows 11

**Comment by erictraut** [comment] 2022-04-13 22:41
@heejaechang, this regression is caused by your recent removal of the file watcher. Could you please investigate and provide a fix?

**Comment by heejaechang** [comment] 2022-04-15 02:40
This will be fixed in the next release.

**Comment by erictraut** [comment] 2022-04-16 05:56
This is fixed in pyright 1.1.238, which I just published.

**Closed by erictraut** 2022-04-16 05:56 UTC
Labels: bug, addressed in next version
