### ISSUE TITLE
More equivalency between `Callable` TypeAlias and callback `Protocol`

### ISSUE THREAD

**Issue by Drino** [microsoft/pyright#3803] opened 2022-08-07 16:58 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to type hint a lot of decorator factories. So, I've started with writing a type for a decorator. 

There are two approaches to do so - one is via `typing.Callable` and another is `typing.Protocol`. According to [PEP-544](https://peps.python.org/pep-0544/#callback-protocols): 
>Callback protocols and Callable[...] types can be used interchangeably.

There are two ways of writing `Protocol` for a decorator:
1. `PDecorator` which has type variables in its `__call__` method
2. `PGenericDecorator[TCallable]` which has a class-scope type variable

There is a code snippet with all the approaches (tested in Pylance v2022.8.10):

```python
from typing import Any, Callable, Protocol, TypeAlias, TypeVar
from typing_extensions import reveal_type

TCallable = TypeVar('TCallable', bound=Callable[..., Any])

TDecorator: TypeAlias = Callable[[TCallable], TCallable]

class PDecorator(Protocol):
    def __call__(self, _: TCallable) -> TCallable:
        ...

class PGenericDecorator(Protocol[TCallable]):
    def __call__(self, _: TCallable) -> TCallable:
        ...

def factory_with_unbound_type_alias() -> TDecorator:
    ...

def factory_with_bound_type_alias() -> TDecorator[TCallable]:
    ...

def factory_with_protocol() -> PDecorator:
    ...

def factory_with_unbound_generic_protocol() -> PGenericDecorator:
    ...

# NOTE: TypeVar "TCallable" appears only once in generic function signature
def factory_with_bound_generic_protocol() -> PGenericDecorator[TCallable]:
    ...

def some_function(request: Any) -> str:
    return 'Hello world'

reveal_type(factory_with_unbound_type_alias()(some_function)) # Type of "factory_with_unbound_type_alias()(some_function)" is "Unknown"
reveal_type(factory_with_bound_type_alias()(some_function)) # Type of "factory_with_bound_type_alias()(some_function)" is "(request: Any) -> str"
reveal_type(factory_with_protocol()(some_function)) # Type of "factory_with_protocol()(some_function)" is "(request: Any) -> str"
reveal_type(factory_with_unbound_generic_protocol()(some_function)) # Type of "factory_with_unbound_generic_protocol()(some_function)" is "Unknown"
reveal_type(factory_with_bound_generic_protocol()(some_function)) # Type of "factory_with_bound_generic_protocol()(some_function)" is "Unknown"
```
So, it seems like there are two working ways to type hint decorator factory:
1. Use bound generic `Callable` like `-> TDecorator[TCallable]`
2. Use non-generic `Protocol` with generic `__call__` method: `-> PDecorator`

Though this behavior is understandable it feels a bit messy. `Protocol`-based and `Callable`-based solutions are rather different. It is possible to use `TCallable` only once in generic function signature, but only if passed as an argument to `Callable`-based `TypeAlias`.

**Describe the solution you'd like**
If `Callable` or `Callable`-based type alias used in type annotation has an unbound type variable - assume that this type variable is call-scoped instead of being `Unknown`. 

This will make `TDecorator` equivalent to `PDecorator`. 

It is tempting to say that `TDecorator[TCallable]` should be equivalent to `PGenericDecorator[TCallable]`, but this seems to break backwards compatibility (and probably explicit `-> Callable[[TCallable], TCallable]` annotation). 

**Additional context**
It's probably worth mentioning that specifying explicit return type of course works like a charm:
```python
def explicit_factory() -> Callable[[TCallable], TCallable]:
    ...

reveal_type(explicit_factory()(some_function)) # Type of "explicit_factory()(some_function)" is "(request: Any) -> str"
```

**Comment by erictraut** [comment] 2022-08-07 21:58
If I understand your proposal correctly, you're suggesting a change to the way generic type aliases work within the Python type system. If you want to make such a change, the pyright issue tracker is not the right place to have this discussion. If you want to pursue changes to the typing standard, you should start a discussion in the [python/typing discussion forum](https://github.com/python/typing/discussions).

Your proposed change would likely have backward compatibility implications for existing code bases, and that will make it difficult to convince the broader typing community to adopt such a change.

I'm going to close this issue for now because Pyright is working as intended here and is conforming to the way generic type aliases are currently behave according to the typing standard.

**Closed by erictraut** 2022-08-07 21:58 UTC
Labels: enhancement request
