### ISSUE TITLE
type narrowing fails for tagged unions of tuples discriminated over `bool`

### ISSUE THREAD

**Issue by lmmarsano** [microsoft/pyright#1668] opened 2021-03-20 21:51 UTC
**Describe the bug**
Is this a bug? Narrower types aren't inferred when tests resolve a discriminated union of boolean-tagged tuples.

**To Reproduce**
Save the provided code as `stub.py` & run the CLI.

**Expected behavior**
The type signature for the function should resolve as given without errors.

**Screenshots or Code**
```python
import typing as T
_V = T.TypeVar('_V')
Tagged = T.Union[
	tuple[T.Literal[False], _V],
	tuple[T.Literal[True], BaseException]
]
def value_or_raise(x: Tagged[_V]) -> _V:
	if x[0]:
		raise x[1]
	else:
		return x[1]
```

**VS Code extension or command-line**
```shellsession
$ pnpx pyright stub.py --outputjson
```
```json
{
    "version": "1.1.123",
    "time": "1616276801043",
    "diagnostics": [
        {
            "file": "/home/LOM0227/project/ALM.OnRampSecrets/stub.py",
            "severity": "error",
            "message": "Invalid exception class or object\n  \"_V@value_or_raise\" does not derive from BaseException",
            "range": {
                "start": {
                    "line": 8,
                    "character": 8
                },
                "end": {
                    "line": 8,
                    "character": 12
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/home/LOM0227/project/ALM.OnRampSecrets/stub.py",
            "severity": "error",
            "message": "Expression of type \"_V@value_or_raise | BaseException\" cannot be assigned to return type \"_V@value_or_raise\"\n  Type \"_V@value_or_raise | BaseException\" cannot be assigned to type \"_V@value_or_raise\"",
            "range": {
                "start": {
                    "line": 10,
                    "character": 9
                },
                "end": {
                    "line": 10,
                    "character": 13
                }
            },
            "rule": "reportGeneralTypeIssues"
        }
    ],
    "summary": {
        "filesAnalyzed": 14,
        "errorCount": 2,
        "warningCount": 0,
        "informationCount": 0,
        "timeInSec": 0.251
    }
}
```

**Comment by erictraut** [comment] 2021-03-20 22:21
Thanks for the feature request.

Here are the documented patterns and cases where pyright applies type narrowing for conditional type guards: https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-guards. Pyright already supports more type narrowing patterns and cases than any other Python type checker, to the best of my knowledge.

I occasionally receive requests for adding support for more patterns or cases, but every one of these adds complexity to the type checker code and affects runtime analysis performance. This one, in particular, would likely have a measurable impact on performance because it involves the narrowing of the type of one expression `x` based on a check of another expression `x[0]`. The standard type narrowing code flow logic looks for an exact match of the expression pattern within the conditional expression.

I'm willing to add support for more type narrowing patterns and cases if 1) it's a pattern that's already supported by another type checker like mypy (which is evidence that the maintainers of other type checkers thought it was a worthwhile capability), or 2) it's a pattern or case that is likely to be useful to a wide number of users. I confirmed that mypy also doesn't handle this case, and I don't think this suggestion meets the second criterion. I could be convinced to reconsider if enough other pyright users submit a similar request or upvote this issue, but for now I'm going to close this request.

**Closed by erictraut** 2021-03-20 22:22 UTC

**Comment by lmmarsano** [comment] 2021-03-21 23:07
> 1) it's a pattern that's already supported by another type checker like mypy (which is evidence that the maintainers of other type checkers thought it was a worthwhile capability), or

Not sure if true, but [mypy _claims_ to support `x[L0] == L1` subscription type guards](https://mypy.readthedocs.io/en/stable/literal_types.html#tagged-unions).
> Instead, what you can do is label or tag your TypedDicts with a distinct Literal type. Then, you can discriminate between each kind of TypedDict by checking the label

This same section also says
> you can also use the same technique with regular objects, tuples, or namedtuples

contrary to observation. 🤷
