### ISSUE TITLE
feature request: `reportGeneralTypeIssues` is too broad of a setting, split it?

### ISSUE THREAD

**Issue by ankush** [microsoft/pyright#2026] opened 2021-06-23 10:00 UTC
**Is your feature request related to a problem? Please describe.**
Consider dynamically defined objects. Pyright complains about "cannot access member" everywhere dynamically defined objects are used. There's is way to disable this particular error without disabling "general type issues" which are still useful in other places.

**Describe the solution you'd like**
`reportGeneralTypeIssues` should be broken down into several categories of issues and each should be configurable individually.

**Comment by erictraut** [comment] 2021-06-23 14:59
We have split out individual diagnostics into separate rules in the past, so there is precedent for this. However, we would need specific examples for consideration. I'm not sure what you mean by "dynamically defined objects". That could mean a bunch of different things. Please provide specific examples with code snippets if possible.

**Comment by erictraut** [comment] 2021-06-26 01:00
This feature request is too vague, so I'm going to close it. If you have specific classes of errors that you would like to see split off from `reportGeneralTypeIssues` or you have specific situations where you would like advice about how to deal with error conditions, please file a separate feature request or start a thread in the discussions tab.

**Closed by erictraut** 2021-06-26 01:00 UTC
Labels: question

**Comment by omegahh** [comment] 2021-07-08 03:18
I have same question about it. so does it happen in python official codes (for example: /usr/lib/python3.9/codecs.py, see screenshot below). I have no idea that it's truly a potential error or not and how to fix it.

![codecs_pyright](https://user-images.githubusercontent.com/5026687/124857030-2582e080-dfde-11eb-8290-568c4307ac65.png)

**Comment by JelleZijlstra** [comment] 2021-07-09 00:19
@omegahh The standard library isn't typechecked with pyright and you shouldn't expect it to show no errors. That particular one looks like a false positive.

**Comment by erictraut** [comment] 2021-07-09 02:30
@omegahh, this is a duplicate of https://github.com/microsoft/pylance-release/issues/573. Implicit declaration of instance variables from within a `__new__` method is not supported. We currently have no plans to support this because it's not a typical use case. Instance variables should be assigned in `__init__` since that's its intended use.
