### ISSUE TITLE
When configuring using `pyproject.toml`, `useLibraryCodeForTypes` still defaults to false. 

### ISSUE THREAD

**Issue by mmohaveri** [microsoft/pyright#5044] opened 2023-05-01 11:04 UTC
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
`pyrigh 1.1.303` release notes says that `useLibraryCodeForTypes`'s default has changed from False to True and consequently has removed support for `--lib` CLI option. 

But my in my experience, until I explicitly added `useLibraryCodeForTypes = true` to my `pyproject.toml` file, pyright was ignoring the `--lib` CLI option while not trying to infer types from library code.

**To Reproduce**
Install pyright 1.1.303, 304, or 305, add your pyright configuration using `pyproject.toml`, add use a library in your code that does not have type stubs and required `--lib` option in the past, run pyright on you code.

In my exprience, it resulted in a lot of Unknown type errors, which are caused due to the fact that pyright was not reading the library code (just like if I set `useLibraryCodeForTypes` to false).

**Expected behavior**
If the `--lib` has been removed and `useLibraryCodeForTypes = true` has become the default, it should also be the default if you're configuring pyright using pyproject.toml file as well.

**VS Code extension or command-line**
Running pyrihg in CLI, tested with versions 1.1.303 to 305. Keep in mind that the same setup works for versions bellow 1.1.303, and the problem only accrues as soon as I upgrade pyright to 303 or higher.

**Comment by erictraut** [comment] 2023-05-01 15:01
This is a duplicate of https://github.com/microsoft/pyright/issues/5029.

**Closed by erictraut** 2023-05-01 15:01 UTC

**Comment by mmohaveri** [comment] 2023-05-02 13:07
@erictraut So sorry. I searched the issue tracker for similar issues, but somehow I had missed it.
