### ISSUE TITLE
`Error: Debug Failure. False expression.` occurring using `transformers.Trainer`

### ISSUE THREAD

**Issue by lukasberglund** [microsoft/pyright#5154] opened 2023-05-23 00:23 UTC
**Describe the bug**
I have pyright installed through poetry. When I run `poetry run pyright file.py` on this and other pieces of python code that involve the huggingface `transformers.Trainer` class, I get the error `Error: Debug Failure. False expression.`

Here is the full trace:

```
An internal error occurred while type checking file "/Users/lukasberglund/Code/situational-awareness/file.py": Error: Debug Failure. False expression.
    at a.lock (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeVarContext.ts:372:9)
    at validateFunctionArgumentTypes (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10449:28)
    at validateFunctionArgumentTypesWithContext (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at s.validateCallArguments [as timeOperation] (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateNewMethod (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:317:19)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
    at s.useSpeculativeMode [as timeOperation] (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateConstructorArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14513:39)
    at evaluateTypesForStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18254:25)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19866:17)
    at evaluateTypeForSubnode (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
    at getInferredTypeOfDeclaration (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19865:32)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20182:36)
    at Array.forEach (<anonymous>)
    at getEffectiveTypeOfSymbolForUsage (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20126:15)
    at getTypeOfName (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4157:43)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:943:30)
    at validateArgType (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10996:40)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10460:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10459:32)
    at validateFunctionArgumentTypesWithContext (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14513:39)
    at evaluateTypesForStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18254:25)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19866:17)
    at evaluateTypeForSubnode (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
    at getInferredTypeOfDeclaration (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19865:32)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20182:36)
    at Array.forEach (<anonymous>)
    at getEffectiveTypeOfSymbolForUsage (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20126:15)
    at getTypeOfName (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4157:43)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:943:30)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17141:66)
    at Array.forEach (<anonymous>)
    at inferFunctionReturnType (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17138:59)
    at disableSpeculativeMode (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20459:48)
    at getFunctionInferredReturnType (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20458:25)
    at xs (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20407:20)
Error performing analysis: Error: Debug Failure. False expression.
    at a.lock (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeVarContext.ts:372:9)
    at validateFunctionArgumentTypes (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10449:28)
    at validateFunctionArgumentTypesWithContext (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at s.validateCallArguments [as timeOperation] (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateNewMethod (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:317:19)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19120:20)
    at s.useSpeculativeMode [as timeOperation] (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateConstructorArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14513:39)
    at evaluateTypesForStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18254:25)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19866:17)
    at evaluateTypeForSubnode (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
    at getInferredTypeOfDeclaration (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19865:32)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20182:36)
    at Array.forEach (<anonymous>)
    at getEffectiveTypeOfSymbolForUsage (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20126:15)
    at getTypeOfName (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4157:43)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:943:30)
    at validateArgType (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10996:40)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10460:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10459:32)
    at validateFunctionArgumentTypesWithContext (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14513:39)
    at evaluateTypesForStatement (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18254:25)
    at callback (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19866:17)
    at evaluateTypeForSubnode (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
    at getInferredTypeOfDeclaration (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19865:32)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20182:36)
    at Array.forEach (<anonymous>)
    at getEffectiveTypeOfSymbolForUsage (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20126:15)
    at getTypeOfName (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4157:43)
    at getTypeOfExpression (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:943:30)
    at forEach (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17141:66)
    at Array.forEach (<anonymous>)
    at inferFunctionReturnType (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17138:59)
    at disableSpeculativeMode (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20459:48)
    at getFunctionInferredReturnType (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20458:25)
    at xs (/Users/lukasberglund/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20407:20)
```

**To Reproduce**
Create a file called `file.py`. Add the following code snippet to it:
```python
from transformers import Trainer

def safe_save_model_for_hf_trainer(trainer: Trainer, output_dir: str, save_optimizer: bool = False):
    """Collects the state dict and dump to disk."""
    if trainer.deepspeed is not None and save_optimizer:
        trainer.deepspeed.save_checkpoint(output_dir)
    trainer.save_model(output_dir)
```

Create a pyproject.toml file with the following code:
```
[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors=[]

[tool.poetry.dependencies]
scipy = "^1.9.2"
python = "~=3.10.0"
python-dotenv = "^0.19.2"
numpy = "^1.14.5"
matplotlib = "^3.7.1"
openai = "^0.27.0"
tenacity = "^8.1.0"
autopep8 = "^2.0.1"
levenshtein = "^0.20.9"
datasets = "2.11.0"
diskcache = "^5.4.0"
wandb = "^0.13.9"
termcolor = "^2.2.0"
humanize = "^4.6.0"
prettytable = "^3.6.0"
jsonlines = "^3.1.0"
transformers = "4.28"
torch = "2"
pandas = "^1.5.3"
accelerate = "^0.16.0"
emoji = "^2.2.0"
langdetect = "^1.0.9"
pytest = "^7.2.2"
rouge-score = "^0.1.2"
nltk = "^3.8.1"
absl-py = "^1.4.0"
debugpy = "^1.6.6"
tiktoken = "^0.3.3"
deepspeed = "^0.8.3"
sentencepiece = "^0.1.97"
textstat = "^0.7.3"
pre-commit = "^3.2.2"
poetry = "^1.4.2"
pyright = "1.1.309"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
poethepoet = "^0.13.0"

[tool.autopep8]
max_line_length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.10"
exclude = ["wandb", "cache"]
```
Run `poetry install` and then `poetry run pyright file.py`.

**Expected behavior**
Pyright lists all type errors if there are any.

**VS Code extension or command-line**
I'm using `pyright 1.1.309` from the command line.

**Comment by erictraut** [comment] 2023-05-23 01:34
Thanks for the bug report. This is a duplicate of https://github.com/microsoft/pyright/issues/5129. A fix has been checked in, and it will be addressed in tomorrow's weekly release of pyright.

**Closed by erictraut** 2023-05-23 01:34 UTC
