### ISSUE TITLE
Something in hover provider broke in a commit released in 1.1.333

### ISSUE THREAD

**Issue by kfreezen** [microsoft/pyright#6465] opened 2023-11-16 06:39 UTC
Hover suggestion just shows "loading" when I hit Ctrl+Space in a custom Monaco setup.

Expected behavior: Should show something, whether a keyword, or a name, or something similar.

Bug Screenshot
<img width="256" alt="image" src="https://github.com/microsoft/pyright/assets/346924/37a7e990-3585-440b-98f0-18b7b19f2b93">

The bug seems to occur on 1.1.333 and after.

So, I decided to set up a development instance of pyright, and integrate it into my custom Monaco setup. After some digging I've concluded that the offending commit is `* cfe56bfb3 pull-pylance-with-pyright-1.1.332 (#6195)`

I've been trying to track down the offending changes in the above commit, but I've been coming up short.
edit: I think the offending changes are in `packages/pyright-internal/src/common/pathUtils.ts`

Any additional information I can get for you, let me know. Thanks!

**Comment by kfreezen** [comment] 2023-11-16 06:53
After some more tracking down, I think the file with the offending changes is `packages/pyright-internal/src/common/pathUtils.ts`

**Comment by erictraut** [comment] 2023-11-16 07:28
@kfreezen, there was a regression introduced in 1.1.333, but we think it has been addressed in subsequent versions. Have you tried the latest release (1.1.336)? Are you still able to repro the problem?

I'm curious what led you to the code in `pathUtils.ts`? Do you have a stack trace?

I wonder if this is the same issue as #6314.

@debonte, @rchiodo, thoughts?

**Comment by kfreezen** [comment] 2023-11-16 15:08
@erictraut the release we were on when we discovered the problem was 1.1.336. After downgrading to 1.1.330, the problem went away.

I have no stack trace, all I did was brute force build/test/build/test over and over again to see which builds had the problem and which didn't. Very tedious.

As far as I can tell, my process has no error traceback for anything. I assumed that my process is echoing pyright-langserver's stderr, but now I'm wondering whether that's the case.

I will see if I can get that stderr echo figured out, and then get back to you with any updates I have. I'm pretty sure my code should be bubbling up any error reports from sub-processes if it isn't.

**Comment by rchiodo** [comment] 2023-11-16 17:34
We had a similar hang yesterday when we imported pyright into Pylance prior to shipping last night. I think the root cause is this code here when parsing non file URIs:

https://github.com/microsoft/pyright/blob/9709a5b7ebedab02cc8cb7ec1cd29dcdb672139d/packages/pyright-internal/src/analyzer/importResolver.ts#L2676

The `isDiskPathRoot` function will return false on something like `untitled:/`, but then the combinePaths call will return the same `untitled:/` path and so it goes around in an infinite loop.

We made a temporary fix in Pylance for this, I can port that to pyright. We shouldn't have this issue when we switch to storing URIs everywhere instead of file paths.

**Comment by rchiodo** [comment] 2023-11-16 17:38
Here's a PR for the temporary workaround:
https://github.com/microsoft/pyright/pull/6477

**Comment by kfreezen** [comment] 2023-11-16 20:50
Just tested our configuration out with the latest `main` and can confirm that the bug is fixed. Thank you guys for your quick response.

**Comment by rchiodo** [comment] 2023-11-16 20:59
Sorry didn't mean to close this.

**Comment by rchiodo** [comment] 2023-11-16 21:00
I believe Eric closes these when he ships the next version.

**Comment by erictraut** [comment] 2023-11-22 03:24
This is addressed in pyright 1.1.337, which I just published. It will also be included in a future release of pylance.

**Closed by erictraut** 2023-11-22 03:24 UTC
Labels: bug, addressed in next version
