### ISSUE TITLE
Support setting `venv` setting in addition to `venvPath` from workspace config`

### ISSUE THREAD

**Issue by tanj** [microsoft/pyright#5109] opened 2023-05-13 16:47 UTC
**Is your feature request related to a problem? Please describe.**
When trying to set `venv` from workspace config it is not possible to set.

**Describe the solution you'd like**
To be able to set up the complete virtual environment from workspace config. That is, set both `venvPath` and `venv` in my workspace config.

**Additional context**
https://github.com/microsoft/pyright/blob/c51bb4b7466ec009f7b2b2dccad246d6defadeaa/packages/pyright-internal/src/server.ts#L92-L111

**Comment by erictraut** [comment] 2023-05-13 17:03
The `venvPath` / `venv` mechanism was designed to be used in cases where the `venvPath` differs on each developer's machine but they all agree on a common `venv` name. That way, you can check in a config file that refers to the `venv` and allow each developer to specify a custom `venvpath` on the command line or in their LSP settings.

It sounds like you're using `venvPath` and `venv` in a manner in which they were not designed. Can you explain more about what you're trying to do?

Very few pyright users actually use `venvPath` and `venv`. The standard way to specify the Python environment in pyright is to use either the `python.pythonPath` LSP setting (if you're using pyright as a language server) or by selecting the Python environment in the shell prior to invoking the pyright CLI (e.g. by using the `source` command to configure your venv). These are preferable to `venvPath` and `venv` because they leverage the Python interpreter to determine the import resolution paths for the environment. By contrast, the `venvPath` / `venv` mechanism requires pyright to determine these import resolution paths itself, and there are complex edge cases that it does not (and cannot) handle.

So my recommend is to avoid using the `venvPath` / `venv` mechanism and use one of the more common and robust mechanisms for specifying your Python environment.

**Comment by erictraut** [comment] 2023-05-13 17:05
BTW, I'm considering deprecating (and eventually removing) the `venvPath` / `venv` mechanism because of the problems and confusion it causes.

**Comment by AlexWaygood** [comment] 2023-05-13 18:28
FYI, we recently started using the `venvPath`/`venv` mechanism over at typeshed, so that we could run pyright in a more isolated environment in our CI: https://github.com/python/typeshed/pull/10121.

If I understand correctly, the alternative ways of specifying the Python environment that you mention wouldn't work for us (or other users of `pyright-action`).

**Comment by erictraut** [comment] 2023-05-13 21:18
@AlexWaygood, if I expose `pythonPath` (i.e. a path that specifies the path to the interpreter you want to use) as a command-line option, would that meet your needs for typeshed? I ask because I just received [this feature request](https://github.com/microsoft/pyright/issues/5111).

I think it would be preferable to use `pythonPath` than `venvPath` / `venv` for the reasons I mention above. The only reason that `venvPath` and `venv` make sense is if there's no way to invoke the python interpreter binary in your environment (e.g. you're running the analysis on a system that has no python interpreter installed, the installed binary is incompatible with your CPU, or you don't have permissions to execute the binary for some reason). Those cases should be extremely rare.

@tanj, would it solve your problem if I were to expose `pythonPath` from the command line?

**Comment by AlexWaygood** [comment] 2023-05-13 21:20
> @AlexWaygood, if I expose `pythonPath` (i.e. a path that specifies the path to the interpreter you want to use) as a command-line option, would that meet your needs for typeshed? I ask because I just received [this feature request](https://github.com/microsoft/pyright/issues/5111).

Yes -- and I think we'd actually like that a lot more, in fact! It would enable us to simplify our configuration over at typeshed.

**Comment by erictraut** [comment] 2023-05-13 23:22
@AlexWaygood, I've implemented the `--pythonpath` command-line option, which will be included in pyright 1.1.309.

I've also improved the documentation so it directs users away from the `venvPath`/`venv` mechanism toward one of the preferred mechanisms.

@tanj, let me know if that addresses your problem. I'd prefer not to invest more in the `venvPath`/`venv` mechanism because of the issues I mentioned above.

**Closed** 2023-05-16 15:13 UTC
Labels: enhancement request, question
