### ISSUE TITLE
Out of memory error under very specific circumstances

### ISSUE THREAD

**Issue by LeeeeT** [microsoft/pyright#8723] opened 2024-08-09 21:09 UTC
Starting with version 1.1.373, I am experiencing an out of memory error when using pyright to type check my project [felis](https://github.com/LeeeeT/felis). Here's the [workflow run](https://github.com/LeeeeT/felis/actions/runs/10165951692/job/28586377327). I tried to extract the minimal reproducible example as usual, but the best I was able to come up with is [this sample](https://github.com/LeeeeT/pyright_bug_sample). There's a lot of code consisting of several modules. If I touch a single line in any of these files the problem disappears.
I presume pyright is entering an infinite loop while checking [sample.function.add2](https://github.com/LeeeeT/pyright_bug_sample/blob/main/sample/function.py#L27) (when I was playing around with this code, pyright once revealed a very long type for this definition; and weirdly if I change some completely unrelated code in other modules, it somehow interferes pyright's behavior for the aforementioned line).
Yeah, I am relying heavily on the undocumented parts of pyright and maybe my code should in fact fail to type check (that's a different question) but I think you would agree that crashing with an OOM error is unsatisfactory anyway.
Please let me know if you need any additional details.

**Comment by erictraut** [comment] 2024-08-10 21:21
Thanks as always for the bug report and the great repro steps.

Your code definitely pushes the boundaries of what's possible with the Python type system. However, I don't see anything that you're doing here that relies on undocumented behaviors. And I agree that pyright should never hang regardless of what code it is fed.

I've narrowed down the problem to a specific commit, but I need to do further work to root cause the problem.

**Comment by LeeeeT** [comment] 2024-08-10 21:44
Thank you so much!

**Comment by erictraut** [comment] 2024-08-14 02:21
This is addressed in pyright 1.1.376.

**Closed by erictraut** 2024-08-14 02:21 UTC
Labels: bug, addressed in next version, regression
