### ISSUE TITLE
Use LSP's standard server-initiated progress scheme

### ISSUE THREAD

**Issue by rwols** [microsoft/pyright#1268] opened 2020-12-11 22:45 UTC
**Is your feature request related to a problem? Please describe.**
pyright may analyze a bunch of files when editing a file that's imported by a lot of other files. It currently uses three non-standard LSP notifications for this whose methods are named `pyright/beginProgress`, `pyright/reportProgress`, `pyright/endProgress`. Although there is probably some client glue code written for this in the VSCode client (indeed even for our ST [client](https://github.com/sublimelsp/LSP-pyright/blob/b92e4e8034ac3eb2ec3f540b936a85c273d0f3ed/plugin.py#L46-L58))

**Describe the solution you'd like**
It's probably better for the LSP ecosystem in the long run if this custom scheme were instead replaced by the standard [server initiated progress](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#serverInitiatedProgress) scheme of the LSP spec.

- `pyright/beginProgress` --> `window/workDoneProgress/create` + `$/progress` with kind `begin`
- `pyright/reportProgress` --> `$/progress` with kind `report`
- `pyright/endProgress` --> `$/progress` with kind `end`

**Comment by jakebailey** [comment] 2020-12-11 22:52
The main point of contention will be where VS Code puts its version of progress reports and what they look like as compared to the current UI we have for Python (which predates progress reporting as far as I know, and may work differently).

The APIs are also different in that you need to create a specific progress report and reference it, rather than just marking the start/middle/end, but that's not hard to do code wise. It does have implications for some automated benchmarks we run which use these progress notifications to know when to move onto the next part of the benchmark.

**Comment by erictraut** [comment] 2020-12-11 23:44
Thanks for the suggestion. I didn't realize there was a standard protocol for server-initiated progress reporting. Perhaps it was added since I first implemented this in pyright. In any case, I think this is a good suggestion and a nice simplification.

@jakebailey, here's a PR for your review: https://github.com/microsoft/pyright/pull/1269

I don't see any tests that relying on the old implementation. They all pass after my change.

I confirmed that visual behavior in VS Code is the same as before. No visible difference.

**Comment by jakebailey** [comment] 2020-12-12 00:02
There are no tests for this because we have no tests for the language server itself outside manual testing and benchmarking. This will definitely break the benchmarker, which relies on the current notification mechanism to know when it should move through its test suite. I'd prefer not to merge this until we have the time to adapt it for the benchmarker or add some option to enable the old behavior, otherwise the benchmarker will fail until it's fixed and we'll lose perf data from any changes after it.

**Comment by rwols** [comment] 2020-12-12 00:04
> which predates progress reporting in the LSP AFAIK, and may work differently

Yes, it's a relatively new set of requests and notifications, since 3.15 I believe.

**Comment by erictraut** [comment] 2020-12-12 00:08
OK, I'm fine putting this on hold. I'm in no hurry to merge this. I do think it's a worthwhile change though, so I'd like to incorporate it eventually.

**Comment by jakebailey** [comment] 2020-12-12 00:10
Yes, I definitely agree, I just know I can't test and fix it at the end of day on a Friday. 🙂

**Comment by jakebailey** [comment] 2020-12-14 23:14
Alright, I've merged a change that will use the window progress if the client has declared support for it in its capabilities. Otherwise, it'll use the old custom notifications. This'll be in the next release.

**Comment by erictraut** [comment] 2020-12-23 07:34
This is now addressed in Pyright 1.1.96, which I just published.

**Closed by erictraut** 2020-12-23 07:34 UTC
Labels: addressed in next version
