### ISSUE TITLE
Enhance highlighting for individual items which are wrong

### ISSUE THREAD

**Issue by michaeloliverx** [microsoft/pyright#3837] opened 2022-08-17 15:01 UTC
When something is incorrect inside a `TypedDict` the red squiggly line spans the entire object rather than the specific line that there is an issue.

Take the following two code snippets in Python and TypeScript:
```python
from typing import TypedDict


class Person(TypedDict):
    name: str
    age: int


person: Person = {
    "name": "Michael",
    "age": "not a number",
}

```

```typescript
type Person = {
    name: string;
    age: number;
};

const person: Person = {
    name: "Michael",
    age: "not a number",
};

```

This is what is looks like in VS Code:

![image](https://user-images.githubusercontent.com/55017335/185171516-28fa75a8-aee3-4323-a465-1d00fb8ede16.png)

Its harder to grok what the problem is in the Python version, especially when the it spans multiple lines.

---

The same behaviour is observed when using other data structures too, here is a list example:

![image](https://user-images.githubusercontent.com/55017335/185173328-61192af9-fa9d-42b8-9b63-133da9b08fd3.png)

**Comment by erictraut** [comment] 2022-08-20 01:18
I've figured out a reasonable mechanism to implement this, and I've implemented support for TypedDicts. Here's the commit: https://github.com/microsoft/pyright/commit/e4b41e1a30002a1fbb1c6ada7bd0ab529bc2627b.

I'm going to leave this issue open because I'd like to push through this same solution for list & set expressions, dictionary expressions assigned to `dict` (as opposed to a TypedDict), and tuple expressions.

**Comment by erictraut** [comment] 2022-08-31 06:11
I've extended this to support tuple, list, set, and dictionary expressions.

**Comment by erictraut** [comment] 2022-09-07 01:16
This is addressed in pyright 1.1.270, which I just published. It will also be included in a future release of pylance.

**Closed by erictraut** 2022-09-07 01:16 UTC
Labels: enhancement request, addressed in next version

**Comment by mardukbp** [comment] 2023-04-23 12:44
This issue hasn't been satisfactorily adressed. When there's more than one problem in a TypedDict, the whole dictionary gets a red squiggly.

![grafik](https://user-images.githubusercontent.com/1140106/233840244-d279fa84-fe59-49e4-98eb-0565e19b913e.png)

I have a large TypedDict that represents the spec of an API and Pyright's current behavior makes it impossible to know what changed.

**Comment by erictraut** [comment] 2023-04-23 16:57
This is working as designed. When you have multiple mismatches, the whole expression text range is used for the diagnostic. The alternative would be to emit a bunch of individual (redundant) error messages, which has a bunch of downsides. The current behavior (emitting a single error message and using the entire expression as the text range) is consistent with other language servers in other languages, like TypeScript, so we're unlikely to change this behavior. Pyright's error message will provide details about the individual fields that are incorrectly typed or missing, so if you read the error message, you can figure out what's wrong in your code.
