### ISSUE TITLE
Local Import Error Showing Up Unnecessarily 

### ISSUE THREAD

**Issue by diamondwyrm** [microsoft/pyright#6025] opened 2023-09-25 19:27 UTC
![image](https://github.com/microsoft/pyright/assets/10159098/a5e5c745-8b36-4ffa-ae30-d114813deb49)

My issue is basically, when I loaded up my code on the 21st to work on my code, I noticed that all of my local imports were showing up as unresolved. Attached is a simple example. Both .py files are in the same folder. below is the code in the other file. I have changed nothing from the day before, but everything just stopped showing up as imported. Note this only is an issue for local Imports, "Import random as r" works just fine.

Also, it is important to note that, despite showing up as unresolved, the program still functions without any issues; I run it and it outputs a random value between 1 and 6. I had installed no other extensions in this time nor changed any settings. I have tried uninstalling and reinstalling pylance. In addition, this lines up perfectly with when the new version came out, which is why I decided to issue a bug report. 

```
import random as r
def dice(amount=2,die=6):
    result = 0
    counter = 0
    while counter<amount:
        result+=r.randint(1,die)
        counter+=1
    return result
```

**VS Code extension or command-line**
Pylance in VS Code
Version: v2023.9.20

**Comment by rchiodo** [comment] 2023-09-25 19:40
This should be a dupe of https://github.com/microsoft/pylance-release/issues/4861, which should ship when we next release. The workaround is to open a folder instead of just raw files.

**Closed by rchiodo** 2023-09-25 19:40 UTC
Labels: bug
