### ISSUE TITLE
The Pyright 1.1.309 test throws an error when using tuple as an argument for the join function

### ISSUE THREAD

**Issue by ImNotVafel** [microsoft/pyright#5145] opened 2023-05-21 20:14 UTC
**Describe the bug**
The Pyright throws an error on using tuple as an argument for the join function.

<details>
<summary>Click here for see traceback</summary>

```
PS C:\Users\inv\Documents\inv> pyright .\test.py
An internal error occurred while type checking file "C:\Users\inv\Documents\inv\test.py": Error: Debug Failure. False expression.
    at a.lock (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeVarContext.ts:372:9)
    at validateFunctionArgumentTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10449:28)
    at validateFunctionArgumentTypesWithContext (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10222:20)
    at validateFunctionArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10702:16)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8666:48)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3653:39)
    at doForEachSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeUtils.ts:487:9)
    at expandSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3677:13)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8595:26)
    at s.validateCallArguments [as timeOperation] (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:40:20)
    at validateNewMethod (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\constructors.ts:317:19)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\constructors.ts:113:35)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:19120:20)
    at s.useSpeculativeMode [as timeOperation] (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:40:20)
    at validateConstructorArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\constructors.ts:108:15)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8966:55)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3653:39)
    at doForEachSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeUtils.ts:487:9)
    at expandSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3677:13)
    at validateCallArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8595:26)
    at getTypeOfCall (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7563:36)
    at getTypeOfExpression (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:958:30)
    at validateArgType (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10996:40)
    at forEach (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10460:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10459:32)
    at validateFunctionArgumentTypesWithContext (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10222:20)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8096:28)
    at useSpeculativeMode (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:19126:28)
    at validateOverloadsWithExpandedTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8095:36)
    at validateOverloadedFunctionArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8438:32)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8744:48)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3653:39)
    at doForEachSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeUtils.ts:487:9)
    at expandSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3677:13)
    at validateCallArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8595:26)
    at getTypeOfCall (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7563:36)
    at getTypeOfExpression (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:14513:39)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:18254:25)
    at s.evaluateTypesForStatement [as timeOperation] (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:40:20)
    at L.visitAssignment (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:1156:25)
    at L.visit (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:367:29)
    at L.visitNode (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:933:21)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:915:37)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:307:19)
    at forEach (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:924:22)
    at Array.forEach (<anonymous>)
    at L.walkMultiple (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:922:15)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:917:18)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:307:19)
    at L._walkStatementsAndReportUnreachable (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:2569:18)
    at L.check (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:286:14)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\sourceFile.ts:1057:29)
    at s.timeOperation (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:44:28)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\sourceFile.ts:1048:45)
    at t.LogTracker.log (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\logTracker.ts:45:20)
    at t.SourceFile.check (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\sourceFile.ts:1046:33)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\program.ts:1929:40)
    at t.LogTracker.log (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\logTracker.ts:45:20)
    at E._checkTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\program.ts:1870:33)
Error performing analysis: Error: Debug Failure. False expression.
    at a.lock (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeVarContext.ts:372:9)
    at validateFunctionArgumentTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10449:28)
    at validateFunctionArgumentTypesWithContext (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10222:20)
    at validateFunctionArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10702:16)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8666:48)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3653:39)
    at doForEachSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeUtils.ts:487:9)
    at expandSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3677:13)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8595:26)
    at s.validateCallArguments [as timeOperation] (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:40:20)
    at validateNewMethod (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\constructors.ts:317:19)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\constructors.ts:113:35)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:19120:20)
    at s.useSpeculativeMode [as timeOperation] (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:40:20)
    at validateConstructorArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\constructors.ts:108:15)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8966:55)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3653:39)
    at doForEachSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeUtils.ts:487:9)
    at expandSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3677:13)
    at validateCallArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8595:26)
    at getTypeOfCall (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7563:36)
    at getTypeOfExpression (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:958:30)
    at validateArgType (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10996:40)
    at forEach (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10460:31)
    at Array.forEach (<anonymous>)
    at validateFunctionArgumentTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10459:32)
    at validateFunctionArgumentTypesWithContext (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:10222:20)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8096:28)
    at useSpeculativeMode (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:19126:28)
    at validateOverloadsWithExpandedTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8095:36)
    at validateOverloadedFunctionArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8438:32)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8744:48)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3653:39)
    at doForEachSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeUtils.ts:487:9)
    at expandSubtype (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:3677:13)
    at validateCallArguments (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:8595:26)
    at getTypeOfCall (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:7563:36)
    at getTypeOfExpression (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:14513:39)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\typeEvaluator.ts:18254:25)
    at s.evaluateTypesForStatement [as timeOperation] (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:40:20)
    at L.visitAssignment (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:1156:25)
    at L.visit (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:367:29)
    at L.visitNode (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:933:21)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:915:37)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:307:19)
    at forEach (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:924:22)
    at Array.forEach (<anonymous>)
    at L.walkMultiple (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:922:15)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\parseTreeWalker.ts:917:18)
    at L.walk (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:307:19)
    at L._walkStatementsAndReportUnreachable (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:2569:18)
    at L.check (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\checker.ts:286:14)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\sourceFile.ts:1057:29)
    at s.timeOperation (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\timing.ts:44:28)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\sourceFile.ts:1048:45)
    at t.LogTracker.log (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\logTracker.ts:45:20)
    at t.SourceFile.check (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\sourceFile.ts:1046:33)
    at callback (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\program.ts:1929:40)
    at t.LogTracker.log (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\common\logTracker.ts:45:20)
    at E._checkTypes (C:\Users\inv\AppData\Roaming\npm\node_modules\pyright\dist\pyright-internal\src\analyzer\program.ts:1870:33)
```
</details>

**To Reproduce**
1. Create venv with python 3.10.6
2. Install pyright 1.1.309
3. Create file `test.py` with next code:
```python
# Works fine, but pyright throws error
a = "".join(tuple(str(i) for i in range(4)))
print(a)  # => '0123'

# Works fine
a = "".join((str(i) for i in range(4)))
print(a)  # => '0123'

# Also works fine
a = tuple(str(i) for i in range(4))
b = "".join(a)
print(b)  # => '0123'
```
4. Execute command `pyright test.py`

**Expected behavior**
No errors as a result of the command `pyright test.py `

**VS Code extension or command-line**
I came across this using the Pyright CLI, and nvim LSP.

**Additional context**
Nvim after trying to show the type of object `a`:
![image](https://github.com/microsoft/pyright/assets/82383581/c161f61b-f264-4ab6-a9e6-92b4bd518bab)

**Comment by erictraut** [comment] 2023-05-21 21:28
Yes, this is a duplicate of https://github.com/microsoft/pyright/issues/5129 and https://github.com/microsoft/pyright/issues/5140. It's fixed in "main" and will be included in the next release of pyright. Apologies for the regression.

**Closed by erictraut** 2023-05-21 21:28 UTC
