### ISSUE TITLE
Referencing variable in `finally` clause wrongfully changes type after try except block

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#2930] opened 2022-01-24 11:07 UTC
For the following code Pyright correctly reports no errors:

```python
def foo():
    file = None
    try:
        file = open('test.json')
    except Exception:
        return None
    file.name
```

However when we add a `finally` clause to close the file the last line is incorrectly reported as an error:

```python
def foo():
    file = None
    try:
        file = open('test.json')
    except Exception:
        return None
    finally:
        if file:
            file.close()
    
    # error: "name" is not a known member of "None" (reportOptionalMemberAccess)
    file.name
```

(using pyright 1.1.214)

**Comment by JelleZijlstra** [comment] 2022-01-24 18:20
For what it's worth, pyanalyze gets this one right, but the solution isn't pretty (https://github.com/quora/pyanalyze/blob/aa705ecb2a86925e02f4634d85d73db793b7ebc0/pyanalyze/name_check_visitor.py#L3360). We visit the finally block three times:
- Once assuming nothing in the try-except block executes
- Once assuming something interrupted execution within the try-except block (e.g. a return or raise)
- Once assuming execution continued through the whole block without error
Combining the variable types from the three options then yields the correct types within the finally block.

**Comment by erictraut** [comment] 2022-01-25 01:43
This case is easier to handle in a multi-pass analyzer. Pyright is a single-pass lazy analyzer, which is important because it's designed as the basis for a language server. It enables a caller to ask for the type of any identifier in a source file, and it evaluates only the necessary types to answer that question. 

Pyright's architecture is based on the TypeScript compiler. I confirmed that it also doesn't handle this particular case.

```typescript
function get_str_or_undefined(): string | undefined {
    return undefined;
}

function needs_str(y: string) {
    // Do nothing
}

export function foo() {
    let x: string | undefined;

    try {
        x = get_str_or_undefined()
    } catch (e) {
        return;
    } finally {
        // Do nothing
    }

    // This generates an error because the type of x
    // is `string | undefined`
    needs_str(x)
}
```

I've figured out a way to make this work within pyright's architecture. It trades off a bit of speed when analyzing the finally block, but I think the tradeoff is acceptable.

This fix will be in the next release.

@jakebailey, you may find this one interesting.

**Comment by erictraut** [comment] 2022-01-26 05:37
This is included in pyright 1.1.215, which I just published. It will also be included in the next release of pylance.

**Closed by erictraut** 2022-01-26 05:37 UTC
Labels: bug, addressed in next version

**Comment by not-my-profile** [comment] 2022-01-26 05:49
Thank you!

**Comment by jakebailey** [comment] 2022-01-27 19:53
@erictraut Maybe I'm misreading the test, but why would `x` be `string` at the end there? The function can return undefined, so `x` could be undefined.

I think that the original issue's code here is more similar to:

```ts
function getString(): string {
    return "hello";
}

export function foo() {
    let x: string | undefined;

    try {
        x = getString()
    } catch (e) {
        x = undefined; // Ignored, as it's returning.
        return;
    } finally {
        // Do nothing
    }

    x; // string
//  ^?
}
```

[Playground Link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAcwKZQMpQE4zMgCgEoAuRAZxz2UQG8AoRJxbdEbJAIgAtUAbPnE4BuegF969VAA8ADnGxREoSLATK4cYnUbM+6RNLKVc+RAB9E4ACapgeVNdG6mOAJ47mXw4gC8KdCxTQiIXRDFECABDKAhuRAJUIk9vJmk-KzBbezBHYUQAegLEAElkMAVHABpEKPJEGCgAcnrWKHYwagA6MK82jtEvCJyogQ8GVKYixAAROEQKqG5qMIkw6VFpxAA9AH5xIA)

**Comment by erictraut** [comment] 2022-01-27 20:00
Yes, you're correct. My bad. Looks like TS is handling it correctly.

**Comment by erictraut** [comment] 2022-02-24 20:53
Note: I needed to revert the change because it introduced a regression for analysis of types within the `finally` suite. 

As I mentioned above, there are limitations to pyright's ability to analyze code within a `finally` statement, and the case described in this bug report is one such circumstance. You can work around this by adding an extra assert statement after the finally clause.
