### ISSUE TITLE
Wrong type inside loop comprehension

### ISSUE THREAD

**Issue by mehdigmira** [microsoft/pyright#4103] opened 2022-10-28 15:08 UTC
**Describe the bug**
Pyright seems to not take into account the if clause of a nested loop comprehension.

**To Reproduce**
```python
result: list[str | list[dict]] = []
reveal_type([subitem for item in result for subitem in item if not isinstance(item, str)]). # type here is list[str | dict[Unknown, Unknown]] it should be list[dict[Unknown, Unknown]]
reveal_type([item for item in result if not isinstance(item, str)]). # type here is correct list[list[dict[Unknown, Unknown]]]
```

**Expected behavior**
Pyright should infer list[dict[Unknown, Unknown]] in the first example

**VS Code extension or command-line**
pyright 1.1.277 but i can also reproduce in 1.1.274

**Comment by erictraut** [comment] 2022-10-28 15:33
I agree this looks like an incorrect type evaluation.

Interestingly, mypy gets both cases completely wrong.

**Comment by debonte** [comment] 2022-10-28 23:40
If we change `isinstance(item, str)` to `isinstance(subitem, str)` this works.

```python
result: list[str | list[dict]] = []
reveal_type([subitem for item in result for subitem in item if not isinstance(item, str)])    # type is list[str | dict[Unknown, Unknown]]
reveal_type([subitem for item in result for subitem in item if not isinstance(subitem, str)]) # type is list[dict[Unknown, Unknown]]
```

**Comment by erictraut** [comment] 2022-10-29 03:15
Thanks for the analysis.

Yes, in looking at this closer, the behavior is expected because of the way type narrowing works. The conditional check in this case tests the type of `item`, so type narrowing is applied to `item`. The type of `subitem` is not narrowed by this conditional.

The behavior is more obvious if you deconstruct the list comprehension into its equivalent `for` loops:
```python
x = []
for item in result:
    reveal_type(item) # str | list[dict]
    for subitem in item:
        reveal_type(subitem) # str | dict
        if isinstance(item, str):
            reveal_type(subitem) # str | dict
            x.append(subitem)
```

Since this is expected behavior and not a bug, I'm going to close it.

**Closed** 2022-10-29 03:16 UTC
Labels: as designed

**Comment by mehdigmira** [comment] 2022-10-31 11:39
you're right, sorry for the wrong report 👍
