### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nodeType')

### ISSUE THREAD

**Issue by judej** [microsoft/pyright#6391] opened 2023-11-08 23:53 UTC
pyright 1.1.334 
TypeError: Cannot read properties of undefined (reading 'nodeType')
at nodeType /analyzer/analyzerNodeInfo.ts:148:16
at getFileInfo /analyzer/typeEvaluator.ts:5590:55
at getTypeOfClassMemberName /analyzer/typeEvaluator.ts:2067:25
at getTypeOfObjectMember /analyzer/typeEvaluator.ts:12606:34
at callback /analyzer/typeUtils.ts:419:31
at objType /analyzer/typeEvaluator.ts:12662:39
at callback /analyzer/typeUtils.ts:419:31
at type /analyzer/typeEvaluator.ts:2571:41
at getTypeOfIterator /analyzer/typeEvaluator.ts:10008:24
at matchFunctionArgumentsToParameters /analyzer/typeEvaluator.ts:11368:29
at validateFunctionArguments /analyzer/typeEvaluator.ts:9210:31
at errorNode /analyzer/typeEvaluator.ts:8964:28
at callback /analyzer/typeEvaluator.ts:19739:19
at useSpeculativeMode /analyzer/typeEvaluator.ts:8960:23
at callback /analyzer/typeUtils.ts:669:8
at expandedType /analyzer/typeEvaluator.ts:3771:29
at expandSubtype /analyzer/typeEvaluator.ts:3810:12
at mapSubtypesExpandTypeVars /analyzer/typeEvaluator.ts:8956:25
at node /analyzer/typeEvaluator.ts:1020:43
at getTypeOfExpression /analyzer/typeEvaluator.ts:15333:38
at evaluateTypesForAssignmentStatement /analyzer/typeEvaluator.ts:18843:24
at callback /analyzer/typeEvaluator.ts:18957:8
at evaluateTypeForSubnode /analyzer/typeEvaluator.ts:20500:31
at getInferredTypeOfDeclaration /analyzer/typeEvaluator.ts:20843:31
at func ()

**Comment by erictraut** [comment] 2023-11-09 00:00
Thanks for reporting. This turns out to be a duplicate of https://github.com/microsoft/pyright/issues/6383, which I've already fixed.

**Comment by judej** [comment] 2023-11-29 21:04
we are still seeing this in pylance insiders 2023.11.13 released on 11/15.

**Comment by judej** [comment] 2023-11-29 21:10
stack trace from 2023.11.13
```
TypeError: Cannot read properties of undefined (reading 'nodeType')
at nodeType src/analyzer/analyzerNodeInfo.ts:148:16
at getFileInfo src/analyzer/typeEvaluator.ts:3083:42
at callback src/common/timing.ts:40:19
at addDiagnostic src/analyzer/checker.ts:1010:32
at visitReturn src/analyzer/parseTreeWalker.ts:526:28
at visit src/analyzer/parseTreeWalker.ts:933:20
at visitNode src/analyzer/parseTreeWalker.ts:915:36
at walk src/analyzer/checker.ts:267:18
at declaration src/pytest/pyTestDocumentTransformer.ts:180:12
at func (nonymous>)
at forEach src/analyzer/parseTreeWalker.ts:922:14
at walkMultiple src/analyzer/parseTreeWalker.ts:917:17
at walk src/analyzer/checker.ts:267:18
at walk src/analyzer/checker.ts:2695:17
at _walkStatementsAndReportUnreachable src/analyzer/checker.ts:276:13
at visitSuite src/analyzer/parseTreeWalker.ts:544:28
at visit src/analyzer/parseTreeWalker.ts:933:20
at visitNode src/analyzer/parseTreeWalker.ts:915:36
at walk src/analyzer/checker.ts:267:18
at declaration src/pytest/pyTestDocumentTransformer.ts:180:12
at func (nonymous>)
at forEach src/analyzer/parseTreeWalker.ts:922:14
at walkMultiple src/analyzer/parseTreeWalker.ts:917:17
at walk src/analyzer/checker.ts:267:18
at walk src/analyzer/checker.ts:2695:17
at _walkStatementsAndReportUnreachable src/analyzer/checker.ts:276:13
at visitSuite src/analyzer/parseTreeWalker.ts:544:28
at visit src/analyzer/parseTreeWalker.ts:933:20
at visitNode src/analyzer/parseTreeWalker.ts:915:36
at walk src/analyzer/checker.ts:267:18
at walk src/analyzer/checker.ts:643:17
at visitFunction src/analyzer/parseTreeWalker.ts:442:28
```

**Closed** 2023-12-02 09:48 UTC
Labels: bug, addressed in next version
