### ISSUE TITLE
Pyright language server does not work with jupyter

### ISSUE THREAD

**Issue by Igorgro** [microsoft/pyright#6789] opened 2023-12-21 17:57 UTC
**Describe the bug**
When using pyright as language server in vscode, it crashes when trying to use it with jupyter notebook. The logs show the following:
```
[Info  - 18:21:46] Pyright language server 1.1.342 starting
[Info  - 18:21:46] Server root directory: file:///home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist
[Info  - 18:21:46] Starting service instance "jupyter"
Received pythonPath from Python extension: /home/igormahov/dev/python/.venv/bin/python
[Info  - 18:21:46] Setting pythonPath for service "jupyter": "/home/igormahov/dev/python/.venv/bin/python"
[Info  - 18:21:46] Assuming Python version 3.11
[Info  - 18:21:48] Found 2 source files
Error: Debug Failure. vscode-notebook-cell:/home/igormahov/dev/python/test.ipynb#W2sZmlsZQ%3D%3D is not a file based URI.
    at d.getFilePath (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/common/uri/webUri.ts:164:15)
    at S.isInZip (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/common/realFileSystem.ts:415:26)
    at l.isInZip (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/readonlyAugmentedFileSystem.ts:159:28)
    at canNavigateToFile (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/languageService/navigationUtils.ts:14:16)
    at b.canNavigateToFile (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/languageServerBase.ts:1410:16)
    at forEach (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/languageServerBase.ts:1304:23)
    at Array.forEach (<anonymous>)
    at b.onAnalysisCompletedHandler (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/languageServerBase.ts:1303:29)
    at c._onAnalysisCompletion (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/languageServerBase.ts:441:57)
    at c.handleAnalysisResponse (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/backgroundAnalysisBase.ts:245:22)
    at MessagePort.<anonymous> (/home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist/pyright-internal/src/backgroundAnalysisBase.ts:279:61)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[Info  - 18:21:50] Connection to server got closed. Server will restart.
true
[Info  - 18:21:50] Pyright language server 1.1.342 starting
[Info  - 18:21:50] Server root directory: file:///home/igormahov/.vscode/extensions/ms-pyright.pyright-1.1.342/dist
[Info  - 18:21:50] Starting service instance "jupyter"
```

**Code or Screenshots**
This bug does not depends on the exact python code

**VS Code extension or command-line**
Vscode extension version: 1.1.342

**Comment by debonte** [comment] 2023-12-21 17:59
This is a duplicate of https://github.com/microsoft/pyright/issues/6787.

**Comment by erictraut** [comment] 2023-12-21 18:01
Closing as duplicate.

**Closed by erictraut** 2023-12-21 18:01 UTC
Labels: bug
