### ISSUE TITLE
TypedDict from typing_extensions doesn't work with __getitem__ or assignments

### ISSUE THREAD

**Issue by Maistho** [microsoft/pyright#6074] opened 2023-10-03 16:18 UTC
**Describe the bug**
Importing `TypedDict` from `typing_extensions` makes pyright complain that `__getitem__` doesn't exist and that it's not possible to assign anything to a `TypedDict` declared using the function.

The main reason this is an issue to us is that certain dependencies are using `typing_extensions` for compatibility reasons.

**Code or Screenshots**

When importing from `typing_extensions`:
```python
from typing_extensions import TypedDict


TestFunction = TypedDict("TestFunction", {"foo": int})

test_function: TestFunction = {"foo": 1}
test_function["foo"]


class TestClass(TypedDict):
    foo: int


test_class: TestClass = {"foo": 1}
test_class["foo"]
```
Running pyright I get the following errors:
```
/home/user/test_type.py
  /home/user/test_type.py:6:31 - error: Expression of type "dict[str, int]" cannot be assigned to declared type "__class__TypedDictMeta" (reportGeneralTypeIssues)
  /home/user/test_type.py:7:1 - error: "__getitem__" method not defined on type "__class__TypedDictMeta" (reportGeneralTypeIssues)
  /home/user/test_type.py:10:17 - error: Expected type expression but received "(typename: Unknown, fields: _Sentinel | Unknown = _marker, /, *, total: bool = True, **kwargs: Unknown) -> type[__class__TypedDictMeta]" (reportGeneralTypeIssues)
  /home/user/test_type.py:14:25 - error: Expression of type "dict[str, int]" cannot be assigned to declared type "TestClass" (reportGeneralTypeIssues)
4 errors, 0 warnings, 0 informations
```

But when importing from `typing`:
```python
from typing import TypedDict


TestFunction = TypedDict("TestFunction", {"foo": int})

test_function: TestFunction = {"foo": 1}
test_function["foo"]


class TestClass(TypedDict):
    foo: int


test_class: TestClass = {"foo": 1}
test_class["foo"]
```
Running pyright results in no errors:
```
0 errors, 0 warnings, 0 informations 
```

**VS Code extension or command-line**
I see this both in VS Code and in command-line usage of pyright.
I'm using python `3.11.3`, typing_extensions `4.8.0` and pyright `1.1.329`

**Comment by erictraut** [comment] 2023-10-03 16:59
I'm not able to repro the problem. It's likely that you have an old type stub for `typing_extensions` installed in your python environment. Please try `pip uninstall typing_extensions-stubs`. If that doesn't work, try to repro with a fresh virtual environment.

**Comment by erictraut** [comment] 2023-10-04 01:55
I'm pretty sure this isn't a pyright bug, so I'm going to close this issue. If you're not able to find the cause, feel free to post additional information, and I'd be happy to help you further diagnose the cause.

**Closed by erictraut** 2023-10-04 01:56 UTC
Labels: bug, question
