### ISSUE TITLE
Reflected operand methods not recognized in numeric subclasses

### ISSUE THREAD

**Issue by philg314** [microsoft/pyright#3862] opened 2022-08-24 11:06 UTC
**Describe the bug**
Pyright does not recognize reflected (swapped) operand methods in numeric subclasses.

**Code**
```python
from __future__ import annotations


class intSubclass(int):
    def __add__(self, __x: int) -> intSubclass:
        return intSubclass(super().__add__(__x))

    def __radd__(self, __x: int) -> intSubclass:
        return intSubclass(super().__radd__(__x))


int_var: intSubclass = intSubclass(123)

int_var = int_var + 123
print("int_var __add__ ", type(int_var))
#      int_var __add__  <class '__main__.intSubclass'>

# Expression of type "int" cannot be assigned to declared type "intSubclass"
#   "int" is incompatible with "intSubclass"
int_var = 123 + int_var
print("int_var __radd__", type(int_var))
#      int_var __radd__ <class '__main__.intSubclass'>


class floatSubclass(float):
    def __add__(self, __x: float) -> floatSubclass:
        return floatSubclass(super().__add__(__x))

    def __radd__(self, __x: float) -> floatSubclass:
        return floatSubclass(super().__radd__(__x))


float_var: floatSubclass = floatSubclass(1.23)

float_var = float_var + 1.23
print("float_var __add__ ", type(float_var))
#      float_var __add__  <class '__main__.floatSubclass'>

# Expression of type "float" cannot be assigned to declared type "floatSubclass"
#   "float" is incompatible with "floatSubclass"
float_var = 1.23 + float_var
print("float_var __radd__", type(float_var))
#      float_var __radd__ <class '__main__.floatSubclass'>
```

**VS Code extension**
Pyright 1.1.266 through Pylance 2022.8.30

**Additional context**
Python 3.10.5

**Comment by erictraut** [comment] 2022-08-24 14:32
Pyright applies reflected operand methods in cases where the non-reflected operand methods do not work — that is, the type information indicates that the non-reflected method cannot be called with the provided operand types. This behavior matches the [documented](https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types) Python behavior, which says:

> These [reflected] methods are called to implement the binary arithmetic operations (+, -, *, @, /, //, %, divmod(), pow(), **, <<, >>, &, ^, |) with reflected (swapped) operands. These functions are only called if the left operand does not support the corresponding operation and the operands are of different types.`

In the case of `int_var + 123`, the `int.__add__` method accepts `int_var` (which derives from `int`) as an operand, and it produces an `int` as a result.

```python
    def __add__(self, __x: int) -> int: ...
```

From the type information provided to pyright, I think it's doing the right thing here. From your example, it looks like the runtime is doing something different in this case. That means the Python documentation is wrong, there's a bug in the runtime implementation, the typeshed stubs are wrong, or some combination of the above.

**Comment by erictraut** [comment] 2022-08-24 14:38
After doing a bit more experimentation, it looks like `int.__add__` does not return `NotImplemented`, which means that the runtime is following the documentation, but the typeshed `__add__` method is incorrect. It should probably be changed to something like this to match the runtime behavior:

```python
TInt = TypeVar("TInt", bound=int)
def __add__(self, __x: TInt) -> TInt: ...
```

If you agree with this, please consider reporting a bug in the typeshed project.

This is a pretty significant change to a builtin class, so I don't know how the typeshed maintainers will feel about it.

**Comment by philg314** [comment] 2022-08-24 17:38
I think pyright is wrong in this case. The [docs](https://docs.python.org/3.10/reference/datamodel.html#object.__ror__) include this note:

> **Note:** If the right operand’s type is a subclass of the left operand’s type and that subclass provides a different implementation of the reflected method for the operation, this method will be called before the left operand’s non-reflected method. This behavior allows subclasses to override their ancestors’ operations.

The runtime does what the note describes in [cpython/Objects/abstract.c](https://github.com/python/cpython/blob/3.10/Objects/abstract.c#L846-L907).

`intSubclass` is a subclass of `int` and it provides a reflected method for the operation, so it is called:

```python
from __future__ import annotations

class intSubclass(int):
    def __radd__(self, __x: int) -> intSubclass:
        print(f"called intSubclass.__radd__({self=}, {__x=})")
        return intSubclass(super().__radd__(__x))

print(type(123 + intSubclass(456)))

# called intSubclass.__radd__(self=456, __x=123)
# <class '__main__.intSubclass'>
```

**Comment by erictraut** [comment] 2022-08-24 18:00
Ah, thanks for calling out that additional note in the documentation. I didn't notice that previously.

**Comment by erictraut** [comment] 2022-08-28 04:27
I thought this sounded vaguely familiar. It turns out this is a duplicate of https://github.com/microsoft/pyright/issues/3368. As noted in that thread, there's no real way to handle this correctly because the type system doesn't distinguish between a type and its subtypes. If an annotation specifies type `Foo`, that means `Foo` or a subtype thereof. One could argue that there are edge cases that could be handled statically, but they would be incomplete. And adding this support would add significant complexity to an already extremely-complex piece of code. This is a very common code path in the type checker, and it would also impact performance. For all of those reasons, I'm going to come to the same conclusion as before. You'll need to explore workarounds if you want this type check without errors in pyright.

**Closed** 2022-08-28 04:28 UTC
Labels: as designed

**Comment by philg314** [comment] 2022-08-28 07:30
I don't understand why this can't be handled correctly. When evaluating the result type of a binary operation the type(s) of the left and right hand side are known. If it is a reversible operation it can always be determined whether to use the specified reversible operation or the corresponding reversed operation:

- Normal case (use specified operation)
- Special case (use reversed operation) if
  - Right type is a subclass of left type and
  - Right type implements the reversed operation and
  - Right type reversed operation implementation is different from left type reversed operation implementation

For union left and right hand types the result type is the union of types determined by applying the above to all combinations of left and right hand types.

Under what circumstances would this be incorrect or incomplete?

**Comment by erictraut** [comment] 2022-08-28 10:16
The problem is that when you specify a type annotation, you are not specifying an exact type. For example, if you specify that a parameter is of type `Foo`, it doesn't need to literally be an instance of the class `Foo`. It can be any subclass of `Foo`.  So if the type checker sees that there's a `+` operator and the LHS and RHS are both determined to be `Foo` or a subclass thereof, it cannot tell whether the runtime interpreter will apply this special-case rule and prioritize `__radd__` or `__add__`.
