### ISSUE TITLE
reportOptionalMemberAccess is fired for .__doc__

### ISSUE THREAD

**Issue by vakorol** [microsoft/pyright#7519] opened 2024-03-19 11:38 UTC
Consider the following code:

```python
class SomeAbstractClass:
    """This is a docstring template: {foo}"""


class ChildClass(SomeAbstractClass):
    __doc__ = SomeAbstractClass.__doc__.format(foo="bar")
```

Pyright treats the last line as an error:

```
"format" is not a known member of "None" [reportOptionalMemberAccess]
```

This is wrong, since `__doc__` is available for the parent class implicitly and is not `None`. 

This is observed when using Pyright as an LSP server for Neovim.

**Comment by erictraut** [comment] 2024-03-19 14:38
This is by design. The type of `__doc__` is `str | None`, and it's not `Final`, so it can be reassigned to `None` at any time. To make your code type check here, you can add an assert.

**Closed** 2024-03-19 14:52 UTC
Labels: bug, as designed
