### ISSUE TITLE
Too broad type for TypedDict.get with union of literals

### ISSUE THREAD

**Issue by unicodestrangely** [microsoft/pyright#7715] opened 2024-04-17 13:33 UTC
**Describe the bug**
`TypedDict.get` with `Union[Literal[...], Literal[...], ...]` returns `Any | None`. It should return union of value types.

**Code**
```python
from typing import Literal, TypedDict

class MyDict(TypedDict):
    foo: str
    bar: int

def get_foo(d: MyDict, key: Literal["foo"]) -> None:
    value1 = d[key]
    reveal_type(value1)  # Type of "value1" is "str"
    value2 = d.get(key)
    reveal_type(value2)  # Type of "value2" is "str"

def get_foobar(d: MyDict, key: Literal["foo", "bar"]) -> None:
    value1 = d[key]
    reveal_type(value1)  # Type of "value1" is "str | int"
    value2 = d.get(key)
    reveal_type(value2)  # Type of "value2" is "Any | None"
```

**VS Code extension or command-line**
Command-line, 1.1.358

**Comment by erictraut** [comment] 2024-04-17 14:52
This is an unfortunate result of the way that overload resolution works. I don't see a way to fix this without breaking other (more common) use cases for the `get` method in a TypedDict.

Pyright synthesizes methods in a TypedDict based on the class definition. In the case of `MyDict` in your example, the synthesized `get` consists of the following overloads:

```python
@overload
def get(k: Literal['foo']) -> str: ...
@overload
def get(k: Literal['foo'], default: Any) -> str: ...
@overload
def get(k: Literal['bar']) -> int: ...
@overload
def get(k: Literal['bar'], default: Any) -> int: ...
@overload
def get(k: str) -> Any | None: ...
@overload
def get(k: str, default: T) -> T | None: ...
```

The last two overloads are required because TypedDicts may contain arbitrary additional keys that are not specified in the TypedDict definition (i.e. they are not "closed"). They're also required because it's legal to pass a key any `str` value even if the literal value isn't known statically.

When you call `get` with a union type, the second-to-the-last overload applies, so the return type is `Any | None`. If none of the overloads were to match, then pyright would apply "[union expansion](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=overloads)" to the key argument and apply two or more overloads, but this never happens because an overload match is found without the need for union expansion.

The current type evaluation (`Any | None`) is technically correct for your use case, but it's admittedly a wider type than is ideal. Removing the last two overloads would produce a better (narrower) type result in your use case, but it would create a bunch of false positive errors in legitimate code, so that's not a good tradeoff.

I'll think about this a bit more, but my inclination is to close it as "won't fix" because I don't see a way to fix it without breaking other (more important) cases.

**Comment by unicodestrangely** [comment] 2024-04-17 17:13
FYI mypy: `main.py:17: note: Revealed type is "Union[builtins.str, builtins.int, None]"`

**Comment by erictraut** [comment] 2024-04-17 17:31
Yes, mypy implements this functionality in a different way. It applies custom logic for this case rather than synthesizing a set of static overloads. That results in its own set of problems — especially in the context of a language server, so it's not an approach I would entertain here for pyright.

**Comment by unicodestrangely** [comment] 2024-04-17 17:53
The problem here is `Any` that hides all errors; For example:

```python
from typing import Literal, TypedDict

class MyDict(TypedDict):
    foo: str
    bar: int

# Maybe "bar" type was str, but was changed to int during refactoring. Old code is not fixed yet
def get_foobar(d: MyDict, key: Literal["foo", "bar"]):
    my_func(d.get(key, "")) # This is a runtime error that is not catched by pyright
    my_func(d[key])  # This shows an error

def my_func(foo: str):
    print(foo.split())

get_foobar({"foo": "foo", "bar": 1}, "bar")
```

**Comment by erictraut** [comment] 2024-04-23 01:41
After thinking about this more, I've decided to close this as "won't fix". I understand your perspective, but I think pyright's behavior here is defensible. The return type of `get` is wider than you might like, but it is correct. The behavior you're seeing is an inevitable consequence of the way overload resolution works.

**Closed by erictraut** 2024-04-23 01:41 UTC
Labels: bug, as designed

**Comment by kyle-query** [comment] 2024-07-23 22:43
I suspect not having closed key sets is also why `TypedDicts` can't be assigned to dict types narrower than `dict[str, object]`. I found [PEP-728](https://peps.python.org/pep-0728/) which would mean the second type parameter to `dict` could be computed as a union over the specified values, so this could work:

```python
class Foo(TypedDict, closed=True):
    a: int
    b: str

foo: dict[str, str | int] = Foo(a=1, b="")
```

This PEP is not yet accepted but is implemented in [pyright 1.1.352](https://github.com/microsoft/pyright/releases/tag/1.1.352) and I've confirmed it works. It does cause analysis to be much slower in a large package with hundreds of TypedDicts definitions that reference one another, but I can live with this. Thank you for making this available, @erictraut.

Regarding the original issue, pyright still reports that `get` has the overload `gef get(k: str) -> (Any | None): ...`. I wonder if this could be `def get(k: str) -> Never: ...` or `def get(k: str) -> None: ...` when the TypedDict is defined with `total=True`.

**Comment by erictraut** [comment] 2024-07-24 00:17
Yes, closed TypedDicts is the right answer here.

It's interesting to hear that switching to closed TypedDicts affects analysis performance in a meaningful way. I wouldn't expect that. If you have some way for me to repro this, I could take a look at it. Then again, I probably don't want to spend too much time optimizing this code path unless/until the PEP is accepted because if it's rejected, I'll be ripping out all of that support anyway.

As for your suggested change for the synthesized `get` method, I don't think that would work. A TypedDict defined with `total=True` means that the keys that are defined must be populated. It doesn't mean that other keys (outside of the defined set) are not present. There needs to be some fallback overload to handle these keys. `Never` wouldn't be an appropriate return type for this fallback overload, nor would `None`. I suppose it could be `object | None`, which is equivalent to just `object`, but I don't think that change helps you.

**Comment by kyle-query** [comment] 2024-07-30 16:06
> A TypedDict defined with total=True means that the keys that are defined must be populated. It doesn't mean that other keys (outside of the defined set) are not present.

But that would be the case with `closed=True`. Could the type of `get` depend on whether `closed=True` is given?

> It's interesting to hear that switching to closed TypedDicts affects analysis performance in a meaningful way. I wouldn't expect that. If you have some way for me to repro this, I could take a look at it.

Thanks for mentioning that. The performance issue seemed to disappear when I created a standalone repo to isolate it, but if the PEP is accepted I will spend more time creating a reproducible test case.

**Comment by erictraut** [comment] 2024-07-30 16:20
> Could the type of get depend on whether closed=True is given?

Yes, it would be safe to synthesize a different (more "precise") version of `get` if `closed=True`. That's an enhancement I'd consider if the PEP is accepted.
