### ISSUE TITLE
Wrong warning "Code is unreachable"

### ISSUE THREAD

**Issue by kaldown** [microsoft/pyright#1532] opened 2021-02-24 17:55 UTC
[EDITED]
For some reason `Pyright` thinks this code is unreachable - this is clearly a mistake.
```
from contextlib import suppress

seconds = 0
with suppress(ValueError):
    seconds = int('a')

if not seconds:
    seconds = 42
```

Then in think all the other code, out of scope is broken too. Which is another (maybe consecutive) misconception.

**Comment by erictraut** [comment] 2021-02-24 18:04
Can you please create a minimal code example that exhibits the problem?

**Comment by kaldown** [comment] 2021-02-24 18:26
```
from contextlib import suppress

seconds = 0
with suppress(ValueError):
    seconds = int('a')

if not seconds:
    seconds = 42

```

**Comment by kaldown** [comment] 2021-02-24 19:00
I'm actually using https://github.com/fannheyward/coc-pyright with `vim`.
How could I tell you version you need?
Is this some kind of a server running, idk

**Comment by erictraut** [comment] 2021-02-24 19:03
Sorry, I don't know anything about coc-pyright other than that it uses pyright. In particular, I don't know how often they release updates. You'd need to talk to the maintainers of that project.

I'm pretty confident this is not a bug in pyright, so I'm going to close the issue. If you learn more, feel free to update this issue.

**Closed** 2021-02-24 19:13 UTC
Labels: question
