### ISSUE TITLE
List[Hashable] possibly matching wrong?

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pyright#3259] opened 2022-03-26 19:33 UTC
See discussion at https://github.com/python/mypy/issues/12464#issuecomment-1079759274

```python
from typing import Hashable, List


def f(x: List[Hashable]):
    x.append("x")


def g(x: List[object]):
    pass


l: List[int] = [1]
f(l)  # no pyright error
g(l)  # error (as expected)
```

pyright reports:
```
c:\Code\Misc\pytypes\dictstrany.py
  c:\Code\Misc\pytypes\dictstrany.py:14:3 - error: Argument of type "list[int]" cannot be assigned to parameter "x" of type "list[object]" in function "g"
    TypeVar "_T@list" is invariant
      "int" is incompatible with "object" (reportGeneralTypeIssues)
```

mypy reports:
```
dictstrany.py:13: error: Argument 1 to "f" has incompatible type "List[int]"; expected "List[Hashable]"
dictstrany.py:13: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
dictstrany.py:13: note: Consider using "Sequence" instead, which is covariant
dictstrany.py:14: error: Argument 1 to "g" has incompatible type "List[int]"; expected "List[object]"
dictstrany.py:14: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
dictstrany.py:14: note: Consider using "Sequence" instead, which is covariant
```

Seems to be some difference of opinion on how `Hashable` should be interpreted inside of invariant collections (`List`, `Dict`, `Mapping`, etc.)

This is with command line pyright 1.1.232 on Windows, python 3.9.7

**Comment by JelleZijlstra** [comment] 2022-03-26 19:35
I already reported #3258

**Comment by erictraut** [comment] 2022-03-27 04:25
This is a duplicate of #3258.

**Closed** 2022-03-27 04:25 UTC
