### ISSUE TITLE
VSC Extension: Option to disable InteliSence

### ISSUE THREAD

**Issue by butuzov** [microsoft/pyright#122] opened 2019-05-09 18:52 UTC
**Is your feature request related to a problem? Please describe.**
Python extension provides currently better support for intelisense, I would like to avoid seeing pyright integration with intelisense, but there is no option to disable it. 

**Describe the solution you'd like**
Implement VSC setting, that allows disabling integration with intelisense.

**Additional context**
![image](https://user-images.githubusercontent.com/651824/57478829-9b774a00-72a4-11e9-8690-9dd14b0439a2.png)

Both bottoms autocomplete options are coming from `pyright`, and they not providing any useful information.

**Comment by erictraut** [comment] 2019-05-10 00:53
Is pyright overriding the type completion information provided by the Python extension? I assumed that VS Code would combine the two lists.

I'll need to think about the best way to expose an "off switch". Options include: a VS Code setting or a pyrightconfig.json setting. Or maybe there's a way I could auto-detect the presence of the Python extension and disable type completion in that case.

My plan is to improve type completion, but it's lower on the list than other type checking features.

**Comment by butuzov** [comment] 2019-05-10 04:16
It's not overriding Python extension information, but adding doubles and not providing any info in them. 

I think `intelisense disable` option should be added to VSC setttings, as it directly related to VSC functionality.

PS
once again, thanks for awesome checker and your work!

**Comment by erictraut** [comment] 2019-05-10 04:34
OK, thanks for the suggestion. 

Currently pyright doesn't expose any pyright-specific settings in VS Code. It honors a few python settings. Adding its own settings is doable, but it's a bit of work. I'll keep the suggestion open for now, but I just want to set expectations that this is lower on the priority list.

**Comment by erictraut** [comment] 2019-05-28 02:36
In version 1.0.34, I've substantially improved type completion (Intelligence) support in pyright. It now supports completion of import paths, import symbols, keywords, local variables, classes, methods, and functions. It also offers "signature help" — information that pops up when you're editing a call signature to provide hints about the parameters. And it now extracts doc strings for modules, classes, methods and functions and displays them as hover text. 

Let me know what you think. Are there other ways I can make better?

**Comment by butuzov** [comment] 2019-05-31 08:11
I am looking at this right now (1.0.36), alongside with Python extension - I can't tell what is what. 

* There no more duplicates (I just don't see it anymore)
* "Signature help"s are OK now.

So I assume - you did a great work eliminating a problem. 

thanks!

**Comment by erictraut** [comment] 2019-05-31 15:11
OK, I'm going to close this issue then. Thanks.

**Comment by leonhard-s** [comment] 2019-07-06 12:11
As of 1.0.43, I am still getting duplicates with both IntelliSense suggestions and hover text.

![2](https://user-images.githubusercontent.com/35902139/60755830-cdcbcc00-9ff5-11e9-9c7b-831181ad497b.PNG)
![2019-07-06](https://user-images.githubusercontent.com/35902139/60755832-cdcbcc00-9ff5-11e9-95ca-0c7942dae858.png)
*The top entries are provided by the Python extension, the bottom ones by Pyright. The screenshots were made on a fresh VS Code install with only the Python and Pyright extensions enabled.*

Is a VS Code setting still on the roadmap? Or was there a fix the OP found I haven't yet?

**Comment by butuzov** [comment] 2019-07-06 13:17
@leonhard-s problem returned. 

Guess having the option to disable intelisence integration will be really handy.

**Comment by erictraut** [comment] 2019-07-06 14:53
I don't currently plan to add settings to disable individual editor integration features (like type completion, hover, or definitions) in Pyright. If the duplicates are really bothering you, here are several options:
1. Disable the Pyright VS Code extension and run it as a command-line tool.
2. Disable the type completion functionality in the Python extension. I think you can do so by setting the python.jediPath to a non-existent path, but I haven't yet confirmed.
3. Build your own private copy of the Pyright VS Code extension with functionality disabled.

**Comment by giyyapan** [comment] 2019-08-07 04:00
@erictraut 
Sorry I have to comment under a closed issue, But the duplicate suggestions are realy anoying.

I've tried number 2 of your options above, but I found that pyright (version 1.0.52) dosn't suggest bult-in types, and there's no signature help.

---

![image](https://user-images.githubusercontent.com/3479453/62593290-b63f7600-b908-11e9-9a79-444d5abce344.png)
_only pyright enabled - "Exception" class not in suggestions_

![image](https://user-images.githubusercontent.com/3479453/62593356-f6065d80-b908-11e9-81b1-e70b614a0e8e.png)
_only pyright enabled - no signature displayed_

---

![image](https://user-images.githubusercontent.com/3479453/62593108-2e596c00-b908-11e9-9abb-bf36afe1f877.png)
_pyright and jedi enabled - jedi shows "Exception" class and it's signature_

![image](https://user-images.githubusercontent.com/3479453/62593642-1e428c00-b90a-11e9-9bec-5257ee035db4.png)
_pyright and jedi enabled - two same suggestion, the jedi one have signature_

---

One of your comment says you've done something about the duplication and signature help, so is this behaviour expected or it's a bug or something?

I would love to use pyright with VSCode because it's obviously much usefull this way. So I definitely won't take option 1.

And I think it dosn't have to be a new setting, maybe just fix the signature hint and make pyright suggest built-in types, then I can just disable jedi for good.

**Comment by erictraut** [comment] 2019-08-08 04:39
@glyyapan, thanks for the great suggestions and feedback. 

These weren't bugs, but they were omissions in the type completion logic. I've addressed all of the shortcomings you've noted, and the fixes will be in the next version of pyright. 

Please keep the great ideas coming!

**Comment by erictraut** [comment] 2019-08-08 08:01
This is implemented in 1.0.53, which I just published.

**Comment by giyyapan** [comment] 2019-08-09 04:35
@erictraut 
Used version 1.0.53 and It much better now, thanks for you great work!

**Comment by erictraut** [comment] 2019-08-17 05:53
This feature continues to be requested, so I've decided to add a way to disable the language service features in pyright. This will be in the next release.

**Comment by erictraut** [comment] 2019-08-17 06:01
This is now implemented in 1.0.56, which I just published.

**Closed by erictraut** 2019-08-17 06:01 UTC
Labels: enhancement, fixed in next version

**Comment by dzpt** [comment] 2020-02-14 04:54
@erictraut `pyright.disableLanguageServices` also disable object properties. So it doesn't work
