### ISSUE TITLE
"from pylab import *" break right type

### ISSUE THREAD

**Issue by zhuangzhuang** [microsoft/pyright#788] opened 2020-07-03 15:49 UTC
**Describe the bug**

from pylab import * 
lead to type failed

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Pyright can resolve the Image.open correctly

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/521058/86483763-51460780-bd87-11ea-8cf8-ec24b3797971.png)

![image](https://user-images.githubusercontent.com/521058/86483797-61f67d80-bd87-11ea-8fb3-29adc29c368f.png)

**VS Code extension or command-line**
This happens with Pylance 2020.6.1 and pyright 1.1.48

**Additional context**

**Comment by erictraut** [comment] 2020-07-03 17:05
Thanks for the bug report. I'm not able to repro the problem you're seeing. Perhaps there are additional repro steps that I'm missing. I installed the latest versions of pylab-sdk and Pillow.

![image](https://user-images.githubusercontent.com/7040122/86487955-5fa70b80-bd14-11ea-8fda-073d12b547c6.png)

Based on the screen shots you provided, my best guess is that pylab is exporting a symbol called `Image`, and it is being imported as part of your wildcard import. (Incidentally, using wildcard imports is a very dangerous practice that leads to very fragile code. I highly recommend against ever using wildcard imports.)

**Comment by zhuangzhuang** [comment] 2020-07-04 02:32
@erictraut 
the pylab  is from matplotlib, not pylab-sdk
"https://stackoverflow.com/questions/16849483/which-is-the-recommended-way-to-plot-matplotlib-or-pylab"

**Comment by erictraut** [comment] 2020-07-04 07:26
I switched from pylab-sdk to mayplotlib, and I am still unable to repro the problem. Perhaps you're using an older version of matplotlib? Which version do you have installed?

**Comment by zhuangzhuang** [comment] 2020-07-04 08:25
python version is 3.7.7 64bti version.

attrs==19.3.0
autopep8==1.5.3
backcall==0.2.0
bleach==3.1.5
colorama==0.4.3
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
importlib-metadata==1.7.0
ipykernel==5.3.0
ipython==7.16.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.1
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.5
jupyter-console==6.1.0
jupyter-core==4.6.3
kiwisolver==1.2.0
libsvm==3.23
MarkupSafe==1.1.1
matplotlib==3.2.2
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.7
notebook==6.0.3
numpy==1.18.5
opencv-python==4.2.0
packaging==20.4
panda3d==1.10.4.1
pandocfilters==1.4.2
parso==0.7.0
pickleshare==0.7.5
Pillow==7.2.0
prometheus-client==0.8.0
prompt-toolkit==3.0.5
pycodestyle==2.6.0
pydot==1.4.1
pygame==1.9.6
Pygments==2.6.1
PyOpenGL==3.1.5
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
python-graph-core==1.8.2
pywin32==228
pywinpty==0.5.7
pyzmq==19.0.1
qtconsole==4.7.5
QtPy==1.9.0
scipy==1.4.1
Send2Trash==1.5.0
six==1.15.0
terminado==0.8.3
testpath==0.4.4
toml==0.10.1
tornado==6.0.4
traitlets==4.3.3
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp==3.1.0

**Comment by erictraut** [comment] 2020-07-05 02:13
I'm still unable to repro the problem you're reporting. Would you be willing to create a new workspace with a fresh virtual environment and try to repro it in with an isolated code snippet? Without specific repro steps, I won't be able to make any further progress.

**Comment by zhuangzhuang** [comment] 2020-07-05 03:07
I make a video for this 
I has remove all python version from my pc, remove all vscode extends from my pc.
https://www.youtube.com/watch?v=ndZgZdO8SgQ&feature=youtu.be

**Comment by erictraut** [comment] 2020-07-05 14:11
Thank you, I was able to repro the problem based on your video. I am working on a fix. The problem is related to the fact that you are importing the "Image" symbol twice. The first time it is imported through the wildcard import, and the second time it is imported through an explicit (non-wildcard) import statement.

If you were to reverse the order of your two import statements, your program would break. This underscores the importance of never using wildcard imports in Python code. They can easily lead to very fragile code.

**Comment by zhuangzhuang** [comment] 2020-07-05 15:13
maybe  the matplotlib inspired by matlab.
matlab code has not module or namespace.
😄

**Comment by erictraut** [comment] 2020-07-06 02:29
This is addressed in Pyright 1.1.50, which I just published.

**Closed by erictraut** 2020-07-06 02:29 UTC
Labels: bug, fixed in next version
