### ISSUE TITLE
Watcher could not use native fsevents library. File system watcher disabled.

### ISSUE THREAD

**Issue by Haibao425** [microsoft/pyright#386] opened 2019-12-03 08:05 UTC
I am using VSCode in Mac OS, and now when I open my VSCode, pyright output below errors, since I added 5 folders for "include" section in pyrightconfig.json.
And I am working on Python project.

[Error - 3:58:02 PM] Watcher could not use native fsevents library. File system watcher disabled.
[Error - 3:58:02 PM] Watcher could not use native fsevents library. File system watcher disabled.
[Error - 3:58:02 PM] Watcher could not use native fsevents library. File system watcher disabled.
[Error - 3:58:02 PM] Watcher could not use native fsevents library. File system watcher disabled.
[Error - 3:58:02 PM] Watcher could not use native fsevents library. File system watcher disabled.

I installed Watchman, Node, and also fsevents, cannot solve this issue.

**Comment by burknator** [comment] 2019-12-03 08:43
Same here, although I it doesn't matter if I have an include section in the config. The error pops up whenever I change the config or when I restart Code.

I'm pretty sure this started to come up after updating to 1.40.1, maybe already at 1.40. Extension version is 1.1.7.

**Comment by Haibao425** [comment] 2019-12-03 10:13
The issue happened from 1.1.5, please check the change list from 1.1.4 to 1.1.5

**Comment by erictraut** [comment] 2019-12-03 15:45
Pyright uses a library called chokidar for detecting file system changes. It's the same library that VS Code and thousands of other tools use. On MacOS it attempts to use native component that uses file system events. However, in some conditions (that are not well understood by me or others I've talked to), chokidar falls back on a much slower polling mechanism. To do so, it maintains an in-memory representation of the file system hierarchy. If that hierarchy gets very large (as is the case with some workspaces), chokidar can run the CPU at 100% for many minutes, consume the entire heap, and crash pyright. For that reason, I've disabled the file system watcher when it hits this condition. The error you're seeing is simply reporting that you're in this condition. It should be benign except that pyright won't notice when code files are modified outside of VS Code.

**Comment by burknator** [comment] 2019-12-03 15:51
Thanks for the explanation! Did it always behave this way? Because it's only lately that I got the error, and as I said it pops up everz time Code is started (or the plugin for that matter). Is there a way to make this go silent?

**Comment by erictraut** [comment] 2019-12-03 15:55
You're actually seeing the error pop up? It should be a (mostly silent) error that gets logged to the Output panel if you care to look there. If it's popping up in a VS Code dialog, that's unexpected.

**Comment by burknator** [comment] 2019-12-03 16:08
<img width="1021" alt="Bildschirmfoto 2019-12-03 um 17 03 53" src="https://user-images.githubusercontent.com/26658/70067861-3e036b80-15ef-11ea-97fb-75cec8c36bb6.png">

Yes, like this. And I just noticed that the "Output" panel only opens in that project. In my other Python project only the notification is shown.

**Comment by Haibao425** [comment] 2019-12-04 01:22
> <img alt="Bildschirmfoto 2019-12-03 um 17 03 53" width="1021" src="https://user-images.githubusercontent.com/26658/70067861-3e036b80-15ef-11ea-97fb-75cec8c36bb6.png">
> 
> Yes, like this. And I just noticed that the "Output" panel only opens in that project. In my other Python project only the notification is shown.

Yes, I have same problem, the error dialog pops up every time while starting VSCode.
And I checked the change history from 1.1.4 to 1.1.5, there is one change to change FS Watcher logic, the issue must be caused by that change.
@Eric, Would you please have different logic for Mac OS? the popped dialog is indeed boring me.

**Comment by erictraut** [comment] 2019-12-04 03:49
Thanks for reporting this. I've changed it to log the error in a more silent manner. This will be fixed in the next release.

**Comment by erictraut** [comment] 2019-12-04 18:32
This is now fixed in 1.1.8, which I just published.

**Closed by erictraut** 2019-12-04 18:32 UTC
Labels: bug, fixed in next version

**Comment by kanekv** [comment] 2020-02-04 07:58
I'm still seeing this problem in 1.1.21

**Comment by erictraut** [comment] 2020-02-04 08:03
To confirm, are you seeing the error appear in a dialog box as shown in the screen shot above? Or are you seeing this error message logged to the Pyright output panel? It should no longer appear in a dialog box, only as informational output.

I would expect this to appear only if you have set the "pyright.openFilesOnly" setting to false, you are on MacOS, and you have a large number of files within your workspace. Please let me know if I'm incorrect in any of those assumptions.

**Comment by kanekv** [comment] 2020-02-04 08:36
@erictraut Yes, not seeing it in dialog, only in output panel. That's correct that I have a lot of files on MacOS (in the workspace), but not many under `include` folder.

**Comment by erictraut** [comment] 2020-02-04 15:41
OK, then this is the expected behavior. Pyright makes use of a file system watcher when you set "pyright.openFilesOnly" to false. This allows it to detect source file changes made outside of the editor, such as when you do a "git pull". Unfortunately, the MacOS file system has limitations that prevent this from working when the number of files and directories is very large. In those cases, Pyright needs to disable the file system watcher. All functionality in Pyright will continue to work except that it won't detect file changes outside of your editor. The warning that you see in the output window is for diagnostic purposes only.
