### ISSUE TITLE
Inconsistencies in case statements type analysis with Never type

### ISSUE THREAD

**Issue by MJavad** [microsoft/pyright#9633] opened 2024-12-25 19:28 UTC
**Describe the bug**
I found some issues while working with a Result type inspired by Rust's [Result](https://doc.rust-lang.org/std/result/). While it is possible to reduce this example more, I think it is more understandable if I include some of the original use cases:

**Code**
Code sample in [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.391&pythonVersion=3.10&code=GYJw9gtgBCCGB2ATSUCWEAOYQBcYOQgChQUcBPDVeAczU2zwHEBTeFkVAYwBooAVSiwCCAG1SwAzn0EYWANVggS4aBSq0A%2BiwAeONpNRh4k%2BllxQAciwBuHPiFstYozepZEi-KAF4BQxRAACgAifhCASiIAUV9-OUDQ6JC%2BACMwAFckHwAhKRZonS4WDBwjeCjPLlEpUwB5AGsg1nZOLgBtfj5ogF0IgC4iKGGoTRsXDJZ%2BgSGRzU0IWBwuAAtNJRpJebjQsYmWFMqRqEQWYFHNalQceaDJFlFgPnHRSen%2BCKgAWgA%2BK2MprNjsN7o8AHR7V4sOIvSaeIjVWpQaIgYItDjcTrdPqDY7aVHTaJAi6LZZrDZbTQ7EL4kCHTzHU7neZXG6aO4PJ5QDggQmfX7-di44EgzkQnlxHnwgBKLEkGVEOHeQjEElMfkaWORPSgAB9kaitb14UyoMAwGAgvy-rL5Yr2tQcHxrHYQD1hcNHDgMiB4FBGkEAAyVIim1JKK3fG1yhU4dou%2BxQRRQlHgN0emAsb2%2Bg3BZOTVPYK0h81gTSOO14Pylq1ERx2FxuIRBUvlmOKz5QADE8WhYHOIVbFdjITQphCmsdzqcbr1uYd8CdVhnPRCnlJqzNFrblYzXHy-qaYAaA2Jx3rzlc7iCx87PdkfYHx9HqHHjrXx3391zQR5p5FnpOI215-sM95CFA-ZQCEPIvuOACq8ANPAYAAO7wCkUAAMLGIYpycLQUA4Cs0IsNcJEgDusZ8AAklAqGZKIiDcjochcHgxGvkRYBQKk0IhAmdJQEEACMnxBAATFEn4HhWSpniMF7Ac2cl3r2kEDnJcHQYJo6iZUG4rFuZbDoqe4HgGt4ZueQFXs2t5gepUEhM%2BY7Qe%2BxJftCcnWYptlNnIQSqY5D4adBWluSEqYLkugmrrR9GMcxuhsRxKxceI7Dcbx3klIwLDMVkjiwKssCpKI0JBAAzCGZHERwVGKnENafKg5xwEgkCRg837hsEURKXZgV1RRjU4GpoXOSNDWmTg2kTg0MXTq6Or6tFU7Litc6aoJfD5gUqLYKt867Um%2ByFm6a5EIZ3LkTN7byTJ36WSevmAQ2Q0sDeJ4hRBzmuVxITvnwOGoiw7GiOQkEQNcpiCZ5B6pr%2BqL-gBg0BV9oHdk5A6wZF%2B0XZhoOOBDUOQLDm0cAj34%2BQp72XhjQVyuNv1yGFIQRYDul8AAspQUMrFIUCwFAGDgOVLDQGLYBcMUkiGIRnGmF5wliUQQA)

```python
from random import random
from typing import Generic, TypeAlias, TypeVar
from typing_extensions import Never, reveal_type

T = TypeVar("T")
E = TypeVar("E", bound=BaseException)


class Ok(Generic[T, E]):
    _value: T
    __match_args__ = ("_value",)

    def __init__(self, value: T) -> None:
        self._value = value


class Err(Generic[T, E]):
    _err: E
    __match_args__ = ("_err",)

    def __init__(self, err: E) -> None:
        self._err = err


Result: TypeAlias = Ok[T, E] | Err[T, E]


def foo() -> Result[int, Never]:
    return Ok(0)


def bar() -> Result[Never, ValueError]:
    return Err(ValueError())


foo_result = foo()
reveal_type(foo_result)  # Type of "foo_result" is "Ok[int, Never] | Err[int, Never]"

match foo_result:
    case Ok(ok):
        reveal_type(ok)  # Type of "ok" is "int"
    case Err(err):
        reveal_type(err)  # Type of "err" is "Unknown", Considering the either_result, I would expect this to be "Never" (1) (2)
    case rest:
        reveal_type(rest)  # Type of "rest" is "Never" (1)

match foo_result:
    case Ok(ok):
        reveal_type(ok)  # Type of "ok" is "int"
    case rest:
        reveal_type(rest)  # Type of "rest" is "Err[int, Never]", I would expect this line to be reported unreachable (3)


either_result = foo() if random() else bar()
reveal_type(either_result)  # Type of "either_result" is "Ok[int, Never] | Err[int, Never] | Ok[Never, ValueError] | Err[Never, ValueError]"

match either_result:
    case Ok(ok):
        reveal_type(ok)  # Type of "ok" is "int", Correctly omits Never
    case Err(err):
        reveal_type(err)  # Type of "err" is "ValueError", Correctly omits Never
    case rest:
        reveal_type(rest)  # Type of "rest" is "Never", Mypy has a problem proccessing this case (1)

```

1. These lines are reported unreachable in Pyright Playground, but not in VSCode.
2. Considering the `either_result` example can correctly omit `Never`, I would expect the type of `err` in this line to be `Never`, like the `rest` case.
3. Considering it is impossible to create an `Err` with `Never` as the second generic argument (Since calling its `__init__` with `Never` is impossible), In theory, Pyright should be able to recognize that `Err[int, Never]` is equal to `Never`. I don't know if this is a bug or a feature request.

**VS Code extension**
VSCode 1.96.2
Pylance language server 2024.12.1 (pyright version 1.1.389, commit ce1325fc)

**Comment by erictraut** [comment] 2024-12-25 19:44
I'm not able to repro the first issue with the latest version of pyright (1.1.391). The behavior in VS Code matches the behavior in the playground. Please upgrade to the latest version of pyright to see if you can repro it.

For the second case, pyright is working as intended. The type of the class parameter cannot be determined in this case, so the `err` is `Unknown`.

For the third case, pyright is working correctly. The type `X[Never]` is not equivalent to `Never` from a type theory standpoint, so it would be inappropriate for a type checker to assume equivalency in this case.

I think pyright is working correctly in all three cases, so I'm going to close this issue. If you think I've missed something in my analysis, let me know.

**Closed by erictraut** 2024-12-25 19:44 UTC
Labels: bug

**Comment by MJavad** [comment] 2024-12-25 21:17
First I would like to mention that there were some mistakes in the third case on my part, the issue is more nuanced than this:
Please take a look at this [pyright playground](https://pyright-play.net/?pyrightVersion=1.1.391&pythonVersion=3.13&code=GYJw9gtgBCCGB2ATSUCWEAOYQBcYOQgChQUcBPDVeAczU2zwHEBTeFkVAYwBooA5FgDcOfACqUWAQQA2qWAGdxkgGqwQfEMJawZAfQoYWRImKgBeKBKNqQACgBEYhwEoiAUQtXV6x%2B4d8AEZgAK5I5gBCiizuAB5cLBg4qGDwbiZcMooKUADyANZ2rOycXADaYnzuALouAFxEUE1QekK6ISx1Vo3NenoQsDhcABZ66jQKfV6Ore0sAenNUIgswC161Kg4fXYKLDLAfG0yHV1iLlAAtAB8AqmdPUtNewcAdLMnLF7HHSZEmdkoO4QPZihxuBUqrUGks9BwQF13I91gMhqNxpM9NMHHCQQsTEsVms%2BpttnpdvtDlB4YiLjc7uwYU9npT3vCvPC-gAlFgKEIyHBnSSyeQ5SwFSFA6pQAA%2BQJBkpqfyJUGAYDAdjptx5fIFZWoOD4ghEIGqTKaWhwIRA8DyhQADOkSOq9FpdTgAIxeNUa9Kokaql1u-merpQADEUAAEmATdQ6LGOFAHD7XbyQx6HFAFMMwAB3HIOHUh-XwQ0CbSmhzIrjRO2a81PDDZGt14H2eH1JqRgA8l0u1JB2DQORYsRwcC4OBYiGRS2bChyEagAGFsFopzJyMsWNOpzkwlpYCNYIEZF8uGAViZ-cNA2A0%2B6PWHIzG47QoImQMnU8GBZns1zAtkwlA0jUraoswAQhg1s9nreo52aBcFDgr49EbedAWXNcQRYTdtxWPccAPeAjxPM8LyvYwTF-dMBQAJm9dVNRvQYAzo90GJfaMv3jT8TR-IN6JwBisxzfNC2LPUwIrE1ILQhDMOQlsllreD2wbJCmhQ7soAAETAXkoHgMA8CI-C8EPHQKPPKBL2vIhb3vR8Q24vS33BD8vyEh8-1E8SgMLUCy3A%2BTZXlEBS3LY0OEgqAYKgxSCi05kdNU5p1PQ5T0sXPTDOM0zzN3SyoGs49hlPOyHJokwgA)

As you can see, Pyright is able to detect the unreachable case only if I extract the match arm `err` variable.
Is it possible to extend this behavior to all cases?

While I agree that type `X[Never]` is not equivalent to `Never`, in my example, it is impossible to construct `Err[T, E]` with `Never` as `E` since it's used in its `__init__`. So `Err[Any, Never]` can be considered unreachable and equivalent to `Never` _in this manner_.

Using the bottom type like this is actually common in languages like Rust. The Rust's bottom type is `Infallible` (soon to be renamed to `!`) and it is used in the `Result` quite often. (First example at [here](https://doc.rust-lang.org/std/convert/enum.Infallible.html) or [here](https://stackoverflow.com/a/67836646))

Also since Pyright correctly detects the unreachable case in the `foo_result1` example, I would argue that the extracted `err` in the match case should be `Never` instead of `Unknown` since `Unknown` is not unreachable.

**Comment by MJavad** [comment] 2024-12-26 12:16
For the VSCode issue, I had to add `"python.analysis.typeEvaluation.enableReachabilityAnalysis": true`.

**Comment by erictraut** [comment] 2024-12-26 16:32
> it is impossible to construct `Err[T, E]` with `Never`

That's not true. It's possible to create a subclass whose `__init__` method doesn't meet this requirement. Even if this were true, you're claiming that a type checker should analyze the implementation of a constructor to determine type equivalency. That violates many precedents in the Python type system, so it's not a reasonable argument.

I think you're trying to be too clever with the use of `Never` here. 

I see your point that there are some apparent inconsistencies here. If I were to attempt to address these, I would make it consistent in the opposite direction — eliminating the unreachable code detection in all of your cases. I'm not sure that's worth it though. No one else has requested this, and it wouldn't satisfy your request. For those reasons, I'm going to leave this closed for now.

If you'd like to advocate for a more precise set of rules for `Never` in the Python type system, I recommend that you create a thread in the [Python typing forum](https://discuss.python.org/c/typing/32). A discussion in this forum could lead to a clarification in the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html).
