### ISSUE TITLE
Data Descriptor Type Overridden by Object Variable

### ISSUE THREAD

**Issue by KL3Baby** [microsoft/pyright#5843] opened 2023-08-29 06:45 UTC
---

## Environment data

-   Language Server version: pylance 2023.8.40
-   OS and version: Windows11 22H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2

## Code Snippet

```python
class AutoStr:
    def get(self, instance, owner=None) -> str:
        ...
    
    def set(self, instance, value: int | str):
        ...

class Test:
    Sa = AutoStr()
    St: AutoStr = AutoStr()

    def dump(self):
        self.Sa = 1.0
        self.Sa = 1
        sa = reveal_type(self.Sa)
        # Runtime type is Literal[1]

        self.St = 1.0
        self.St = 1
        st = reveal_type(self.St)
        # Runtime type is str
```

## Repro Steps

1. Define a class `AutoStr` with `get` and `set` methods.
2. Define another class `Test` with two attributes `Sa` and `St` of type `AutoStr`.
3. Assign new values to `Sa` and `St` inside a method.
4. Observe that the runtime types of `Sa` and `St` are overwritten by the types of the assigned values.

## Expected behavior

When `AutoStr`'s type hints are omitted, Pylance should still be able to parse that the type of `Test.Sa` is `AutoStr` and it should not overwrite this type hint when a variable of another type is assigned to it. 

## Actual behavior

Even though Pylance can parse that the type of `Test.Sa` is `AutoStr`, as soon as a variable of another type is assigned to it, this type hint gets overridden.

## Logs

None

**Comment by erictraut** [comment] 2023-08-29 15:22
This behavior is currently by design, so I don't consider this a bug per se.

If you want to specify that it's a class variable that contains a descriptor, you should include a type declaration at the class level (as you've done with `St`). Even better would be if you specify in the annotation that it's a `ClassVar[AutoStr]` to make it clear that this is a "pure class variable", not a variable that can be overwritten as an instance variable.

For details about how pyright interprets class and instance variables, please refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=class-and-instance-variables).

I'm going to explore whether I can change the current behavior to handle this case without a type declaration and without breaking other common use cases or degrading type analysis performance. I want to set expectations that there's a reasonable chance this will be closed as a "won't fix".

**Comment by KL3Baby** [comment] 2023-08-30 08:15
I appreciate your response. However, I believe this issue is not related to whether the variable is a ClassVar. In my case, AutoStr is a data descriptor that can change the behavior of an object's overwritten variables, please refer to [this documentation](https://docs.python.org/3/reference/datamodel.html#descriptor-invocation).

Considering the situation with `Test.St` in my sample code, it seems that Pyright itself has relevant handling for the behavior of data descriptors. I think the core of this issue is: when I do not explicitly specify a type for the fields of the data descriptor type, Pyright seems to be unsure about the result of automatic type inference, leading to the subsequent type inference result being inconsistent with the situation where the type is explicitly declared. 

I believe this might be because Pyright's handling of data descriptors does not take into account the case where the type is not explicitly specified. This could potentially be an aspect for the Pyright developers to further explore and address. Your feedback on this issue has been highly valuable.

**Comment by erictraut** [comment] 2023-09-02 15:59
As I said above, the current behavior is by design, so I don't consider this a bug. The open question is whether we should change the current type inference behavior.

Here is how pyright handles class-scoped variables (class vars and instance vars). If the type is declared (i.e. there is a type annotation), it uses the declared type. There's no ambiguity involved if the type is declared. If it's not declared, the type is inferred from the values that are assigned to the variable. If there is more than one assignment to the variable, the type is inferred as the union of all assigned types.

Consider the following example:

```python
class Foo:
    a = 1
    b = 1

    def method1(self):
        self.a = "hi"
        self.c = "hi"

f = Foo()
reveal_type(f.a) # int | str
reveal_type(f.b) # int
reveal_type(f.c) # str
```

In your code sample, type of `Sa` is not declared. Pyright's algorithm therefore infers its type based on all assigned values. 

Values can be assigned to class-scoped values in an order that cannot generally be determined statically because it depends on the order in which methods (static, class and instance) are called, so pyright doesn't attempt to apply any ordering to the assignments. It treats all assignments the same.

Consider the following code, which builds on your example above.
```python
class Test:
    Sa = AutoStr()

    @classmethod
    def reset_sa(cls):
        cls.Sa = 1.0

t = Test()
t.reset_sa()
print(t.Sa) # 1.0

reveal_type(Test.Sa) # AutoStr | float
```

There are no type violations in this code because the type of `Test.Sa` is not declared, and it's fine for the value of `1.0` to be assigned to it in the `reset_sa` class method.

If you explicitly declare the type of `Sa` to be `AutoStr`, the above code would result in a type violation, and pyright can assume that `Test.Sa` will always refer to an `AutoStr` instance.

Type inference inevitably involves assumptions and heuristics that will work in some cases and break in others. When type inference fails, a type declaration is needed to override the inference behavior. Generally, the more sophisticated the inference heuristics, the more difficult the behavior is to document. When complex heuristics fail, it's difficult for users to understand why. Complex heuristics also often have unintended side effects. For these reasons, I prefer simple heuristics and consistent behaviors.

That said, I can understand why you were surprised by pyright's behavior in this case. I'll explore adding a more complex heuristic that favors assignments in the class body when inferring the type of a class-scoped value. If I can implement this without imposing too much performance overhead, I can show that it doesn't break other common use cases, and I can explain it clearly in the documentation, then I think such a change is worth considering. No promises at this point.

**Comment by erictraut** [comment] 2023-09-03 14:52
I should point out that the original code sample claims to define a data descriptor class, but its methods are named `get` and `set` rather than `__get__` or `__set__`. That's probably just a typo, but I wanted to point it out for the benefit of others reading this issue.

Here's the corrected code.

```python
class AutoStr:
    def __get__(self, instance, owner=None) -> str:
        ...
    
    def __set__(self, instance, value: int | str):
        ...

class Test:
    Sa = AutoStr()
    St: AutoStr = AutoStr()

    def dump(self):
        self.Sa = 1.0
        self.Sa = 1
        sa = reveal_type(self.Sa)
        # Runtime type is Literal[1]

        self.St = 1.0
        self.St = 1
        st = reveal_type(self.St)
        # Runtime type is str
```

**Comment by KL3Baby** [comment] 2023-09-04 06:11
Based on your example, I now fully understand the reasoning behind Pyright's current design. Indeed, I hadn't considered that data descriptors could be overwritten. Also, I apologize for the confusion in my example about `__get__` and `get`, that was my oversight. Thank you for your explanations on this issue, I look forward to seeing the results of your further exploration.

**Comment by erictraut** [comment] 2023-12-22 18:25
I'm going to close this for now. I think pyright's current behavior is justifiable and internally consistent, although I admit that it is perhaps not what users would expect in this particular case.

I am open to revisiting this if and when this area is formalized in the Python typing spec. In the meantime, I don't want to risk creating churn for existing pyright users.

**Closed** 2023-12-22 18:26 UTC
Labels: enhancement request
