### ISSUE TITLE
Pyright doesn't recognize asyncio.subprocess as a module

### ISSUE THREAD

**Issue by Leedehai** [microsoft/pyright#859] opened 2020-07-19 23:17 UTC
**Describe the bug**
[asyncio.subprocess](https://docs.python.org/3/library/asyncio-subprocess.html) is a valid module in the asyncio module, but Pyright complained about `asyncio.subprocess` not being a known member of the module.

**To Reproduce**
Copy code :
```
import asyncio

a = asyncio.subprocess.DEVNULL
```
Run Pyright on that file (e.g. use VSCode's Pyright extension).

**Expected behavior**
There should be no Pyright error message.

**Screenshots or Code**

![Screenshot from 2020-07-19 19-11-09](https://user-images.githubusercontent.com/18319900/87887540-1e8d4780-c9f4-11ea-9033-cd7241c773f6.png)

**VS Code extension or command-line**
Pyright extension 1.1.53 on VSCode 1.47

**Additional context**
Python 3.8.2 on Ubuntu 20.04.

**Comment by erictraut** [comment] 2020-07-20 00:09
Thanks for reporting the issue. However, Pyright is working as intended here, so I'm going to mark this as "as designed".

Pyright has no intrinsic knowledge about Python stdlib classes and modules like asyncio. It uses [typeshed stub files](https://github.com/python/typeshed) for this information. If you believe that asyncio should include a subprocess submodule as part of its official public interface, please file a bug against the typeshed repo (or feel free to submit a PR). Pyright (and Pylance) directly consume typeshed stubs, so any fixes to typeshed will be incorporated into future releases of Pyright and Pylance.

**Comment by ileonte** [comment] 2020-07-20 01:20
As far as I can tell Typeshed does include stubs for that module: https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/subprocess.pyi

On my system Pyright generates no error with this code:
```
import asyncio.subprocess

a = subprocess.DEVNULL
```

Although the code in the original report works just fine in the python interpreter:
```
ileonte@ltkcentral ~/Work/projects/pyright-tests $ python
Python 3.8.4 (default, Jul 19 2020, 22:26:13) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> a = asyncio.subprocess.DEVNULL
>>> print(a)
-3
```

**Comment by erictraut** [comment] 2020-07-20 02:45
Ah, yes, you are correct. Typeshed does include the submodule definition, but it doesn't indicate that this submodule is automatically imported by (and re-exported by) the top-level module. As such, you would need to use `import asyncio.subprocess` to access this submodule.

**Comment by hauntsaninja** [comment] 2020-07-20 20:46
Isn't this the same issue as https://github.com/python/typeshed/pull/4300#issuecomment-652600517

**Comment by erictraut** [comment] 2020-07-20 21:16
@hauntsaninja, no, it's a different issue. The other one was fixed already.

**Comment by hauntsaninja** [comment] 2020-07-20 21:36
Oh you're right, my apologies. But your fix to the other issue means https://github.com/python/typeshed/pull/4346 should fix this one :-)

**Comment by erictraut** [comment] 2020-07-20 21:39
In the other case, the `json/__init__.pyi` file included the statement `from .decoder import xxx, yyy`, which (as we learned) implies that `decoder` should be included as a symbol in the `json` module.

There is no corresponding `from .subprocess import xxx, yyy` statement inside of `asyncio/__init__.pyi`.

**Comment by hauntsaninja** [comment] 2020-07-20 21:41
Yup, which is what the linked PR changes the imports in `asyncio/__init__.pyi` to look like :-)

**Comment by jakebailey** [comment] 2020-07-20 21:55
This is more like #439, which is side effects gained from doing nested imports like this. E.g. if anyone in any part of the program does `import asyncio.subprocess` before your code executes, then code that just does `import asyncio; subprocess.something` will execute without trouble (as the previous code introduced a side effect that `asyncio` must have a member named `subprocess` in order for that other code to work at all).

**Comment by erictraut** [comment] 2020-07-20 21:57
Yes, it depends on the implementation of the `asyncio` module. If the top-level module always imports the `subprocess` submodule, then the proposed change to typeshed is correct. If it doesn't, then the proposed change to typeshed would be incorrect, and Pyright's current error message would be appropriate.

**Closed** 2020-07-20 23:48 UTC
Labels: as designed
