### ISSUE TITLE
Pyright generates bad paths for stubs when `pyrightconfig.json` is in a subdir

### ISSUE THREAD

**Issue by felixm-stripe** [microsoft/pyright#6066] opened 2023-10-03 07:10 UTC
**Describe the bug**
When the `pyrightconfig.json` is not in the root of the source tree, it generates `pyi` files in the wrong location.

**Code or Screenshots**
Given a directory structure like:

```
.
├── out
│   └── path
│       └── to
│           └── whatever
│               └── pyrightconfig.json
└── some
    └── path
        └── to
            └── src
                └── python
                    └── banana.py
```

With the contents of `pyrightconfig.json` being:

```
{
  "extraPaths": [
    "../../../.."
  ],

  "include": [
    "some"
  ],

  "stubPath": "."
}
```

and the contents of `banana.py` being:

```py
from __future__ import annotations

def foo() -> int:
    return 1
```

when running:

```
pyright --project out/path/to/whatever/pyrightconfig.json --createstub some.path.to.src.python.banana --verbose
```

I get the following output:

```
Loading configuration file at /Users/x/oss/badpaths/out/path/to/whatever/pyrightconfig.json
Assuming Python version 3.9
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Search paths for /Users/x/oss/badpaths/out/path/to/whatever
  /Users/x/.nodenv/versions/18.14.0/lib/node_modules/pyright/dist/typeshed-fallback/stdlib
  /Users/x/oss/badpaths/out/path/to/whatever
  /Users/x/oss/badpaths
  /Users/x/oss/badpaths/out/path/to/whatever
  /Users/x/.nodenv/versions/18.14.0/lib/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /Users/x/.pyenv/versions/3.9.11/lib/python3.9
  /Users/x/.pyenv/versions/3.9.11/lib/python3.9/lib-dynload
  /Users/x/.pyenv/versions/3.9.11/lib/python3.9/site-packages
Type stub was created for 'some.path.to.src.python.banana'
```

the directories are created in the right location but the stub files are created in the wrong location:

```
.
├── out
│   └── path
│       └── to
│           └── whatever
│               ├── pyrightconfig.json
│               └── some
│                   ├── path
│                   │   └── to
│                   │       └── src
│                   │           └── python
│                   │               └── banana
│                   └── some
│                       └── path
│                           └── to
│                               └── src
│                                   └── python
│                                       └── banana.pyi
└── some
    └── path
        └── to
            └── src
                └── python
                    └── banana.py
```

**VS Code extension or command-line**
Pyright command line version 1.1.320

**Repro steps**
```sh
# In an empty dir do:
mkdir -p out/path/to/whatever/ && \
    echo '{"extraPaths":["../../../.."],"include":["some"],"stubPath":"."}' > out/path/to/whatever/pyrightconfig.json && \
    mkdir -p some/path/to/src/python/ && \
    echo 'from __future__ import annotations\n\ndef foo() -> int:\n    return 1' > some/path/to/src/python/banana.py

# then run:
pyright --project out/path/to/whatever/pyrightconfig.json --createstub some.path.to.src.python.banana --verbose
```

**Comment by erictraut** [comment] 2023-10-06 06:17
You're using this feature in a way that it was not intended to be used. It was designed to create stubs from a package installed in your python environment. If a module's source is located within your project, there's no need to create stubs from it. Also, `stubPath` is intended to be some subdirectory within your project. You're specifying the project root.

Is your use case real? Or are you just looking for ways to break this feature by using it in unusual ways? I need to decide whether to put time into making this work. My inclination is to simply close it as "won't fix". Now that you understand how this feature was designed to be used, are you able to use it to address your use case?

**Comment by felixm-stripe** [comment] 2023-10-06 09:16
Good question. What I really want is a way to generate stubs for a given set of sources.

We are migrating a large monorepo using Bazel as its build system to use pyright for type-checking. We want to do this by natively integrating pyright with Bazel. When we type-check a target, we need to be able to do so incrementally in the Bazel sense. That is, for each individual target, only its source files should be directly available for pyright to scrutinize, despite the target's dependency sources potentially living in the repo.

What this looks like in Bazel terms is:

```bazel
py_binary(
    name = "a",
    srcs = ["a.py"],
    deps = [":b"],
)

py_typestubs(
    name = "a.typestubs",
    srcs = ["a.py"],
)

py_library(
    name = "b",
    srcs = ["b.py"],
)

py_typestubs(
    name = "b.typestubs",
    srcs = ["b.py"],
)

py_typecheck(
    name = "a.typecheck",
    srcs = ["a.py"],
    deps = [":b.typestubs"],
)
```

To do the typecheck, we'd run `bazel build //:a.typecheck`. The `py_typecheck` target would then run `pyright` configured to find the typestubs created by the `py_typestubs` target named `b.typestubs`. I realize that if we did e.g: `pyright a.py` in the type-check target, it would only check what it needed to in `b.py`, but at scale, I believe that becomes prohibitive.

**Comment by erictraut** [comment] 2023-10-06 15:59
Hmm, that's an intriguing idea. I don't think I've heard of that approach before. Do you find that these generated stubs work for type checking? Stub generators produce what I generally refer to as a "[first draft](https://microsoft.github.io/pyright/#/type-stubs?id=generating-type-stubs)" stubs. Normally these stubs require manual cleanup before they are usable for type checking. I suppose that if the source files used to generate these stubs are already fully type annotated, the resulting stubs would be pretty high quality. In that case, however, you might as well have the build scripts copy the dependent source modules and use the source files directly rather than generating stubs from them. This would be much faster and less error prone because it wouldn't involve creating stubs. Have you considered that approach?

**Comment by felixm-stripe** [comment] 2023-10-09 07:53
The stubs are ~fine for now. Like you mentioned, if the files are already properly annotated the stubs subsequently become high-quality. As such, third party dependencies that are already properly annotated work really well. The internal codebase is not yet annotated well enough, thus we need a forcing mechanism to help us achieve our decided level of typing -- while not adding too much friction for our engineers.

Bazel also aggressively caches everything, so we never end up recreating stubs needlessly. If their sources change, they of course should be recreated -- thankfully, if the generated files are equal, Bazel reuses the cached output.

The idea of allowing a target to see its direct dependencies is a possibility for sure. If the direct dependencies are properly annotated or easy enough to type-check without transitive dependencies, then we'd not need their stubs. If, however, they are not properly annotated, we end up having to resolve types for transitive dependencies, which will then trigger an error since these are not visible to the target being type-checked.

If we use direct dependencies in type-checking here, that might elicit some confusing errors to users. However, we do massage the JSON output of Pyright, so we might be able to produce better context on the error messages if there's a stable identifier. I.e. errors when failing to resolve types using transitive dependencies, maybe the `rule` field of `Diagnostic`?

The advantage, however, of forcing Pyright to use stubs for all dependencies is that we make certain that no unnecessary type-checking occurs -- but maybe there's another mechanism here to control that which I'm unaware of?

**Comment by erictraut** [comment] 2023-10-09 17:08
You'll probably need transitive dependencies regardless of whether you're using stubs or source files. It's likely that the direct dependencies expose types in their public interface surface that are imported from other dependencies. If you don't include those other dependencies, these exposed symbols will have an `Unknown` (implied `Any`) type.

> The advantage, however, of forcing Pyright to use stubs for all dependencies is that we make certain that no unnecessary type-checking occurs

If you want to prevent type checking of these other files, you can place them in a directory outside of the project's root directory, then configure pyright's `extraPaths` setting to point to that external directory so the import dependencies can be resolved. Pyright will use these external source files for types, but it won't type check them.

Alternatively, if there's a need to place these files within your project directory, you could use the `ignore` configuration option to suppress any type checking errors for these files. Pyright would type check the files, but any errors would be dropped on the floor.

**Comment by felixm-stripe** [comment] 2023-10-09 18:07
Hmm, let me see if I understand this. If we have, e.g:

```
.
├── c.py
├── pyrightconfig.json
└── typings
    └── b.pyi
```

With:

```py
# b.pyi
from a import Foo as Foo

def something(a: Foo) -> int: ...
```

and

```py
# c.py
from b import something

def main() -> int:
    return something(1)
```

Given that the stub for `a.py` is not in the `typings` directory -- Pyright will consider the function to be `something(a: Any) -> int`?

**Comment by erictraut** [comment] 2023-10-09 18:11
Yes, that's correct. If pyright cannot resolve the import of module `a`, any symbols imported from that module will be inferred as type `Unknown` (which is pyright's term for implicit `Any`).

**Comment by erictraut** [comment] 2023-10-09 18:15
What do you mean by "a stable type"? That symbol could refer to anything — a class, a function, a type alias, a constant, etc. There's really nothing valid that a type checker can assume about a symbol if it is imported from a missing module.

This is how other static analysis tools work as well.

**Comment by felixm-stripe** [comment] 2023-10-09 18:28
I can elaborate. To me this depends on when the files are present and to which part of the process.

When someone creates the type definitions for `b.py`, presumably, they have access to the module `a` that defines `Foo`. At that point, we should be able to create a canonical form of `Foo` that can be used in the above type-checking. I.e. when we want to type-check `c.py`, we need to find a subtype relationship for `int` and `Foo`, we'd need to have access to `a.py` or `a.pyi` in order to actually perform that check.

I think this is what you're saying as well. However, Pyright doesn't actually tell me that it needs to know what `Foo` is or that it couldn't resolve its module. It silently accepts `Unknown` 😅

**Comment by erictraut** [comment] 2023-10-09 18:45
> we should be able to create a canonical form of `Foo` that can be used in the above type-checking

That's not how stub generation works. Stubs are generated for a specified module and its submodules. If these modules reference other external modules, you need to generate stubs for those as well and ensure that those dependent stubs are also present at type checking time.

I mentioned above that stub generation creates a "first draft" and that you typically need to examine the generated stubs and perform a manual pass to make them usable. It's during this manual pass that you'd notice that the module depends on some external module. You can then decide whether to manually add a dummy type definition in your stubs or generate a separate set of stubs for the dependent library.

You're attempting to use these "first draft" stubs directly with no manual fix-up step. In my experience, that doesn't work for a variety of reasons, some of which you're encountering.

**Comment by erictraut** [comment] 2023-10-09 18:49
I'm going to close this issue as "won't fix". Your use case is well outside of the target use case for pyright's stub generation functionality, and it sounds like you're basing your solution on some tenuous assumptions.

If you'd like to explore other solutions to the problem you're trying to solve, I'm happy to continue the conversation in the [pyright Discussions forum](https://github.com/microsoft/pyright/discussions).

**Closed by erictraut** 2023-10-09 18:49 UTC
Labels: bug

**Comment by felixm-stripe** [comment] 2023-10-09 18:58
Yep, the discussion veered off into other territory, happy to follow this up later when we have more first-hand experience typing the repo. Thanks for the input! 👋
