### ISSUE TITLE
Unbound loop variables after loop.

### ISSUE THREAD

**Issue by BrianPugh** [microsoft/pyright#3784] opened 2022-08-04 16:37 UTC
**Describe the bug**
If you have a for loop that is guarenteed length > 0, the values of the loop variables are declared as unbound at the end of the loop.

This is really an extension of issue https://github.com/microsoft/pyright/issues/2420

**To Reproduce**
See code

**Expected behavior**
No Error Message

**Screenshots or Code**
```python
foo = ["a", "b", "c"]

if not foo:
    raise Exception

# foo is guarenteed to have at least one element at this stage.

for elem in foo:
    pass

assert elem == "c"  # [Pyright reportUnboundVariable] [E] "elem" is unbound

for i, elem in enumerate(foo):
    pass

assert i == 2  # [Pyright reportUnboundVariable] [E] "i" is unbound
```

I realize that this is mostly implementation specific; i.e. that an arbitrary object's `__bool__` and `__len__` methods aren't guaranteed to give information about its iterator methods. However, I was wondering if python's builtins (`str`, `list`, `dict`, `set`) could be special cases in pyright's checking? Thanks!

**Comment by erictraut** [comment] 2022-08-04 16:55
Yes, this is a duplicate of #2420.

This is working as designed. The Python type system doesn't have any notion of "minimum iteration counts", so a type evaluator has no basis for using such knowledge in its analysis.

If your intent is to use a loop variable after exiting a loop (something which is somewhat atypical), you should initialize it prior to the loop. 

If this is a pattern you use frequently in your code and don't want to make accommodations for type checking, you can disable the `reportUnboundVariable` check entirely.

**Closed** 2022-08-04 16:55 UTC
Labels: as designed
