### ISSUE TITLE
Docstring Formatting in autocomplete suggestion

### ISSUE THREAD

**Issue by sagarchalise** [microsoft/pyright#721] opened 2020-06-10 07:22 UTC
**Is your feature request related to a problem? Please describe.**
Currently the autocomplete docstring format is not that readable. Is it possible to show docstrings as is ? I am using `google` style.
![Screenshot from 2020-06-10 13-00-24](https://user-images.githubusercontent.com/174532/84238346-a2613380-ab1a-11ea-9374-7075222ee575.png)

**Describe the solution you'd like**
I think docstring shown by vscode-python is nice. It would be nice if some formatting could be done to docstring when shown in suggestion.

**Comment by erictraut** [comment] 2020-06-10 07:26
Thanks for the suggestion.

Could you provide a more detailed example that includes some original docstrings and what you think they should look like when displayed in completion results?

We are somewhat limited by the way in which VS Code and other language clients display completion results, which are provided in markdown format.

**Comment by msfterictraut** [comment] 2020-06-11 03:17
As Jake said, there are pros/cons to both approaches. To me, the JEDI formatting looks worse (is harder to read) than the formatting used by MPLS and Pyright. I agree that neither of them are ideal.

**Comment by sagarchalise** [comment] 2020-06-11 07:20
It seems it is being discussed in [vscode-python](https://github.com/microsoft/vscode-python/issues/38) as well.

**Comment by erictraut** [comment] 2020-07-11 07:37
This is a duplicate of feature request being discussed in the pylance-release repo. https://github.com/microsoft/pylance-release/issues/48
Also related to this issue: https://github.com/microsoft/pylance-release/issues/41
I'm going to close this bug and use the others to track this issue.

**Closed by erictraut** 2020-07-11 07:37 UTC
Labels: enhancement
