### ISSUE TITLE
Type info loss after unpacking

### ISSUE THREAD

**Issue by zhou-awx** [microsoft/pyright#9235] opened 2024-10-16 03:34 UTC
**Describe the bug**

My function will return a tuple, the first value is for success or not, the second value is the message if fail.

```python
def foo(x: int) -> tuple[bool, str | None]:
  if x > 0:
    return True, None
  else:
    return False, "message"
```

But it cannot infer type of second value even if I checked first value.
Then I changed the signature to below, but it still doesn't work.

```python
def bar(x: int) -> tuple[Literal[True], None] | tuple[Literal[False], str]:
  if x > 0:
    return True, None
  else:
    return False, "message"

ok, msg = bar()
if ok:
    reveal_type(msg) # msg is str | None
```

It it possible to infer the type of `msg` under `if ok:` to str?

I know that is this case I can make the function only return `str|None` to represent success or fail, but the actual situation is much complex.

**VS Code extension or command-line**
Pylance v2024.10.100

**Comment by erictraut** [comment] 2024-10-16 03:39
Pyright is working as intended, so this isn't a bug. 

The `if ok:` statement narrows the type of the expression `ok`. It does not narrow the types of other expressions such as `msg`.

If you want to retain type information about the tuple value returned by `bar()`, you should keep it in tuple form, like this:

```python
bar_result = bar(1)
if bar_result[0]:
    reveal_type(bar_result[1])
```

Once you unpack the tuple and assign its elements to other variables, they are tracked independently of one another.

**Closed by erictraut** 2024-10-16 03:39 UTC
Labels: bug
