### ISSUE TITLE
pyright command line requiring `venv setting`

### ISSUE THREAD

**Issue by toonknapen** [Microsoft/pyright#52] opened 2019-04-04 13:01 UTC
When running `pyright -p pyrightconfig.json -v <root-path-of-my-venv> I get the message "venvPath must be used in conjunction with venv setting, which was omitted".

What is exactly meant by 'venv setting'? 

Next it is not clear to me what exactly the difference is between the -P option and the -v. Using neither of both options and with my virtual environment however activated, pyright was neither able to find my python installation, saying "No venvPath specified. Falling back on PYTHONPATH:  No valid paths found in PYTHONPATH environment variable."

**Comment by erictraut** [comment] 2019-04-05 06:01
The "-P" option was removed in version 1.0.8, but I forgot to update the documentation. It's now fixed.

The "venv" setting is described in the [configuration documentation](https://github.com/Microsoft/pyright/blob/master/docs/configuration.md). I've updated the [command-line documentation](https://github.com/Microsoft/pyright/blob/master/docs/command-line.md) to try to clarify. 

Let me know if it's still not clear.

**Comment by toonknapen** [comment] 2019-04-05 07:08
Thanks for the quick reply.

The doc is much clearer now. 
Nevertheless, even putting the `venvPath` and `venv` in the config file, `pyright` is still not happy as he's saying:

```
cmd> pyright -p pyrightconfig.json
Loading configuration file at C:\Users\egl249\projects\alphareserve\pyrightconfig.json
Config file "C:\Users\egl249\projects\alphareserve\pyrightconfig.json" could not be parsed.
No venvPath specified. Falling back on PYTHONPATH:
  No valid paths found in PYTHONPATH environment variable.
Finding source files
No source files found.
```

However, I did specify my venvPath even in the config file.

```
{
  "include": ["alphareserve"],
  "venvPath": "C:\Users\egl249\.virtualenvs",
  "executionEnvironments": [
    {
      "root": "alphareserve",
      "venv": "alphareserve-u-eETkN8"
    }
  ]
}
```

I must be missing something very silly probably.

BTW: I'm on Windows7, npm version 6.8.0, node v10.14.1 and created my virtual environment using `pipenv`

**Comment by erictraut** [comment] 2019-04-05 16:24
Your config file contains invalid JSON. The JSON parser is failing to parse it, hence the message `Config file "C:\Users\egl249\projects\alphareserve\pyrightconfig.json" could not be parsed`. The problem is that you're using backslashes in your path, which are considered escape characters in JSON strings. You'll need to use double backslashes instead. If you use VS Code to edit the JSON file, its built-in JSON support should highlight the problem and make it clear when the JSON is invalid.

**Closed** 2019-04-06 20:46 UTC
