### ISSUE TITLE
Builtins are not defined if "inject==5.0.0" is present in the environment

### ISSUE THREAD

**Issue by caspervdw** [microsoft/pyright#5611] opened 2023-07-31 12:45 UTC
**Describe the bug**
When `inject==5.0.0` is present in the environment, pyright does not recognize any builtin type (`"str" is not defined`).

**Code or Screenshots**
- create file `script.py` containing the following builtin: `str`.
- create a fresh virtual environment and install packages with `pip install pyright inject==5.0.0`
- wipe the pyright cache (for me: `rm -rf ~/.cache/pyright-python`)
- run `pyright script.py --verbose` (output: [logs.txt](https://github.com/microsoft/pyright/files/12215081/logs.txt))
- you get hundreds of `error: Import "str" could not be resolved`

Uninstalling or downgrading inject has no effect.
A fresh environment without inject or with `inject==4.*` works fine.

The diff https://github.com/ivankorobkov/python-inject/compare/v4.3.1...v5.0.0 shows an added typeshed file, which is probably the cause, but I am not an expert on this area of python.

Thanks in advance for your response!

**Comment by erictraut** [comment] 2023-07-31 14:50
The problem is that the `inject` library is installing a directory called `typeshed` within the `site-packages` directory. I suspect this is unintentional. If so, it should probably be removed by the maintainers of this library so it doesn't pollute `site-packages`.

Pyright contains some code that looks for an installed copy of `typeshed` in the `site-packages` directory and uses it instead of the bundled typeshed stubs. These stubs are used to define builtins and all other stdlib functionality, so if you have incomplete or corrupted typeshed files, type checking will not work. 

The code in pyright that looks for an installed copy of `typeshed` in `site-packages` is very old (from the earliest days of pyright), and I don't think there's a good reason for it to look there. Since then, PEP 561 has been published and clarified the order in which type checkers should perform import resolutions, and it doesn't provide any mechanism for `typeshed` to be located within `site-packages`. So I'm removing this old code from pyright. This allows it to work with the `inject` library. This will be included in the next release.

**Comment by erictraut** [comment] 2023-08-02 02:47
This is addressed in pyright 1.1.320, which I just published. It will also be included in a future version of pylance.

**Closed by erictraut** 2023-08-02 02:47 UTC
Labels: bug, addressed in next version

**Comment by caspervdw** [comment] 2023-08-02 07:13
Thanks @erictraut for your fast response.
