### ISSUE TITLE
Unexpected behavior of dictionary type check

### ISSUE THREAD

**Issue by shungok** [microsoft/pyright#718] opened 2020-06-09 16:15 UTC
**Describe the bug**
The statement that adds a new element to the dictionary gives an error.

**To Reproduce**

```
$ cat test1.py
dic = {"name": "bob"}
dic["age"] = 1

$ node node_modules/pyright/index.js test1.py
stubPath /private/tmp/hoge/typings is not a valid directory.
Searching for source files
Found 1 source file
/private/tmp/hoge/test1.py
  2:1 - error: Argument of type "Literal[1]" cannot be assigned to parameter "v" in function "__setitem__" of type "str"
  "int" is incompatible with "str" (reportGeneralTypeIssues)
1 error, 0 warnings
Completed in 4.838sec
```

**Expected behavior**
I think the sentence is correct.

By the way, I understand that specifying different type values ​​for the same key causes an error, as following.

```
$ cat test2.py
dic = {"name": "bob"}
dic["name"] = "jhon"
dic["name"] = 2

$ node node_modules/pyright/index.js test2.py
stubPath /private/tmp/hoge/typings is not a valid directory.
Searching for source files
Found 1 source file
/private/tmp/hoge/test2.py
  3:1 - error: Argument of type "Literal[2]" cannot be assigned to parameter "v" in function "__setitem__" of type "str"
  "int" is incompatible with "str" (reportGeneralTypeIssues)
1 error, 0 warnings
Completed in 0.846sec
```

**Comment by erictraut** [comment] 2020-06-09 16:41
The behavior is correct. In your example, the variable "dic" does not have an explicit type annotation, so a type checker like Pyright needs to infer its type based on the value that is assigned to it. The problem is that type inferences can be ambiguous. In this example, it's clearly a Dict, but the the two type arguments (corresponding to the key and value of the dictionary) could be inferred in several ways:

```
Dict[Literal["name"], Literal["bob"]]
Dict[str, str]
Dict[str, Any]
Dict[Any, Any]
```

If the inference is too specific, it limits the use of the variable more than intended. If the inference is not specific enough, then you lose the benefits of type checking.

Pyright tries to strike the right balance between the two extremes and uses the following heuristics when inferring the two type arguments to `Dict`:
1. If all of the keys of the assigned value are of the same type, that type is used for the first type argument. If all the values are of the same type, that type is used for the second type argument. Literals are stripped when considering these types.
2. If the keys are of different types and the (strictDictionaryInference)[https://github.com/microsoft/pyright/blob/master/docs/configuration.md] rule is enabled, it uses the union of the types. The same is true for values.
3. If strictDictionaryInference is not enabled, it uses Any if the types are mixed.

In your particular case, it is using rule 1, so the inferred type of `dic` is `Dict[str, str]`. When you then attempt to assign an `int` to the dictionary, it is a type violation.

The correct way to deal with this is to provide an explicit type annotation for the variable `dic`.
```
dic: Dict[str, Any] = {"name", "bob"}
```
or, if you know that you will use only str and int values:
```
dic: Dict[str, Union[str, int]] = {"name", "bob"}
```

If you need to retain compatibility with Python 3.5 or older, you will need to use a type comment in this case because variable type annotations were added in Python 3.6.
```
dic = {"name", "bob"} # type: Dict[str, Any]
```

**Comment by shungok** [comment] 2020-06-10 01:44
@erictraut Thank you for your polite comment.

I could understand the flow of type inference.

I was able to confirm that it also works correctly, as following.

```
$ cat test3.py
from typing import Dict, Any
dic: Dict[str, Any] = {"name": "bob"}
dic["age"] = 1

$ node node_modules/pyright/index.js test3.py
stubPath /private/tmp/hoge/typings is not a valid directory.
Searching for source files
Found 1 source file
0 errors, 0 warnings
Completed in 0.718sec
```

**Closed** 2020-06-10 02:32 UTC
Labels: as designed

**Comment by robertocarta** [comment] 2020-06-26 11:32
Is there a way to change the default behaviour and always have dictionaries as [Any, Any] unless otherwise specified?

**Comment by erictraut** [comment] 2020-06-26 16:03
No, there's currently no way to change the inference behavior for dictionaries in that way. Inferring [Any, Any] in all cases would reduce the type-checker's ability to detect problems in a pretty significant way.

**Comment by vrajanap** [comment] 2022-06-01 06:29
> 
No, there's currently no way to change the inference behavior for dictionaries in that way. Inferring [Any, Any] in all cases would reduce the type-checker's ability to detect problems in a pretty significant way.

Can this be updated to be able to enable /  disable per project via configuration?

**Comment by erictraut** [comment] 2022-06-01 07:44
No, we're unlikely to make that an option. None of the other Python type checkers offer such an option either — and for good reason. It would significantly reduce the effectiveness of type checking.

Adding type annotations may sound daunting if you have a big code base, but it's not that much work. If you have a large existing code base, my recommendation is to incrementally make it typed. Start with individual directories and add them to the "include" section of the pyright config. You can also enable certain type checking rules over time as you clean up the code, add type annotations, and fix type-related bugs in the code base. If it's a code base that you plan to maintain for a while, this is an investment that's well worth it. If there are parts of the code base that are "legacy" and are scheduled to be replaced, don't invest the time or energy in making them typed. For new code modules, I recommend starting with strict type checking. It's much cheaper to write strictly-typed code from the start than to retrofit an existing code base.

This is the approach I took with my team's Python code base (about 2K modules and 500K lines). Within about six months, most of the code base type checked in basic mode, and after about 12 months, we got to the point where most of the code base type checked in strict mode. We have maintained it at this level for the past two years, and this allows a large team of developers to make rapid changes (adding new features, refactoring, etc.) with confidence that we're not introducing regressions.

**Comment by vrajanap** [comment] 2022-06-02 04:59
I understand! Thanks @erictraut for your response.

**Comment by kamerado** [comment] 2025-02-25 18:55
Pyright is garbage for keras and tensorflow.
