### ISSUE TITLE
__init__ overloads and bidirectional type inference ?

### ISSUE THREAD

**Issue by mehdigmira** [microsoft/pyright#5965] opened 2023-09-17 13:19 UTC
**Describe the bug**
In the example below, function f1 and f2 are the same, the only difference is I'm introducing an intermediate variable. But pyright doesn't seem to be able to resolve the TypeVar value in the first case.
I've previously reported bugs that looked liked, and it was related to bidirectional type inference. I don't know if it's still the case here.

**Code or Screenshots**

```python
from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Any, Generic, TypeVar, overload, reveal_type

ResultT= TypeVar("ResultT")
R = TypeVar("R")

class pipeline(Generic[ResultT]):

    @overload
    def __init__(
        self: pipeline[Sequence[R]], child: tuple[Sequence[R]]
    )->None:
        ...

    @overload
    def __init__(
        self, child: tuple[Any]
    )->None:
        ...

    def __init__(
        self, child: tuple[Any]
    )->None:
        ...


class group(Generic[ResultT]):

    @overload
    def __init__(
        self: group[ResultT],
        children: Iterable[pipeline[ResultT]]
    ) -> None:
        ...

    @overload
    def __init__(
        self,
        children: Iterable[Any]
    ) -> None:
        ...

    def __init__(
        self,
        children: Iterable[Any]
    ) -> None:
        ...

def f1(m: Sequence[int]):
    return group([pipeline((m,))])

def f2(m: Sequence[int]):
    p =[pipeline((m,))]  # noqa
    return group(p)


reveal_type(f1((1, )))  # Type of "f1((1, ))" is "group[Sequence[R@__init__]]"
reveal_type(f2((2, )))  # Type of "f2((2, ))" is "group[Sequence[int]]"

```

**VS Code extension or command-line**
Latest version of pyright

**Comment by erictraut** [comment] 2023-09-19 21:48
Here's a simplified version of your code that eliminates details that are unnecessary for reproducing the issue.

```python
from __future__ import annotations
from typing import Generic, TypeVar, Iterable, Sequence

ResultT = TypeVar("ResultT")
R = TypeVar("R")

class pipeline(Generic[ResultT]):
    def __init__(self: pipeline[Sequence[R]], child: tuple[Sequence[R]]) -> None:
        ...

class group(Generic[ResultT]):
    def __init__(self: group[ResultT], children: Iterable[pipeline[ResultT]]) -> None:
        ...

def f1(m: Sequence[int]):
    x = group([pipeline((m,))])
    reveal_type(x)  # mypy: group[Sequence[R]], pyright: group[ResultT]
```

This code relies on tenuous assumptions about how the `__init__` method's `self` parameter annotation will be interpreted by a type checker within a constructor call. It makes use of a function-scoped type variable that has no effect on the return type (since the return type of `__init__` is always `None`). And it makes no reference to the class-scoped type variable `ResultT`, which means that there's no way for a type checker to solve this type variable when evaluating the call.

I'm not sure what this code is trying to do, but I think you'll need to rethink your approach.

**Closed** 2023-09-19 21:49 UTC
Labels: bug, as designed

**Comment by mehdigmira** [comment] 2023-09-20 07:53
Thank you for your answer as always, and sorry if the example is a bit complex. 

My issue was more about overloads (that's why the example is complex), I thought there was some logic to handle such pattern

```python
from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Generic, TypeVar, overload

ResultT = TypeVar("ResultT")
R = TypeVar("R")

class pipeline1(Generic[ResultT]):

    @overload
    def __init__(
        self: pipeline1[Sequence[R]], child: tuple[Sequence[R]]
    )->None:
        ...

    @overload
    def __init__(
        self, child: tuple[Any]
    )->None:
        ...

    def __init__(
        self, child: tuple[Any]
    )->None:
        ...

class pipeline2(Generic[ResultT]):
    def __init__(self: pipeline2[Sequence[R]], child: tuple[Sequence[R]]) -> None:
        ...


def f1(m: Sequence[int]):
    reveal_type(pipeline1((m,)))  # pipeline1[Sequence[int]]
    reveal_type(pipeline2((m,)))  # pipeline2[Unknown]
```

See how pyright infers the type of `pipeline1((m,))` vs the implementation with no overloads (your example), where the revealed type is unknown. Maybe this just happens to work but is not intended behavior ?

The usecase here is just to be able to specify what objects you'll be getting, when you instantiate a `pipeline` with some specific params. If overloading __init__ is not the way to go (even if it does seem to work pretty good in multiple cases), I guess the recommended approach is to overload __new__ ?
