### ISSUE TITLE
Is `ignore` supposed to disable intellisense features?

### ISSUE THREAD

**Issue by max-muoto** [microsoft/pyright#6350] opened 2023-11-06 17:46 UTC
My understanding is that the `exclude` array would disable intellisense features for the specified modules, however based on the description of `ignore`, I assumed only errors would be silenced, but intellisense functionality would remain the same?

For example, I'm wildcarding tests as ignored `ignore = ["**/tests"]` in our `pyproject.toml` however this has the side effect of disabling quick import functionality in all of our tests for VSCode users. Mainly wanting to understand if there is a workaround here, or if this is intended.

**VS Code extension or command-line**
CLI tool with the VSCode Pylance extension.

**Comment by erictraut** [comment] 2023-11-06 18:44
Moving to discussion since this is a question, not a bug report.

**Closed as completed by erictraut** 2023-11-06 18:44 UTC
Labels: bug
