### ISSUE TITLE
Bug: Assigning a NamedTuple[int] to a Tuple of NamedTuples[int], doesn't error.

### ISSUE THREAD

**Issue by PetrochukM** [microsoft/pyright#1157] opened 2020-11-10 22:45 UTC
**Describe the bug**
For some reason, there is no error if I assign a `NamedTuple[Int]` to a `Tuple of NamedTuple[Int]`.

**To Reproduce**
```python
import pathlib
import typing

class Foo(typing.NamedTuple):
    arg: int

boo: typing.Tuple[Foo, ...] = Foo(0) # No Error
path: typing.Tuple[pathlib.Path, ...] = pathlib.Path(".") # Error: "Path" is incompatible with "Tuple[Path, ...]"
```

**Expected behavior**
Similar to `path: typing.Tuple[pathlib.Path, ...] = pathlib.Path(".")`, I expect the error `"Foo" is incompatible with "Tuple[Foo, ...]"`

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
def foo(self) -> str:
    return 3
```

**VS Code extension or command-line**
VS Code Extension: Pylance
Version: v2020.11.0

![image](https://user-images.githubusercontent.com/7424737/98742423-52a1c500-2363-11eb-94cf-cf7e736864af.png)

**Comment by erictraut** [comment] 2020-11-10 22:49
This is a duplicate of https://github.com/microsoft/pyright/issues/1152, which was fixed in the latest version of pyright. That fix will appear in tomorrow's release of pylance.

![Screen Shot 2020-11-10 at 2 49 04 PM](https://user-images.githubusercontent.com/7040122/98742796-e378a080-2363-11eb-9a46-432eaa7e9f4f.png)

**Closed** 2020-11-10 22:50 UTC

**Comment by PetrochukM** [comment] 2020-11-10 22:56
Wow! Thank you, and sorry for not triple checking the issues log first.
