### ISSUE TITLE
Language server process getting stuck when asked for completions in a PySide6 code snippet

### ISSUE THREAD

**Issue by kaofelix** [microsoft/pyright#7336] opened 2024-02-25 22:22 UTC
Hi there,

I encountered this while working on a personal project and this is the minimal reproduction steps that I could find.

I'm using built-in eglot with `emacs -Q` as I'm not sure on how to interact with the server directly from the command line. In a fresh venv where I only pip installed `PySide6` and `pyright`. `pip freeze` gives me:

```
nodeenv==1.8.0
pyright==1.1.351
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
setuptools==69.1.1
shiboken6==6.6.2
```

So, using  the following code snippet, and when requesting a completion for a property of option in line 12 (marked with `<point-is-here>`), I get nothing back from the server and I see the node background process shooting up to ~100% CPU usage:

```python
from PySide6.QtCore import QModelIndex
from PySide6.QtWidgets import QStyledItemDelegate, QStyleOptionViewItem
from PySide6.QtGui import QPainter


class LayerDelegate(QStyledItemDelegate):
    def __init__(self, parent=None):
        super().__init__(parent)

    def paint(
        self, painter: QPainter, option: QStyleOptionViewItem, index: QModelIndex
    ):
        painter.fillRect(option.rect, option.<point-is-here>)
        pixmap: QPixmap = index.data(Qt.ItemDataRole.DecorationRole)
        pixmap.scaled(option.decorationSize)
        painter.drawPixmap(option.rect, pixmap)

```

Looking at the eglot events buffer, the relevant exchange seems to be the following, where the completion request goes out and then I get a bunch of timed-out requests right after:

```
[jsonrpc] e[23:14:35.630] --> textDocument/completion[8] {"jsonrpc":"2.0","id":8,"method":"textDocument/completion","params":{"textDocument":{"uri":"file:///Users/kaofelix/Code/test-pyright-pyside6/test.py"},"position":{"line":12,"character":45},"context":{"triggerKind":1}}}
[jsonrpc] i[23:14:40.849] [4] timed-out request ':textDocument/signatureHelp'
[jsonrpc] i[23:14:42.857] [5] timed-out request ':textDocument/hover'
[jsonrpc] i[23:14:42.857] [6] timed-out request ':textDocument/documentHighlight'
[jsonrpc] i[23:14:42.857] [7] timed-out request ':textDocument/signatureHelp'
```

The full logs are here, in case it's useful [eglot-events.txt](https://github.com/microsoft/pyright/files/14398078/eglot-events.txt).

For what is worth, I tested the same file with `jedi-language-server` and I get completions normally.

**Comment by erictraut** [comment] 2024-02-25 22:43
I'm not able to repro the problem in VS Code.

Which version of PySide6 do you have installed?

**Comment by erictraut** [comment] 2024-02-26 10:30
Sorry, but I'm not able to repro the problem with the VS Code pyright extension (or Pylance). I don't know anything about eglot or emacs, so I'm not able to help you there. If the problem is specific to that editor, you'll need to work with its maintainers to further diagnose the problem.

One thought is that you could enable the "verboseOutput" option in your pyrightconfig.json or pyproject.toml file. This tells pyright to output more verbose log information. I'm not sure where the logs appear when using emacs, but in VS Code they appear in the "Output" tab.

Also, I'll note that your code sample above is not self-contained. It references symbols that are not imported. Please double check that you're able to repro the problem with that code sample.

I'm going to close the issue for now because it's non-actionable at this time. If you find additional clues, I'm happy to spend additional time on it.

**Closed by erictraut** 2024-02-26 10:30 UTC
Labels: bug, question
