### ISSUE TITLE
Ability to generate basic type stubs for untyped 3rd party package

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pyright#214] opened 2019-08-21 09:17 UTC
This approach was introduced in #204 .

CLI version pyright can provide a command to generate basic type stubs for a package so that untyped 3rd party package can have `unknown import symbol` checks or `Go to definition` functionality.

Maybe somthing like:
```bash
pyright gen-type-stubs -o output_dir /path/to/pacakge 
```

**Comment by erictraut** [comment] 2019-09-04 20:16
Thanks again for the suggestion. This will be included in the next release of pyright.

**Comment by erictraut** [comment] 2019-09-05 00:58
This is now implemented in 1.0.58, which I just published. Refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md) for details. Let me know how it works for you.

**Closed by erictraut** 2019-09-05 00:58 UTC
Labels: enhancement, fixed in next version

**Comment by giyyapan** [comment] 2019-09-09 09:31
First, thanks for your work!

I've tested this new feature in our project. Take `pyright --createstub flask` for example, I have these issues:
1. Pyright did not generate a module's dependencies automatically. Flask's pyi file imports something from `werkzeug` and stubs for `werkzeug` was not generated automatically. As a result, those variables imported from werkzeug can't be resolved in my project's import (pyright reported them as error). But it's actually okay because it's easy to investigate and have an easy fix (just create those missing stubs)
2. **Some pyi files are not created fully**. please see the example below:

In flask's source code, file app.py looks like this:
![image](https://user-images.githubusercontent.com/3479453/64519511-d8248200-d326-11e9-8ba5-69022e790798.png)

The generated flask/app.pyi file looks like this:
![image](https://user-images.githubusercontent.com/3479453/64519562-f0949c80-d326-11e9-9884-89e78eee8876.png)

As you can see, **many imports are missing**, causing statement `from flask import Request` fail for "unknown import member".

Maybe we should open a separated issue for this?

**Comment by giyyapan** [comment] 2019-09-09 10:03
I just saw [this section](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md#cleaning-up-generated-type-stubs) in the document, saying that imports that haven't been used will be removed, is that the reason for the issue above?

FYI, the name "Request" is actually referenced in that file:
![image](https://user-images.githubusercontent.com/3479453/64520907-9ba65580-d329-11e9-8a93-370f7ad88e70.png)

And in the generated file, it looks like this:
![image](https://user-images.githubusercontent.com/3479453/64520978-bd074180-d329-11e9-8416-24bcb11aed35.png)

As for the document section I referenced above, I think **maybe all imports should be preserved no matter whether they are referenced**. Because we should assume that the author of the file imported them for a reason.
- If an import is not used at all, It's the author's responsibility to remove it.
- If an import is only for execution purposes and does not influence typing, it's not likely to be exported in the package's root `__init__.py` file unless the author uses something like `from X import *` (which is rare), so there won't be any problem.

The main concern here is probably performance, I think (as a user) it's much more reasonable to let me delete the useless part of a generated pyi file for better performance instead of adding necessary but missing parts into it.

**Comment by erictraut** [comment] 2019-09-09 13:20
Both of these are "as designed". If you want or need to create type stubs for dependent libraries, you should do so separately.

I spent a bunch of extra time implementing import culling because I found that it was generally much easier to add a few missing imports than it was to delete hundreds of extraneous imports. The problem is that most imports are there because they're used by the implementation, not the interface. The type stubs remove the implementation portions, so there are _many_ unused imports. It's very unfortunate that python doesn't have the equivalent of an "export" keyword that could specify which symbols were intended to be exported and which were not. Without some manual work, there's really no way for the tool to figure out what the library's author had in mind. If you can think of any better heuristics, let me know.

**Comment by giyyapan** [comment] 2019-09-10 07:25
Point taken. I'll try adding missing imports by hand, and I'll see if there's any better approach.

Additionally, [python/typeshed](https://github.com/python/typeshed) contains some stubs for commonly used projects, is there a way I can use it with pyright?

I know I can clone and copy its content into "typingsPath", is that the recommended way?

**Comment by erictraut** [comment] 2019-09-10 12:23
There are two ways you can use the third-party type stubs in the python/typeshed repo. The first way is to clone the entire python/typeshed repo locally and use the typeshedPath setting in pyright to point to it. The second is to selectively copy only the type stubs you need and place them in your typingsPath. Some of the type stubs in typeshed are higher quality than others, and you may find that you need to manually update some of them to accommodate your needs. In that case, it works best to make your own copy.

**Comment by giyyapan** [comment] 2019-09-10 14:22
Thanks for the advice, I'll take option two.

**Comment by giyyapan** [comment] 2019-09-16 06:51
@rictraut 
I noticed that a lot of python packages do have a mean full __all__ variable, can pyright take advantage of that when generating stubs?

**Comment by erictraut** [comment] 2019-09-16 06:54
I typically see `__all__` used in `__init__.py` files, and pyright already includes all imported symbols within these files. Do you see `__all__` used in other files?

**Comment by giyyapan** [comment] 2019-09-17 05:24
Yes, but they are relatively rare.

Here are some examples I can find in my project's dependencies:
- celery uses`__all__` in almost every file: https://github.com/celery/celery/blob/master/celery/beat.py
- elasticsearch: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/exceptions.py
- gevent: https://github.com/gevent/gevent/blob/master/src/gevent/_hub_primitives.py
- kombu: https://github.com/celery/kombu/blob/master/kombu/exceptions.py
- pygments: https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/formatter.py
- raven: https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/client.py
- sqlalchemy: https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/sql/expression.py

Hope it helps.

**Comment by erictraut** [comment] 2019-09-18 06:57
Pyright already takes advantage of the `__all__` statement in most cases. However, in looking at the examples above, I realized that I made a bad assumption. I assumed that the assignment to `__all__` always occurred after the import statements in the file. I've changed the code to be order agnostic. That should eliminate some of the inappropriate import culling that you're observing.

**Comment by giyyapan** [comment] 2019-09-18 09:20
I'll keep an eye on it. Thanks for your work!
