### ISSUE TITLE
Empty constructor in custom generic type not consistent with the typed constructor

### ISSUE THREAD

**Issue by jzazo** [microsoft/pyright#6943] opened 2024-01-09 18:37 UTC
**Describe the bug**
I have a custom generic type supporting empty argument as well as with inputs. The overload methods are not compatible with each other because type cannot be inferred with the empty argument constructor. This was working with mypy. Not sure if this is a bug or I am doing things wrong.

**Code**
```python
from collections.abc import Iterable, Set
from typing import TypeVar

T = TypeVar("T")

class MySet(Set[T]):
    _d: set[T]

    @overload
    def __init__(self) -> None:
        ...

    @overload
    def __init__(self, __iterable: Iterable[T]) -> None:
        ...

    def __init__(self, __iterable: Iterable[T] = ()) -> None:
        self._d = set(__iterable)

    def __contains__(self, __x: object) -> bool:
        return self._d.__contains__(__x)

    def __iter__(self) -> Iterator[T]:
        return self._d.__iter__()

    def __len__(self) -> int:
        return self._d.__len__()
```
The error I get is:
```
error: Overloaded implementation is not consistent with signature of overload 1
    Type "(self: Self@MySet[T@MySet], __iterable: Iterable[Any] = (), /) -> None" cannot be assigned to type "(self: Self@MySet[T@MySet]) -> None"
```

**VS Code extension or command-line**
pyright as command-line
Which version? 1.1.345

**Comment by erictraut** [comment] 2024-01-09 18:42
This is related to an ambiguity in the typing spec. The issue is currently being debated in the Python typing community [here](https://discuss.python.org/t/ambiguities-about-positional-only-parameters/42328). Feel free to weigh in to the discussion if you have an opinion.

I'm going to close this bug report because pyright is working as intended currently. I will then update pyright to conform to the typing spec once a decision is made (probably within the next few weeks).

In the meantime, you can address the issue in your code by explicitly marking the `self` parameter in your first overload as position-only, like this:

```python
    @overload
    def __init__(self, /) -> None:
        ...
```

**Closed** 2024-01-09 18:42 UTC
Labels: bug, as designed
