### ISSUE TITLE
Types as class attributes when declared vs assigned

### ISSUE THREAD

**Issue by alwaysmpe** [microsoft/pyright#8620] opened 2024-07-31 16:20 UTC
**Describe the bug**

I'm writing a parser and want to allow constructs to be user defined/extendable. To do this, I'm defining a parameter model that's a subclass of a `pydantic.BaseModel` then defining the parameter spec in each parsed entity. Pyright and MyPy both give (different) errors so here I am.

**Code or Screenshots**

In the below example, Pyright gives the following error, complaining specifically about the class declaration:
> "ParamSpec" overrides symbol of same name in class "BaseCustomEntity"
   "Untitled.CustomizedEntity.ParamSpec" is incompatible with "Untitled.BaseCustomEntity.ParamSpec"
   Type "type[Untitled.CustomizedEntity.ParamSpec]" is incompatible with type "type[Untitled.BaseCustomEntity.ParamSpec]"  

Whereas MyPy gives the following error, complaining instead about the second assignment:
> main.py:18: error: Incompatible types in assignment (expression has type "type[__main__.CustomizedEntity.ParamSpec]", base class "BaseCustomEntity" defined the type as "type[__main__.BaseCustomEntity.ParamSpec]")  [assignment]
Found 1 error in 1 file (checked 1 source file)

```python
from typing import ClassVar

# pydantic BaseModel removed for example.
class ParamSpecT:
    pass

class Entity:
    param_spec: ClassVar[type[ParamSpecT]]
    # Ideally I'd remove the above and only use the below.
    ParamSpec: ClassVar[type[ParamSpecT]]

class BaseCustomEntity(Entity):
    class ParamSpec(ParamSpecT):
        pass
    param_spec = ParamSpec

class CustomizedEntity(BaseCustomEntity):
    # Pyright errors for the below declaration.
    class ParamSpec(ParamSpecT):
        pass
    # MyPy errors for the below assignment.
    param_spec = ParamSpec
```
Given the assigned `ClassVar` type value does not cause a problem but the declared value does, this seems somewhat inconsistent. MyPy has the reverse issue, which also seems inconsistent.

The Pyright error can be solved by either moving the entity `ParamSpec` declaration outside of the entity class (requiring more verbose names, undesirable) or making the class `ParamSpec` declaration private (less bad). I'm not sure if the MyPy error can be trivially solved, but that's a different problem.

The error could also be removed by making `CustomizedEntity.ParamSpec` a subclass of `BaseCustomEntity.ParamSpec` but is not compatible with my desired use case.

**VS Code extension or command-line**

Pylance extension, Pyright command line and Pyright playground.

**Comment by erictraut** [comment] 2024-07-31 16:35
Pyright is working as intended here, so I don't consider this a bug.

The base class `BaseCustomEntity` includes a symbol `ParamSpec` that is declared as a nominal class. The subclass `CustomizedEntity` redeclares this symbol in an incompatible manner, this violating the Liskov Substitution Principle.

Since class declarations are considered immutable, this symbol is covariant. That is, subclasses are allowed to override the symbol with a subtype rather than an equivalent type. That means the following is valid:

```python
class BaseCustomEntity(Entity):
    class ParamSpec(ParamSpecT):
        pass

class CustomizedEntity(BaseCustomEntity):
    class ParamSpec(BaseCustomEntity.ParamSpec):
        pass
```

This type checks in both pyright and mypy.

In any case, I don't consider this a bug, so I'm closing the issue.

**Closed by erictraut** 2024-07-31 16:35 UTC
Labels: bug

**Comment by alwaysmpe** [comment] 2024-07-31 16:43
Thanks for the clarification, makes sense and I'm happy with that. I think it's just a MyPy issue then.
