### ISSUE TITLE
Pyright holds type assertions on list items even after those been changed

### ISSUE THREAD

**Issue by evtn** [microsoft/pyright#3904] opened 2022-09-03 15:45 UTC
**Describe the bug**
Pyright seems to memorise types of specific list items, and assumes those to be same even if elements have changed.

**Screenshots or Code**
If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
a: list[str | int] = [0, "a"]

assert isinstance(a[0], int)
a.pop(0)

reveal_type(a[0]) # Type of a[0] is 'int'
a[0] + 1 # No errors there, exception in runtime
```

I understand that deciding if type has changed (it could stay the same if e.g. another element was removed) is too complex and probably impossible, but reverting `a[0]` to `str | int` on any sequence change seems right to me. It probably requires a special case introduced.

But existing behaviour seems to be a special case already:

```python
T = TypeVar("T")

class A(list[T]):
    pass

a: A[str | int] = A([0, "a"])

assert isinstance(a[0], int)
a.pop(0)

reveal_type(a[0]) # Type of a[0] is 'str | int'
a[0] + 1 # Error
```

**Comment by erictraut** [comment] 2022-09-03 17:53
The Python type system has no way for a class's author to indicate when a method mutates the internals of the class in a way that invalidates assumptions about previous member access (`a.b`) or subscript (`a[0]`) expressions. Type checkers therefore need to do one of the following:

1. Assume that member access and subscript expressions can never be narrowed.
2. Assume that any method call on the object potentially invalidates all previous type narrowing.
3. Hard code knowledge of specific methods on specific classes.
4. Assume that it is generally safe to assume that values assigned to member access and subscript expressions will be read back as the same value.

Of these approaches, options 1 and 2 would both be really painful for developers because those approaches would result in many false positives during type checking.

Option 3 is not feasible. It's not scalable or maintainable, and it violates a core principle that we've upheld within pyright from the beginning where we do not hard-code knowledge about the internal implementations of specific methods.

Option 4 is the approach that pyright adopts, with a few small caveats. In particular, assignments to member access expressions are exempted from type narrowing if the target member is an "asymmetric descriptor" — a descriptor or property whose "setter" type differs from the "getter" type. Subscript expressions are exempted if they use an index expression that is not a string or numeric literal or the type of the object being indexed is not a built-in class with known symmetric `__getitem__` and `__setitem__` internal behaviors. (It is this latter rule that explains why you are seeing type narrowing for `list` but not for `A` in your example above.)

You are correct that option 4 can lead to false positives, but they are exceedingly rare, and it's straightforward to code around them.

This is working as designed, so I don't consider it a bug.

**Closed** 2022-09-03 17:53 UTC
Labels: as designed

**Comment by evtn** [comment] 2022-09-03 18:13
It's not a false positive, since there's wrong type assumed by pyright and error is silenced (where a TypeError in runtime would be).

It would be fine to have option 1 or 2, since those generate false positives (errors for valid code) and this can be "coded around" by developer in code.

Option 4, on the other hand, ignores the presence of a type error and developer wouldn't even know if there is an error (so they won't be able to "code around them").

I agree that more complex type narrowing (e.g. option 3) is not feasible.

If by "working as designed" you mean "silencing real errors to hide typechecker inability to conclude precisely what the type is", it is indeed works as designed.

**Comment by erictraut** [comment] 2022-09-03 18:33
By "working as designed", I mean that we have thought carefully about the tradeoffs here (informed by years of experience and user feedback), and the current implementation is consistent with that design. As with many engineering problems, static type checking involves tradeoffs, and pragmatism plays into those decisions. 

One principle that guides our decisions is that false positives are generally worse than false negatives. It sounds like you would personally flip that priority. I respect that, but it's not what most pyright users want. Static type checking will never catch all bugs in your code. If the type checker is too noisy (i.e. emits too many false positives), users will find it too cumbersome and painful and will decide that it's not worth the pain. I can tell you from experience and past feedback that options 1 and 2 would introduce too much noise for most pyright users.

**Comment by evtn** [comment] 2022-09-03 18:44
Yes, I would definitely flip that priority, because I tend to see a typechecker as a tool I would rely on to catch all possible errors with types. If this means introducing some false positives - well, I can fix my code to be more formally correct with more checks, maybe it would be for better.

I understand that a lot of users would see more warnings as a frustration, but those warnings are essentially just a sign to a developer, "this code may be incorrect and you should introduce checks to be sure it works".

I would again disagree that current design is right, but it is up to you to decide and I've already written all my points.
