### ISSUE TITLE
Unable to infer Callable class variable as method

### ISSUE THREAD

**Issue by ppeetteerrs** [microsoft/pyright#3249] opened 2022-03-24 15:35 UTC
**Describe the bug**
Pyright is unable to pick up child class's method signature when:
1. The method in child class is not defined via `def`
2. The method exists in the parent class

**To Reproduce**
Pytorch's `nn.Module` defines the `__call__` method as a wrapper around the `forward` method:
```python
class Module:
    ...
    __call__ : Callable[..., Any] = _call_impl
    ...
```

Assume I define my own Pytorch `nn.Module` and add type hints to `MyModule.__call__`. I would do the following:

```python
from typing import TypeVar, Callable
from torch import nn

C = TypeVar("C", bound=Callable)

def proxy(f: C) -> C:
    return cast(C, lambda self, *x, **y: super(self.__class__, self).__call__(*x, **y))

class MyModule(nn.Module):
    def forward(x: Tensor, y: Tensor) -> Tensor:
        return x + y
    
   __call__ = proxy(forward) # __call__ exists in nn.Module
   
   another_call = proxy(forward) # another_call does not exist in nn.Module
```

If I then proceed to use `MyModule`:

```python
# x, y = some tensor
model = MyModule()

z1 = model(x, y) # Type hint of z1 is Any, same for model.__call__(x, y)

z2 = model.another_call(x, y) # Type hint of z2 is Tensor
```

**Expected behavior**
`model(x, y)` and `model.another_call(x, y)` should give the same `Tensor` type hint.

**Screenshots or Code**
See above.

**VS Code extension or command-line**
Pylance 2022.3.3

**Additional context**
On the other hand, the correct function signature and overrides pop up when typing `model(`. But the type hint is wrong for the return variable and when hovering over `model.__call__`.

**Comment by erictraut** [comment] 2022-03-24 17:09
The above code is incomplete (not self-contained), so I'm not sure I follow what you're trying to do.

Here's my attempt to fix up the code so it is complete (executable).
```python
from typing import TypeVar, Callable, cast
from torch import nn, Tensor

C = TypeVar("C", bound=Callable)

def proxy(f: C) -> C:
    return cast(C, lambda self, *x, **y: super(self.__class__, self).__call__(*x, **y))

class MyModule(nn.Module):
    def forward(x: Tensor, y: Tensor) -> Tensor:
        return x + y

    __call__ = proxy(forward)

    another_call = proxy(forward)

model = MyModule()

x = Tensor()
y = Tensor()
z1 = model(x, y)  # TypeError: forward() takes 2 positional arguments but 3 were given
z2 = model.another_call(x, y)  # TypeError: (same as above)
```

Note that this code crashes at runtime.

I'm not getting the same results you seem to be getting here. For me, the type of `z1` is `Any` and the type of `z2` is `Unknown` because the expression `model.another_call` is invalid from a type perspective. Both of these results are expected in this case.

One thing to keep in mind is that pyright always honors type declarations if they are present. That's applies for symbols in a class hierarchy. So if a parent class declares the type of a symbol but a child class does not, the type information is taken from the declared type in the parent class. If you want to re-declare the type in the child class to be some other (narrower, and therefore compatible) type, you can add a declaration in the child class.

```python
class Parent:
    x: float | str

class Child1(Parent):
    x = 3

class Child2(Parent):
    x: int = 3

reveal_type(Child1().x) # Revealed type is "float | str", not "int"
reveal_type(Child2().x) # Revealed type is "int"
```

All of this looks to be working as intended in pyright, so I'm going to close the issue. If you have more questions or think that there is an actual bug here, please post a response.

**Closed** 2022-03-24 17:09 UTC
Labels: as designed

**Comment by ppeetteerrs** [comment] 2022-03-24 17:37
Hi, apologies for the error in my code. I have updated the function signature of `forward`, please kindly see if you are able to replicate the results on your side.

![image](https://user-images.githubusercontent.com/8547778/159976833-bd6f239b-c6ae-4762-bfff-0324083b8c63.png)
![image](https://user-images.githubusercontent.com/8547778/159976846-f861de6e-f362-40fb-ae63-738e66fe2bd6.png)

**Comment by erictraut** [comment] 2022-03-24 17:55
Yes, this is expected behavior. The symbol `__call__` has a declared type in the parent class but no declared type in the child class. The type declaration is therefore preferred. The symbol `another_call` does not exist in the base class and has no type declaration in the child class, so its type is inferred.

If you want to override the declared type of `__call__`, you will need to add a type declaration for it in `MyModule`. Something like:
```python
    __call__: Callable[[Tensor, Tensor], Tensor] = proxy(forward)
```

**Comment by erictraut** [comment] 2022-03-24 17:57
If you want a deeper understanding of declared vs inferred types, please refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#understanding-typing).

**Comment by ppeetteerrs** [comment] 2022-03-24 18:05
Thanks for the comment. I do understand why that happens, but can I know why is that design choice made (i.e. why should declared type in the parent class override the inferred type in the child class)? Since I assume that putting `__call__ = proxy(forward)` suggests clearly that I want `__call__` to take the return type of `proxy(forward)` instead of the declared type in its parent class.

**Comment by erictraut** [comment] 2022-03-24 19:10
Type inference is ambiguous. Look at my example above. Is the intent for `Child1.x` to be typed as `float | str` or `int`? If someone has taken the time to provide a type _declaration_, it should not be ignored and overridden by a potentially-ambiguous inferred type. You will find the same design decision in most languages that support type annotations and type inference.

In your case, the assigned type of `__call__` is validated against the declared type, just as in my example where `x = 3` is validated against the declared type of `float | str`. So what you're doing is consistent with the declared type, but the inferred type should not _override_ the declared type. If you want to declare a different (narrower) type for your child class, that is your prerogative. Absent a new type declaration, pyright will use the existing type declaration.

**Comment by ppeetteerrs** [comment] 2022-03-24 19:13
That makes sense, thank you for the explanation!
