### ISSUE TITLE
Stub generator trims source code docstrings to 32 characters in the stub

### ISSUE THREAD

**Issue by argilya** [microsoft/pyright#3503] opened 2022-05-24 14:24 UTC
Not sure if this is a bug, or expected behavior but see below.

**Describe the bug**
Automatic stub generator trims source code docstrings to 32 characters in the stub

**To Reproduce**
1. Use Pyright CLI tool to generate a stub for any third-party package. In my case it's `datashader==0.13.0`. (I tried it with `numpy` too, with the same outcome.)
2. Observe that the stub retains just ~32 chars from the original docstring.

**Expected behavior**
I would expect the tool to preserve the entire docstring.

**Screenshots or Code**
See example here for the `Axis` class. On the left is the stub generated by Pyright, on the right is source code.
![2022-05-24_09-19](https://user-images.githubusercontent.com/100630262/170058586-ac831ec7-79d8-43e1-975f-a059e2d07cdd.png)

**VS Code extension or command-line**
This is with the CLI tool, version `1.1.248`.

Thank you!

**Comment by erictraut** [comment] 2022-05-24 15:14
This is a duplicate of #3500, which will be fixed in the next release.

**Comment by erictraut** [comment] 2022-05-25 05:30
This is addressed in pyright 1.1.249, which I just published. It will also be included in the next release of pylance.

**Closed by erictraut** 2022-05-25 05:30 UTC
Labels: bug, addressed in next version
