### ISSUE TITLE
Pyright gets stuck in analysis on specific file

### ISSUE THREAD

**Issue by QuantFreedom1022** [microsoft/pyright#6280] opened 2023-10-31 22:14 UTC
So it seems that all my files have syntax highlighting but once i move over to this one file it stops highlighting ... i am not sure if it is because the file is too big ... but once it grew to a specific point it seems to have stopped working ... this happens on .40 and .50 so i am not sure what could be the problem ... i have attached my logs and feel free to ask me any questions because i am not sure what more information i can give to help you guys out ... thank you 

although i will say it does seem that if i comment out a bunch of code that the highlighting does come back ... but once i uncomment the code the highlighting breaks ... so it seems to be something in here ... around line 336 ... the self.inc_pos_calculator 
![image](https://github.com/microsoft/pylance-release/assets/95321908/1de01e20-d301-4b35-a912-de651486fb8c)

actually this is so weird .... it seems to be this one stringer=self.stringer ... for some reason it doesn't like that ... but everything else seems to be fine ... even though i have self.stringer in other places and it seems to be fine there too.

![image](https://github.com/microsoft/pylance-release/assets/95321908/6551fbbe-90b9-4932-bd8b-8b2ae9e4d43a)

## repo file that is the problem
https://github.com/QuantFreedom1022/QuantFreedom/blob/neo/quantfreedom/live_mode_pylance.py

## Environment data

-   Language Server version: 2023.10.50 and .40
-   OS and version: windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.10.10

## Expected behavior

![image](https://github.com/microsoft/pylance-release/assets/95321908/126189a9-6984-427b-87fe-55018ceaaaf7)

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/95321908/b15b25d1-eaa0-4c17-ad6c-1858bb259446)

## Logs 
[pylance_log.txt](https://github.com/microsoft/pylance-release/files/13221701/pylance_log.txt)

**Comment by QuantFreedom1022** [comment] 2023-10-31 22:50
@rchiodo  ok thank you ... but did you see in my edit of the issue that it is one specific line that is causing the problem ... if i comment it out then everything loads perfectly fine ... not sure if this helps you out or not .... and also i have the stringer=self.stringer in other places and it is fine in those other places but not at this specific point

![image](https://github.com/microsoft/pyright/assets/95321908/a38055f3-5d52-4281-aff3-182715df015b)

**Comment by rchiodo** [comment] 2023-10-31 23:10
@quantfreedom1022 I saw your update. That will likely help whoever looks at this as to what the root cause is.

**Comment by erictraut** [comment] 2023-11-02 07:14
I'm able to repro the problem, and I'll investigate further.

**Comment by QuantFreedom1022** [comment] 2023-11-02 14:31
> I'm able to repro the problem, and I'll investigate further.

@erictraut thank you ... it is so weird that it is happening on just that one line of code ... i can have that same line in other places but that one function has a problem with that line for some reason

**Comment by QuantFreedom1022** [comment] 2023-11-02 22:40
@rchiodo  ... why did you close this ... the bug is still happening?

**Comment by QuantFreedom1022** [comment] 2023-11-02 22:41
@erictraut i just tried something and if i comment out logger=self.logger then stinger=self.stinger actually works and pylance processes the info ... but then if i uncomment logger then logger becomes the thing that isn't processed ... so i think it might be something with having to many params that i am sending to the pos calculator or something

**Comment by erictraut** [comment] 2023-12-05 08:11
Thanks for your patience on this issue. It took me a while to get to the bottom of the problem. It turns out that it's related to [this issue](https://github.com/microsoft/pyright/issues/6645), and the same bug fix addresses the issue you're seeing. This change will be included in the next release of pyright and will picked up by pylance at some point in the future.

With this change to pyright, the analysis time for your file goes from about 66sec to about 2sec on my machine. That's still a really long time for a single file. Most files can be analyzed fully in 10's of milliseconds.

Your code poses a big challenge for a static type checker. It is largely untyped, so the types of the instance variables need to be inferred from context. The types of many of these instance variables depend on the types of other instance variables. The code flow graph is also complex because it involves nested loops with multiple nested `try` statements. You're also using tuple unpacking on assignment. This creates dependencies between many instance variables.

There are limits to the complexity of code pyright can analyze in a reasonable amount of time. It computes a "complexity score" for each function and avoids type analysis if that complexity score exceeds a certain limit. The function in your code comes close to this limit but doesn't quite exceed it.

If you want pyright (or pylance) to be more responsive, you might consider the following changes to your code:
1. Refactor your code into subroutines
2. Avoid using nested `try` statements within a single function or method.
3. Add type annotations for some or all of your instance variables.

Some combination of these simplifications will likely bring the total analysis time for the file down to <100ms.

**Comment by erictraut** [comment] 2023-12-06 03:33
This is addressed in pyright 1.1.339, which I just published. It will also be included in a future release of pylance.

**Closed by erictraut** 2023-12-06 03:33 UTC
Labels: bug, addressed in next version
