### ISSUE TITLE
Function and callable object not always treated equally

### ISSUE THREAD

**Issue by kjagiello** [microsoft/pyright#8558] opened 2024-07-26 20:16 UTC
I am facing some problems when trying to pass in a callable to `Producer.pipe`. It works fine when passing in a function, but it does not work when passing in a callable object, even though pyright tells me that their signatures are equal. Hopefully the example below explains it better.

**EDIT:** I am not sure anymore if this is really about callables. Changing the signature of `Producer.pipe` to `def pipe[NO](self, other: Transformer[O, NO]) -> Producer[NO]: ...` seems to result in the same error.

Repro case ([playground](https://pyright-play.net/?pyrightVersion=1.1.373&strict=true&code=GYJw9gtgBA%2BjwFcAuCQFM5QJYQA5hCSgEMA7UsJYpLMUgZwChHRIoBjMAGy7XZrr0AdMQBG7bHgJEAymgCOCNKXZoW4aEgCeuLKQDmk-ISgBhYjzG8ANFACSSNCGoFmjdl2L16UAArgAEwRVEABtAHkAXQAuRih4qAC0YFgYPSwkOAAKejQuYFtgaLMLT1FeUNDI2yiASmKhRriEpJTdXDRQgDkonLyCqEoACydi80tyzojqqB7I2qgAWgA%2BP0Dgp26ohqbmDy8fABVnBmACCE27Gpjm%2BNbU9MyYPvzCsdKrKbsZuqXVrroaB2QluiWSqXYpWyuVeJBA%2BmKdgWKyg4WBbnuuHWISyyNWDicLjCckUylUoT0SEiMSgjRB9ywSVING0oUOkSyxHhiMcziQBDZ8z%2B9l5RMF6OYAGIoAB1AgAayYjOULK0WSxYCCONqtUY-k1GxA6uxTlqQnaaCyyuZGS0usY0oAImA0D4KEQAO4KvUmo0arWm81YDpZY5kehnEAXI3W1U6qVQQ4jKD0LD6UjUVCuuFobBMmiQriMdAANzQFhg2hDsdtutL5a4lZ0lrDp3OTit%2BdrQjghcbMFqQA)):

```python
from __future__ import annotations
from collections.abc import Sequence
from typing import Callable, Iterator

class Producer[O]:
    def __init__(self, f: Callable[[], O]): ...
    def pipe[NO](self, other: Callable[[O], NO]) -> Producer[NO]: ...

class Transformer[I, O]:
    def __init__(self, f: Callable[[I], O]) -> None: ...
    def __call__(self, arg: I) -> O: ...

def producer() -> Iterator[Sequence[int]]: ...
def identity[T](arg: Iterator[T]) -> Iterator[T]: ...

# Works
identity(producer())
Producer(producer).pipe(identity)

# Does not work
Producer(producer).pipe(Transformer(identity))

# The signatures are identical
reveal_type(identity)
reveal_type(Transformer(identity).__call__)
```

Pyright output:

```
repro.py:21:25 - error: Argument of type "Transformer[Iterator[T@identity], Iterator[T@identity]]" cannot be assigned to parameter "other" of type "(Iterator[Sequence[int]]) -> NO@pipe" in function "pipe"
    Type "Transformer[Iterator[T@identity], Iterator[T@identity]]" is incompatible with type "(Iterator[Sequence[int]]) -> NO@pipe"
      Parameter 1: type "Iterator[Sequence[int]]" is incompatible with type "Iterator[T@identity]"
        "Iterator[Sequence[int]]" is incompatible with "Iterator[T@identity]"
          Type parameter "_T_co@Iterator" is covariant, but "Sequence[int]" is not a subtype of "T@identity"
            Type "Sequence[int]" is incompatible with type "T@identity" (reportArgumentType)
repro.py:24:13 - information: Type of "identity" is "(arg: Iterator[T@identity]) -> Iterator[T@identity]"
repro.py:25:13 - information: Type of "Transformer(identity).__call__" is "(arg: Iterator[T@identity]) -> Iterator[T@identity]"
```

Pyright version:

```
1.1.373
```

**Comment by erictraut** [comment] 2024-07-26 21:27
The problem here is that the expression `Transformer(identity)` evaluates to type `Transformer[Iterator[T@identity]]`. After this call, the type variable `T@identity` goes out of scope, so it can no longer be solved. In general, type variables can be "solved" only in the context of a call in which they are involved. Here your code involves two separate calls, and `T@identity` gets orphaned after the first call.

Mypy produces a [similar error](https://mypy-play.net/?mypy=latest&python=3.12&enable-incomplete-feature=NewGenericSyntax&flags=no-warn-no-return&gist=f4b78ee143b1cb6f745ee00032c1603a), but it replaces `T@identity` with `Never` after the first call. I don't find either type checker's error message particularly clear here, but I slightly prefer pyright's.

A type checker could arguably convert `T@identity` to an `Unknown` if it goes out of scope and hasn't been solved, but that has other downsides. It would eliminate all type safety for the second call resulting in false negatives.

The part of a type checker that's responsible for determining the values of type variables is called a "constraint solver". The behaviors of constraint solvers are unfortunately not well specified in the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html) currently. I'm hopeful that we can fill in more of the unspecified behaviors over time. Until then, it's probably best for pyright to stick to behaviors that are similar to mypy's unless there's a good [reason for it to deviate](https://microsoft.github.io/pyright/#/mypy-comparison?id=constraint-solver-behaviors).

In any case, pyright is working as intended here, so I'm going to close the issue.

**Closed by erictraut** 2024-07-26 21:27 UTC
Labels: bug

**Comment by kjagiello** [comment] 2024-07-26 22:35
Thanks for the thorough explanation!

**Comment by kjagiello** [comment] 2024-07-31 09:14
I was surprised to see that the code above started typechecking correctly on 1.1.374.

```python
from __future__ import annotations
from collections.abc import Sequence
from typing import Callable, Iterator

class Producer[O]:
    def __init__(self, f: Callable[[], O]): ...
    def pipe[NO](self, other: Callable[[O], NO]) -> Producer[NO]: ...

class Transformer[I, O]:
    def __init__(self, f: Callable[[I], O]) -> None: ...
    def __call__(self, arg: I) -> O: ...

def producer() -> Iterator[Sequence[int]]: ...
def identity[T](arg: Iterator[T]) -> Iterator[T]: ...

# Works
identity(producer())
a = Producer(producer).pipe(identity)

# Should not work
b = Producer(producer).pipe(Transformer(identity))

reveal_type(a)
reveal_type(b)
```

Output:
```
Type of "a" is "Producer[Iterator[Sequence[int]]]"
Type of "b" is "Producer[Iterator[Sequence[int]]]"
```

([playground](https://pyright-play.net/?strict=true&reportMissingModuleSource=true&code=GYJw9gtgBA%2BjwFcAuCQFM5QJYQA5hCSgEMA7UsJYpLMUgZwChRIoBjMAG07TZrvoA6YgCM22PASIBlNAEcEaUmzTNw0JAE9cWUgHMJ%2BQlADCxbqJ4AaKAEkkaENQKNGbTsXr0oABXAATBBUQAG0AeQBdAC5GKDiofzRgWBhdLCQ4AAp6NE5gG2Ao03MPER4QkIibSIBKIsEG2PjE5J1cNBCAOUjs3PyoSgALRyKzCzKO8KqoboiaqABaAD5fAKDHLsj6xrcPLygAFScGYAIIDdtq6Ka4lpS0jJhevILRkstJ22naxZXOujQ20ENwSSRSbBKWRyLxIID0RVs82WUDCQNcd1wa2CmSRK3sjmcoVkCiUKhCuiQEWiUAawLuWESpBoWhCBwimWIcIRDicSAIrLmvzsPMJArRjAAxFAAOoEADWTAZSmZmkymLAgWxNRqjGIUAAvKsNesQGqsY4aoI2mhMkqmelNDrJVBpIMwAhOP4oBQiAB3eWMEQGo2axxm43BS3WzJHMj0U4gc6mu0q7WudAANzQ5hgWnaHJ1meznFz2htIhqQA))

**Comment by erictraut** [comment] 2024-07-31 15:54
> Was that intended?

This wasn't specifically intended, but 1.1.374 includes some _significant_ modifications in how pyright handles constraint solving. The new algorithm is simpler and more consistent — and in some ways more lax in requiring that type variables be solved in the context of a given call. I'm glad to hear that this code now type checks. Thanks for letting me know!
