### ISSUE TITLE
The type of elements in a tuple containing an unpacked tuple

### ISSUE THREAD

**Issue by multimeric** [microsoft/pyright#3664] opened 2022-07-06 13:42 UTC
**Describe the bug**
Pyright will assume that elements of a tuple that contains an unpacked tuple, have the type of the union of all types in that tuple.

**To Reproduce**

The simplest example I can devise to demonstrate this is:
```python
from typing import Tuple
from typing_extensions import Unpack

def foo(param: Tuple[int, Unpack[Tuple[str, ...]], str]):
    x: int = param[0]
```
Which outputs:
```
/tmp/tmp.y2jhUrUaKb/test6.py
  /tmp/tmp.y2jhUrUaKb/test6.py:5:14 - error: Expression of type "int | str" cannot be assigned to declared type "int"
    Type "int | str" cannot be assigned to type "int"
      "str" is incompatible with "int" (reportGeneralTypeIssues)
```

You may note I have used a specific example from [PEP-0646](https://peps.python.org/pep-0646/#unpacking-unbounded-tuple-types), which I believe is not correctly implemented. The PEP says:

> This enables us to specify types such as Tuple[int, *Tuple[str, ...], str] - a tuple type where the first element is guaranteed to be of type int, the last element is guaranteed to be of type str, and the elements in the middle are zero or more elements of type str. 

**Expected behavior**
As stated in the PEP, the first item should have type `int`, and the subsequent items should have type `str`. None of these should have a union type.

**Additional context**
To further diagnose this behaviour, I tried to reveal various types. This clarifies that although the type of the tuple itself is being correctly stored, once we actually index this tuple, the specific type at each position is being lost:
```python
from typing import Tuple
from typing_extensions import Unpack

def foo(param: Tuple[int, Unpack[Tuple[str, ...]], str]):
    reveal_type(param)
    reveal_type(param[0])
    reveal_type(param[1])
    reveal_type(param[-1])
```
```
  /tmp/tmp.y2jhUrUaKb/test5.py:5:17 - information: Type of "param" is "Tuple[int, *tuple[str, ...], str]"
  /tmp/tmp.y2jhUrUaKb/test5.py:6:17 - information: Type of "param[0]" is "int | str"
  /tmp/tmp.y2jhUrUaKb/test5.py:7:17 - information: Type of "param[1]" is "int | str"
  /tmp/tmp.y2jhUrUaKb/test5.py:8:17 - information: Type of "param[-1]" is "int | str"
```

pyright 1.1.257

**Comment by erictraut** [comment] 2022-07-06 15:23
Yes, this is intended behavior. If you include an unpacked tuple with an indeterminate length, pyright falls back on this behavior. You'll note that if you include an unpacked tuple of determinate length, it works.

Pyright could arguably handle some of the edge cases where you are indexing into parts of the resulting tuple that is unaffected by the indeterminate length, but this would involve a bunch of additional complex logic, and I'm reluctant to add it unless/until we receive signal that it's desired from more users. For now, I'm going to close this. We might consider reopening it in the future if it receives enough upvotes.

**Closed** 2022-07-06 15:23 UTC
Labels: enhancement request
