### ISSUE TITLE
Support type narrowing TypedDict based on field that may be `Union[Literal[...], list[...]]`

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/pyright#4377] opened 2022-12-26 14:52 UTC
The following works as expected:

```python
from typing import TypedDict, Literal, Union, Generic, TypeVar

class Foo(TypedDict):
    type: Literal['foo']

class Bar(TypedDict):
    type: Literal['bar']

def foo(foo_or_bar: Union[Foo, Bar]):
    if foo_or_bar['type'] == 'foo':
        reveal_type(foo_or_bar) # Type of "foo_or_bar" is "Foo"
```

However when we change the type of `Bar.type` to `list[str]` then the type narrowing no longer works as expected:

```python
class Foo(TypedDict):
    type: Literal['foo']

class Bar(TypedDict):
    type: list[str]

def foo(foo_or_bar: Union[Foo, Bar]):
    if foo_or_bar['type'] == 'foo':
        reveal_type(foo_or_bar) # Type of "foo_or_bar" is "Foo | Bar"
```

I feel obliged to note that making `type` have the type `Union[Literal[...], list[str]]` isn't my idea ... I am just trying to create a Python library for the MediaWiki API which returns such JSON in its [paraminfo](https://www.mediawiki.org/w/api.php?action=help&modules=paraminfo) action ...

**Comment by erictraut** [comment] 2022-12-26 15:27
The narrowing logic for discriminated TypedDict fields is working as designed. It's intended for the case where multiple TypedDicts contain a shared field with a literal value that distinguish between them. It looks like you're using TypedDicts in a different (more atypical) manner here.

We might consider extending this type narrowing functionality in the future if there's sufficient demand, but for now I'm going close this feature request for now because, in my experience, this use case is quite atypical and probably not a design pattern that should be promoted.

**Closed by erictraut** 2022-12-26 15:27 UTC
Labels: enhancement request

**Comment by not-my-profile** [comment] 2022-12-26 15:51
Fair point, I'll just have my library postprocess the MediaWiki API result to support type narrowing.
