### ISSUE TITLE
flask_login model missing import 

### ISSUE THREAD

**Issue by Rahul-Chotliya-grow** [microsoft/pyright#8668] opened 2024-08-06 05:54 UTC
I'm importing the flask_login library and some classes from it, i'm facing pylance missing imports

**Comment by erictraut** [comment] 2024-08-06 06:03
This is almost definitely not a bug in pyright. You haven't provided enough details for me to help you diagnose the problem. It's most likely either a configuration issue or a bug in a stub file or inline type information within the library package.

I'm going to close the issue, but if you'd like to provide additional details, I can try to help you diagnose your problem. I would need a minimal, self-contained code sample and a list of the packages (along with versions) that the code depends upon. If you have stub packages installed, I'd need those versions as well.

**Closed by erictraut** 2024-08-06 06:03 UTC
Labels: enhancement request
