### ISSUE TITLE
Pyright hanging a vscode process when analyzing requests library

### ISSUE THREAD

**Issue by microcoder** [Microsoft/pyright#82] opened 2019-04-22 07:45 UTC
**Describe the bug**
Pyright hanging a vscode process when openned at vscode the *requests* library

**To Reproduce**
Create a new python file and import the *requests* library:

```python
import requests
```
Then click CTRL + Left mouse click to open the *requests* library. After then a vscode process hangup.

**Comment by erictraut** [comment] 2019-04-22 08:14
Thanks for the bug report. Which version of the Pyright extension are you running? There was a bug in 1.0.15 that could explain this. It's fixed in 1.0.16. I'm not able to repro the problem with the latest version.

**Comment by microcoder** [comment] 2019-04-22 08:31
@erictraut I use last version of Pyright 1.0.16 and VS Code last version - 1.33.1

When i opening the *requests*:
![Screenshot_20190422_112656](https://user-images.githubusercontent.com/2853555/56491651-ed248400-64f1-11e9-9b2e-bb7de7bd035f.png)

Pyright uses 100% a core of CPU:

![Screenshot_20190422_112721](https://user-images.githubusercontent.com/2853555/56491728-2a891180-64f2-11e9-8df7-43789c058879.png)
![Screenshot_20190422_112749](https://user-images.githubusercontent.com/2853555/56491735-2e1c9880-64f2-11e9-809d-18fec65482f0.png)

**Comment by erictraut** [comment] 2019-04-22 08:42
Ah, I was opening the stub file, and you were opening the implementation file. I'm now able to repro the problem. I'll dig into it and work on a fix.

**Comment by microcoder** [comment] 2019-04-22 08:45
@erictraut Thank You!

**Comment by erictraut** [comment] 2019-04-25 05:40
The bug is triggered by code in the requests module that performs the following:
```
for v in vs
   if <condition>
      v = [v]
```

This causes pyright to infer the type of v to be either `X` or `List[X]`. As it analyzes the loop, it adds more variants (`List[List[X]]`, `List[List[List[X]]]`, etc.). This results in an infinite loop.

I've added a partial fix that prevents infinite recursion in this particular case, but I'd like to find a more general fix. I'm going to leave this bug open until I've fully fixed the problem.

**Comment by erictraut** [comment] 2019-05-05 19:43
I've fixed the underlying root cause of the problem in 1.0.24

**Closed by erictraut** 2019-05-05 19:43 UTC
Labels: bug, fixed in next version
