### ISSUE TITLE
Pyright cannot resolve 3rd party libraries imports - Neovim

### ISSUE THREAD

**Issue by alanmicah** [microsoft/pyright#4340] opened 2022-12-14 22:59 UTC
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**
In Neovim when I attempt to import a 3rd party library such as NumPy I get an error 'Pyright:  Import "NumPy" cannot be resolved'.
I have attempted this some other 3rd party libraries and the same thing is happening. Built in libraries don't seem to produce errors. [1]

However Numpy I am still able to get LSP suggested completions and function definitions. I have shown an example image below with `numpy.array()` [2]. But with other 3rd party libraries, for example, cv2 (OpenCV) I am shown the LSP suggested completion for importing but I do not get LSP completions or definitions when trying to use cv2 functions. [3]

Another example is with PyTorch I get import cannot be resolved errors however, I still am able to get LSP suggested completions and definitions for PyTorch functions, example image shown below [4].

bs4 says "Import bs4 could not be resolved from source", however LSP suggested completions and definitions still work.

In Neovim printing `print(sys.version)` reveals: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]

Pylance works in VSCode completely fine with no issues.

**To Reproduce**
Using within an activated Conda environment
- macOS 12.6.1
- iTerm2 3.4.16
- Neovim v0.8.0
- pyright 1.1.284 (installed globably via NPM) 
-  lua files: `use("neovim/nvim-lspconfig")` and `require("lspconfig").pyright.setup(config())`

Conda/pip and example libraries
- conda 22.9.0 (miniconda)
- pip 22.3.1
- Python 3.10.8 (/Users/{user}/opt/miniconda3/bin/python)
- opencv-python 4.6.0.66
- numpy 1.23.4
- torch                     1.14.0.dev20221031          pypi_0    pypi
- torchvision               0.15.0.dev20221031          pypi_0    pypi

**Expected behavior**
To not display the error and be able to import and use installed 3rd party libraries via pip and/or conda.

**Screenshots or Code**
Import not resolved issue [1]
<img width="475" alt="Screenshot 2022-12-14 at 22 02 08" src="https://user-images.githubusercontent.com/31675641/207724910-3cee1a1a-9ee9-42ff-b8be-a6f071bfae42.png">
---

Completion with definitions working for `import numpy` [2]
<img width="883" alt="Screenshot 2022-12-14 at 22 29 29" src="https://user-images.githubusercontent.com/31675641/207729594-f810ebe9-b890-493a-8e03-2787dc7da62d.png">
---

Errors with 3rd party library imports and functions. [3]
<img width="703" alt="Screenshot 2022-12-14 at 22 22 23" src="https://user-images.githubusercontent.com/31675641/207729690-fba36403-511d-426f-8ab0-4771ec0d867b.png">
---

PyTorch examples [4]
<img width="745" alt="Screenshot 2022-12-14 at 22 46 52" src="https://user-images.githubusercontent.com/31675641/207731998-852ed4cf-262b-4ed2-94b3-966d10c40be5.png">

<img width="947" alt="Screenshot 2022-12-14 at 22 44 46" src="https://user-images.githubusercontent.com/31675641/207731974-56da37f8-9ef7-4722-a808-260825d175df.png">
---

I'm quite new to Neovim and apologise for any ignorance I may have.

**Comment by erictraut** [comment] 2022-12-14 23:11
This is a configuration issue, not a bug. Moving to a discussion topic.

**Closed as completed** 2022-12-14 23:11 UTC
Labels: as designed
