### ISSUE TITLE
Any reported as incompatible with a type, but only when inferred.

### ISSUE THREAD

**Issue by adampauls** [microsoft/pyright#7134] opened 2024-01-26 18:06 UTC
**Code or Screenshots**
If possible, provide a minimal, self-contained code sample (surrounded by triple back ticks) to demonstrate the issue. The code should define or import all referenced symbols.

```python
from typing import Any, Generic, TypeVar

T = TypeVar("T")
UnionT = TypeVar("UnionT", bound=list[int] | list[str])


class Super(Generic[T]):
    pass


class Sub(Super[T]):
    pass


def foo(t: type[T]) -> Sub[T]:
    raise NotImplementedError


def bar(super: Super[UnionT]) -> None:
    pass


explicit: Sub[Any] = foo(Any)
bar(explicit) # no error

implicit = foo(Any)  # reveal_type(implicit) gives: Type of "implicit" is "Sub[Any]"
# error: Argument of type "Sub[Any]" cannot be assigned to parameter "super" of type "Super[UnionT@bar]" in function "bar"
#    "Sub[Any]" is incompatible with "Super[UnionT@bar]"
#     Type parameter "T@Super" is invariant, but "Any" is not the same as "UnionT@bar" (reportArgumentType)
bar(implicit)
```

I'm aware this code is doing some pretty funny things. I'm not clear what correct behavior should be, but it seems like it should not differ between the explicit type annotation case and the inferred one. 

**VS Code extension or command-line**
Command-line 1.1.348.

**Comment by erictraut** [comment] 2024-01-26 18:15
This is a duplicate of https://github.com/microsoft/pyright/issues/7082. The call to `foo(Any)` should result in an error because `Any` is not compatible with `type[T]`.

**Closed** 2024-01-26 18:15 UTC
Labels: bug
