### ISSUE TITLE
Numpy.alen() resolves to returning Unknown while it returns int

### ISSUE THREAD

**Issue by MikhailArkhipov** [microsoft/pyright#422] opened 2019-12-13 22:23 UTC
**Describe the bug**
`numpy.alen()` resolves to returning `Unknown` while it returns `int`

**To Reproduce**
- Set `"pyright.useLibraryCodeForTypes": true,`
- install and import `numpy`
- type numpy.alen()
- Hover says function returns `Unknown`.

**Expected behavior**
Expected `alen()` to return `int` since it just calls builtin `len()`
```python
    try:
        return len(a)
    except TypeError:
        return len(array(a, ndmin=1))
```
![image](https://user-images.githubusercontent.com/12820357/70836122-144b0100-1db4-11ea-84f4-1167af7c0787.png)

**Comment by erictraut** [comment] 2019-12-14 03:05
Hmm, I can't explain why you were seeing that hover string. I don't see any code in the numpy sources that would result in a `Union` type for `alen`. I would have also expected to see the doc strings appear in the hover if you were using the real numpy sources.

Did you perhaps have a generated type stub file in place? Or perhaps we're using different versions of numpy?

Here's what it looks like on my system:

![Screen Shot 2019-12-13 at 7 05 06 PM](https://user-images.githubusercontent.com/7040122/70842684-7d923a80-1ddb-11ea-9805-a999ed5be062.png)

**Comment by MikhailArkhipov** [comment] 2019-12-16 20:39
in 0.1.10 on two different machines I get

![image](https://user-images.githubusercontent.com/12820357/70940680-b7438b00-1fff-11ea-8958-41a789b06a6f.png)

looks like formatting issue. Same with `all`

![image](https://user-images.githubusercontent.com/12820357/70940760-e6f29300-1fff-11ea-8d5e-8dea94b0b7dc.png)

**Comment by erictraut** [comment] 2019-12-17 09:13
@MikhailArkhipov, I'm still not able to repro. There must be something different about your setup. What version of numpy are you using?

Since you're able to repro, please feel free to debug it on your system. If you need help getting started with debugging, let me know and I'll give you some pointers.

**Comment by MikhailArkhipov** [comment] 2019-12-17 17:59
Sure, I do that. Are there instructions on the debugging setup?

**Comment by MikhailArkhipov** [comment] 2019-12-19 18:31
The issue is in completion item documentation. Looks like it needs line break after name.
![image](https://user-images.githubusercontent.com/12820357/71199400-bd797780-224a-11ea-9f02-106facd45ad6.png)

**Comment by erictraut** [comment] 2019-12-19 18:43
Thanks for tracking that down. That explains the formatting issue, but it doesn't explain why you're seeing a union between Unknown and a function that returns Any while I'm seeing something different. Is that explained by a difference in numpy versions perhaps?

**Comment by erictraut** [comment] 2019-12-19 18:44
I just pushed a fix for the formatting issue.

**Comment by MikhailArkhipov** [comment] 2019-12-19 19:05
`numpy-1.16.2.dist-info` on 3.7. I'll see what's up there.

**Comment by erictraut** [comment] 2019-12-21 14:41
OK, I was using numpy 1.14.x. When I upgraded to 1.16.x, I was able to repro the problem you reported. The issue is that the newer version added a decorator to the `alen` method. This decorator obscures the true signature of `alen`, resulting in the signature you see.

I don't see a way to fix this without some really gross special-case hacks. The right solution here is to have a high-quality type stub for numpy that provides proper type annotations.

**Closed** 2019-12-21 14:41 UTC
Labels: as designed
