### ISSUE TITLE
Raw string interpolation doesn't count as accessing variable

### ISSUE THREAD

**Issue by vberlier** [microsoft/pyright#1830] opened 2021-05-06 13:18 UTC
With the latest release Pyright reports an error in the following code:

```python
def foo():
    message = "hello"  # Variable "message" is not accessed
    print(fr"{message}")
```

**Comment by erictraut** [comment] 2021-05-06 14:28
Thanks for the bug report. This regression was caused by a recent optimization. I've fixed the problem and added some tests to prevent future regressions for "fr" strings.

**Comment by erictraut** [comment] 2021-05-06 21:46
This is fixed in 1.1.138, which I just published.

**Closed by erictraut** 2021-05-06 21:46 UTC
Labels: addressed in next version, bug
