### ISSUE TITLE
Maximum Call Stack Size Exceeded (v1.1.184)

### ISSUE THREAD

**Issue by dpipemazo** [microsoft/pyright#2525] opened 2021-11-02 18:49 UTC
Note: if you are reporting a wrong signature of a function or a class in the standard library, then the typeshed tracker is better suited for this report: https://github.com/python/typeshed/issues.

**Describe the bug**

We are hitting RangeError: Maximum Call Stack Size Exceeded on our pyright workflows. [CircleCI Logs](https://app.circleci.com/pipelines/github/elementary-robotics/atom/2536/workflows/cb8c1cba-9a5a-4c8c-bc1c-fd5bff84187b/jobs/22131)

We are seeing this after upgrading pyright to `1.1.184` and installing via npm.

We did not see this error with the same workflow on version `1.1.171` and confirmed this by reverting the version being installed [CircleCI Logs](https://app.circleci.com/pipelines/github/elementary-robotics/atom/2537/workflows/c5d05748-6003-4e5a-bb15-dc836a1663bf/jobs/22163)

This is running `pyright` on the Atom python language client codebase, which can be found [here](https://github.com/elementary-robotics/atom/tree/latest/languages/python)

We are using the `pyrightconfig.json` [here](https://github.com/elementary-robotics/atom/blob/latest/languages/python/pyrightconfig-ci.json)

**To Reproduce**

Should be able to reproduce locally running the command-line client on the atom codebase as being invoked in the CI system.

**Expected behavior**

Tests were passing as of 1.1.171.

**Screenshots or Code**

N/A

**VS Code extension or command-line**

Command-line

**Additional context**
Thank you for taking a look!

**Comment by erictraut** [comment] 2021-11-03 01:54
Thanks for reporting the problem. I found the cause of the regression, which was introduced in 1.1.177. The fix will be in the next release.

**Comment by erictraut** [comment] 2021-11-06 02:32
This is included in pyright 1.1.185, which I just published. It will also be included in the next release of pylance.

**Closed by erictraut** 2021-11-06 02:32 UTC
Labels: bug, addressed in next version
