### ISSUE TITLE
Wrong behavior going to definition on 3rd party libraries

### ISSUE THREAD

**Issue by luisiacc** [microsoft/pyright#3201] opened 2022-03-15 22:48 UTC
**Describe the bug**
```python
from django.utils.functional import cached_property
```
If I try to go to definition on `cached_property`, then it doesn't do anything, if i try to go to the definition of the package `django.utils.functional` it brings me to that file(`django/utils/functional.py`), what's weird is, after doing that, if I try again to go to definition on `cached_property`, then it succesfully goes to it's definition

This behavior is the same on all 3rd party libraries, just using this as an example, the builtin libraries apparenlty always go to the stubs definitions

**Expected behavior**
I would expect to go to the definition in `django.utils.functional` to the `cached_propery` on the 1st time I tried to.

**VS Code extension or command-line**
Command line v1.1.229

**Additional context**
The django package is inside a virtualenv

**Comment by erictraut** [comment] 2022-03-15 22:53
I'm not able to repro a problem using the Pyright VS Code Extension. When I choose "Go To Definition", it takes me to the expected location in the django code.

You mentioned that you're using the command-line version of pyright, but "Go To Definition" is an interactive LSP feature that is not present in the command-line version, so I'm a bit confused.

**Comment by luisiacc** [comment] 2022-03-15 23:10
I'm using it on neovim, which has an internall implementation of the LSP, this only happened with pyright server, they implement the Go to Definition with the `textDocument/definition` request I think

This is an example of the logs where the definition was not found:
```
[DEBUG][2022-03-15 18:58:05] .../vim/lsp/rpc.lua:347	"rpc.send"	{  id = 16,  jsonrpc = "2.0",  method = "textDocument/definition",  params = {    position = {      character = 11,      line = 23    },    textDocument = {      uri = "file:///home/acc/projects/maroon/core/users/models/users.py"    }  }}
[DEBUG][2022-03-15 18:58:05] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  id = 16,  jsonrpc = "2.0"}
[TRACE][2022-03-15 18:58:05] ...lsp/handlers.lua:487	"default_handler"	"textDocument/definition"	{  ctx = '{\n  bufnr = 13,\n  client_id = 2,\n  method = "textDocument/definition",\n  params = {\n    position = {\n      character = 11,\n      line = 23\n    },\n    textDocument = {\n      uri = "file:///home/acc/projects/maroon/core/users/models/users.py"\n    }\n  }\n}'}
[INFO][2022-03-15 18:58:05] ...lsp/handlers.lua:323	"textDocument/definition"	"No location found"
```

This is an example where it was found, by following the situation I described on the issue:
```
[DEBUG][2022-03-15 19:06:11] .../lua/vim/lsp.lua:1023	"LSP[pyright]"	"client.request"	2	"textDocument/definition"	{  position = {    character = 17,    line = 23  },  textDocument = {    uri = "file:///home/acc/projects/maroon/core/users/models/users.py"  }}	<function 1>	13
[DEBUG][2022-03-15 19:06:11] .../vim/lsp/rpc.lua:347	"rpc.send"	{  id = 53,  jsonrpc = "2.0",  method = "textDocument/definition",  params = {    position = {      character = 17,      line = 23    },    textDocument = {      uri = "file:///home/acc/projects/maroon/core/users/models/users.py"    }  }}
[DEBUG][2022-03-15 19:06:11] .../vim/lsp/rpc.lua:454	"rpc.receive"	{  id = 53,  jsonrpc = "2.0",  result = { {      range = {        end = {          character = 22,          line = 26        },        start = {          character = 6,          line = 26        }      },      uri = "file:///home/acc/projects/maroon/core/.venv/lib/python3.9/site-packages/polymorphic/models.py"    } }}
[TRACE][2022-03-15 19:06:11] ...lsp/handlers.lua:487	"default_handler"	"textDocument/definition"	{  ctx = '{\n  bufnr = 13,\n  client_id = 2,\n  method = "textDocument/definition",\n  params = {\n    position = {\n      character = 17,\n      line = 23\n    },\n    textDocument = {\n      uri = "file:///home/acc/projects/maroon/core/users/models/users.py"\n    }\n  }\n}',  result = { {      range = {        end = {          character = 22,          line = 26        },        start = {          character = 6,          line = 26        }      },      uri = "file:///home/acc/projects/maroon/core/.venv/lib/python3.9/site-packages/polymorphic/models.py"    } }}
```

I'm not sure this logs are helpful to you at all, just putting it here just in case.
I asked to one of the neovim devs and he told me it was probably a pyright thing

**Comment by erictraut** [comment] 2022-03-16 00:43
Are you able to repro this with a new, minimal project? The position in the example above is on line 23, which tells me that this wasn't from a minimal example. 

Does neovim also expose a "Go To Declaration" command? If so, does that also result in "No location found"?

**Comment by luisiacc** [comment] 2022-03-16 00:55
> Are you able to repro this with a new, minimal project?

Yes, I could reproduce it with just a main.py file with this content:
```python
from django.utils.functional import cached_property

m = cached_property()
```

the folder structure was just:
```
minimal-pyright
	- .venv/
	- main.py
```

> Does neovim also expose a "Go To Declaration" command? If so, does that also result in "No location found"?

Yes and yes, it's pretty much the same message on the logs I wrote above but with the lines positions changed.

**Comment by erictraut** [comment] 2022-03-16 21:34
I'm able to repro the problem, and I understand what's happening.

You've installed `django` which is an untyped library. You haven't installed any type stubs for it (although there exists a public `django-stubs` stub library).

You haven't enabled the `useLibraryCodeForTypes` configuration option in pyright. By default, this setting is off, and pyright therefore treats all imported symbols from untyped libraries as `Unknown`. It doesn't attempt to analyze the library other than to confirm that the import target is present and can be resolved. Because it doesn't analyze the source code in this case and the type is `Unknown`, any attempt to go to its definition will fail.

Once you manually open the target source file (the one that contains the symbol's definition) in your editor, pyright will analyze it and cache the analysis results in memory. You can then "go to definition", and it will show you the definition.

If you want "go to definition" to work immediately, you can enable `useLibrarySourceForTypes`. You can also install the `django-stubs` so you have high-quality type information for the django library. If you install the stubs, you don't need to enable `useLibrarySourceForTypes`, but "go to definition" will take you to the stub file rather than the implementation file. 

I'll note that pylance, which is the VS Code Language Server built on top of pyright, contains some extra functionality that tracks the definition and declaration independently so you "go to definition" takes you to the implementation and "go to declaration" takes you to the stub file. But pyright itself doesn't contain this extra functionality.

I'm going to close this issue because it's working as designed.

**Closed by erictraut** 2022-03-16 21:34 UTC
Labels: question

**Comment by luisiacc** [comment] 2022-03-16 22:59
Great breakdown! Thank you for explaining what is happening!
